### ISSUE TITLE
missing joint limit parsing

### ISSUE THREAD

**Issue by thomasfla** [stack-of-tasks/pinocchio#10]
I think we have to implement the join limit parsing in the URDF to integrate Pinocchio-dynamic in the SoT.
We could simply add an attribute list in the Model class for movable join only.

**Comment by aelkhour** [comment]
+1 for joint limit parsing.
Also task-space inverse dynamics solver requires velocity and torque limits, which are available in the URDF.

**Comment by olivier-stasse** [comment]
:+1:

**Comment by jcarpent** [comment]
Joint limits are now integrated in Pinocchio. Please refer to the devel branch of the project.
