### ISSUE TITLE
Please add collision check example in C++

### ISSUE THREAD

**Issue by Linjackffy** [stack-of-tasks/pinocchio#1008]
I've run the example geometry-models.cpp and load UR5's geometry mode. I want to check collision between UR5's links, but do not find any example in C++. Could you please add an exapmle in C++?

**Comment by jcarpent** [comment]
I will do it today.

**Comment by Linjackffy** [comment]
It help me a lot!
Thanks!

**Comment by jcarpent** [comment]
This is now done. @Linjackffy Feel free to provide feedback if needed.
