### ISSUE TITLE
Distance between located person and robot

### ISSUE THREAD

**Issue by dadouz** [stack-of-tasks/pinocchio#1023]
Hi Team,

do you have a python script enabling the distance calculation (for collision avoidance) between a person (his coordiantes xyz are available) and a robot. What i did is following:
- using an example (overview-urdf.py) from your repositoty i m able to calculate the xyz of all the axes 

In order to avoid: 
- interpolation approach for defining new points between all the axes
- generating theirs xyz values
- identifying the nearest point from the robot points to the person

the goal is to stop the robot when a predefined safety distance is reached between human (at the moment only the position of his hand) and the nearst robot point

regards,

**Comment by jcarpent** [comment]
@dadouz Is this issue still up to date?
