### ISSUE TITLE
robot_wrapper.centroidalMomentumVariation do not work with Numpy Array

### ISSUE THREAD

**Issue by pFernbach** [stack-of-tasks/pinocchio#1035]
See the code: https://github.com/stack-of-tasks/pinocchio/blob/722236daec20e4d9c39e458fba6ace2f3e38357d/bindings/python/pinocchio/robot_wrapper.py#L69-L71

The * operator should be replaced with .dot() .

**Comment by pFernbach** [comment]
Related to https://github.com/stack-of-tasks/pinocchio/issues/1026

**Comment by jcarpent** [comment]
@pFernbach Thanks for the report. #1036 has fixed your issue.
