### ISSUE TITLE
Robot Wrapper

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#108]
Create a robot wrapper similar to the existing python class containing a model and several data store in a vector achieving the interface between (model,data) and the main algorithms.

@aelkhour Do you have some precise requests?

**Comment by aelkhour** [comment]
- Not throwing exceptions would be great.
- Not making explicit dynamic allocations (using `new` operator) would be great.

If this conflicts with your development roadmap, then no worries.

**Comment by jcarpent** [comment]
Concerning the exceptions, why this precise request?

**Comment by aelkhour** [comment]
Our whole code base is supposed to be exception-free. I know this is not currently the case in pinocchio, which is why this is not a hard requirement.

**Comment by jcarpent** [comment]
Ok. If you want you can just use the instruction `-fno-exceptions` with gcc.
I think for lambda user, exceptions are mandatory that why we try to populate our code with them.

**Comment by aelkhour** [comment]
Noted, thanks.

**Comment by nmansard** [comment]
It indeed is: please no throw in construction and destruction (just 
image what can of torture you are generating on the poor stack when 
creating memory with a destruction phase to throw something).

**Comment by jcarpent** [comment]
A robot wrapper have been implemented in https://github.com/stack-of-tasks/tsid
