### ISSUE TITLE
setting joint limits

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/pinocchio#111]
Hello all,
It is currently difficult to write to Joint limits. I suppose the only way available is if I change the Eigen::VectorXd elements available in Model class (lowerPositionLimit, upperPositionLimit ...), though it doesn't feel clean to do that

Is it possible to get a writable expression in these? Currently the visitor in joint-visitor.hpp returns only a readable value.

Thanks,
Rohan

**Comment by jcarpent** [comment]
You can access to this quantities in data via lowerPositionLimit and upperPositionLimit. They are both in read and write mode.

**Comment by proyan** [comment]
Thanks. I was mainly worried that changing limits might require some other changes as well.

**Comment by jcarpent** [comment]
Your welcome. I will close the issue.
