### ISSUE TITLE
Including external force in aba in Python interface

### ISSUE THREAD

**Issue by backtodecember** [stack-of-tasks/pinocchio#1138]
Hi,

I am trying to use the aba(model, data,q,v,tau,extf) function in the Python interface. I see that #632 has asked a similar question, but it seems that some changes have been made since then, I still do not understand exactly how to use the external force. What exactly is extf's format? (Is it a list of arrays of size 6? Is it a list of force-joint ID pairs? ) Any help would be much appreciated!

Best,
Yifan Zhu

**Comment by backtodecember** [comment]
Actually, followed #632 and found the fix. Thanks.

**Comment by jcarpent** [comment]
OK. Nice to hear that it is working for you.
Instead of using StdVec_Force container, which mimics a list in Python, you can directly use a Python list as input argument. The bindings will perform the correct translation then.
