### ISSUE TITLE
dintegrate with the assignment operators ADDTO, SETTO, MULWITH

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/pinocchio#1163]
I'm planning to create a new `dIntegrate` signature that uses the assignmentoperators `ADDTO`(out += res), `SETTO` (out = res), `MULWITH`(out *= res).

The default setting would be SETTO, so it doesn't effect existing code.

@jcarpent What do you think?

**Comment by jcarpent** [comment]
I'm fine, even if in the future, I think this should be made as a class operator and not through a function call.

Please rename `MULWITH`, with `APPLY_ON_THE_LEFT` and for the same price, it might be also useful to add `APPLY_ON_THE_RIGHT`.

**Comment by jcarpent** [comment]
@proyan When do handle this task? Depending on your answer, it might be requested to perform a new release before this one, independendant from the status of this action.

**Comment by proyan** [comment]
Extending to the multiplication operators might take some time and ingenuity. But what I can do is push the ADDTO and RMTO operators today, and then you could make the release. Is that okay?

**Comment by jcarpent** [comment]
Yep. This is fine for me. Thanks a lot ;)

**Comment by jcarpent** [comment]
Partially solved by #1169. The rest will be handled latter if needed.
