### ISSUE TITLE
Check if data is still valid regarding to model

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#117]
Algorithms can crash if a model is modified after creation of data struct. Add a method to check if a data is still valid regarding to model.

**Comment by jcarpent** [comment]
It seems that model as a const ref is not mandatory in the Data struct. The idea is to allow a default constructor with the max number of joints (useful for pre-allocation) or with a model. We also need a method with model as argument to build the data struct.

**Comment by nmansard** [comment]
Solved by #320
