### ISSUE TITLE
Update of reference configurations

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/pinocchio#1178]
At the moment, when appending models with either `buildModel` or `appendModel`, the reference configurations are not updated.

**Comment by jcarpent** [comment]
Can you fix it?

**Comment by jmirabel** [comment]
Is there any other place than the two I mentioned ?

**Comment by jcarpent** [comment]
I don't think so. There are the two I think.

**Comment by jcarpent** [comment]
Small question regarding this issue @jmirabel : how do you want to extend the reference configurations with buildModel and appendModel? Because, some of them might be missing. Do you want to extend them with the neutral configuration?

**Comment by jmirabel** [comment]
I don't see any other choice than using the neutral configuration for the unknown part.

**Comment by jcarpent** [comment]
I do agree.

**Comment by jcarpent** [comment]
@jmirabel Are you still on it?

**Comment by jmirabel** [comment]
I did not encounter the issue again. As this is not blocking anymore, it has become of low priority for me (and I don't think it has a high priority for Pinocchio).

We can mark this as a low priority bug and increase the priority later, if needed.

**Comment by jcarpent** [comment]
@proyan Could you handle this issue in pinocchio-3x?

**Comment by proyan** [comment]
For any configuration "a" in ModelA or ModelB, I see two situations:
1) ModelA and ModelB both have configuration "a"
2) Either ModelA or ModelB (but not both) has configuration "a".

We could take a union of the two configurations, and set the unknown values to zero, which seems to be okay to me. Does that work for you?

**Comment by cmastalli** [comment]
> For any configuration "a" in ModelA or ModelB, I see two situations:
> 
> 1. ModelA and ModelB both have configuration "a"
> 2. Either ModelA or ModelB (but not both) has configuration "a".
> 
> We could take a union of the two configurations, and set the unknown values to zero, which seems to be okay to me. Does that work for you?

It would be ideal if we can append the reference configurations with the same key.

Additionally, the Python interface is not friendly. It would be also ideal to be able to print the keys in Python.
Crocoddyl has a much nicer 'std::map' conversion that could be propagate in Pinocchio.

**Comment by jcarpent** [comment]
> We could take a union of the two configurations, and set the unknown values to zero, which seems to be okay to me. Does that work for you?

I think you should use the neutral configuration for missing data. For the same key, we should append the two configurations I would say.

**Comment by jcarpent** [comment]
> Additionally, the Python interface is not friendly. It would be also ideal to be able to print the keys in Python.
> Crocoddyl has a much nicer 'std::map' conversion that could be propagate in Pinocchio.

A simple trick is to use the conversion to Python's `dict` object and get the related keys.

**Comment by cmastalli** [comment]
> > Additionally, the Python interface is not friendly. It would be also ideal to be able to print the keys in Python.
> > Crocoddyl has a much nicer 'std::map' conversion that could be propagate in Pinocchio.
> 
> A simple trick is to use the conversion to Python's `dict` object and get the related keys.

This is indeed how it is implemented in Crocoddyl. But, at least in Pinocchio 2 is not the same.
This code doesn't work:
```bash
In [7]: anymal.model.referenceConfigurations.todict()
----> 1 anymal.model.referenceConfigurations.todict()

AttributeError: 'StdMap_String_VectorXd' object has no attribute 'todict'
```

**Comment by cmastalli** [comment]
I would go even further. I would suggest to have a print option, as it is nicely done in the Pinocchio model object.

**Comment by proyan** [comment]
```python
dict(anymal.model.referenceConfigurations)
```
is the syntax that works here
