### ISSUE TITLE
Check jointDense for all the joints

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#119]

**Comment by fvalenza** [comment]
Do we still need jointDense with the new JointAccessor ?

**Comment by nmansard** [comment]
Yes indeed. This has a different purpose (enabling virtual inheritance 
for object-oriented developers).

**Comment by jcarpent** [comment]
An other question is: do we need jointDense converter for all joint types ? 
I do not think so as it is just a copy of the sparse quantity to their dense counterpart, while joint accessor does the same job but avoiding copy.

**Comment by nmansard** [comment]
I agree with that: we do not need conversion any more.
However, would you also agree that now, automatic conversion should be 
possible (from JointVariant to JointDense)?

**Comment by jcarpent** [comment]
With the new JointAccessor, it is now possible to get the conversion of the sparse spatial quantities to their dense representation.

**Comment by jcarpent** [comment]
No need this feature in the very near future. Consider this Issue as solved.
