### ISSUE TITLE
addFrame should return FrameIndex

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/pinocchio#1199]
Currently, `addFrame` returns and `int`.
There is really no reason for this to happen, since as far as I can tell the return values are never negative.

This is not only unintuitive, but it also forces explicit casts if you want to use it where a `FrameIndex` is expected.

I believe the return type should be `FrameIndex`. Changing this now should not create serious problems to users. However, it may cause some warnings, which might break compilation if one compiles with `Werror`. These warnings would be easily fixed.

What do you think? Should it be fixed, and, if yes, should it be fixed now or in Pinocchio 3?

**Comment by jmirabel** [comment]
For me, it is fine to fix this now.

**Comment by jcarpent** [comment]
This is fine for me too. You can propose a new PR. Thanks @gabrielebndn.

**Comment by jcarpent** [comment]
Solved by #1209
