### ISSUE TITLE
Export tags in github

### ISSUE THREAD

**Issue by flforget** [stack-of-tasks/pinocchio#12]
Dear Florian,
It seems that you did not push the tags in github.
When I do 
```
git tag
```
nothing appear in the fresh clone I pulled on my computer.
Could you fix the matter please ?
The drawback of this situation lies in the fact that the generated pinocchio.pc does
not include the version number and has UNKNOWN.
This is a bit problematic to test the version from another package.
Thanks a lot in advance for your help.

Best Regards,
Florent.

**Comment by fvalenza** [comment]
As this issue seems to be corrected for the v1.0.0. I close it.

Nota: Next time, i'll double check the use of "make release" from jrl-cmake correctly
