### ISSUE TITLE
Is there a reason to have both `lambda_c` and `impulse_c`?

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/pinocchio#1211]
The title is quite expressive. Note that I refer to Pinocchio data.

**Comment by jcarpent** [comment]
Yes: impulse (contact impulses) is for impact dynamics and lambda (contact forces) if for contact dynamics. But in future, they won't be useful anymore.

**Comment by cmastalli** [comment]
> Yes: impulse (contact impulses) is for impact dynamics and lambda (contact forces) if for contact dynamics. But in future, they won't be useful anymore

I know that, I was thinking that we could use one to store both results (for contact and impulse dynamics). However, this question is not important if they won't be useful in future.

**Comment by gabrielebndn** [comment]
> In future, they won't be useful anymore.

Small note: even though they might not be necessary as an intermediate result to compute the joint acceleration and delta velocity, I suggest to keep these fields and retain a way of computing them. Somebody may need them per se
