### ISSUE TITLE
Does computeRNEADerivatives run internally computeForwardKinematicsDerivatives?

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/pinocchio#1212]
I have a little confusion, I didn't manage to answer this question by reading the paper / code.

**Comment by jcarpent** [comment]
There is no explicit call, but it does the computations. This is written in the paper.

**Comment by cmastalli** [comment]
> There is no explicit call, but it does the computations. This is written in the paper.

Thank you so for a prompt response. So could I call getJointVelocityDerivatives after running only computeRNEADerivatives?

**Comment by jcarpent** [comment]
Yes. This is explained in the doc of the function.
