### ISSUE TITLE
Partial derivative with respect to q in forward dynamics

### ISSUE THREAD

**Issue by mzwang828** [stack-of-tasks/pinocchio#1217]
Hi,

I have a question regarding partial derivatives with respect to q for a special case, in which my f_ext term is sensitive to the model configuration. Referring to Eq. 16(a) in this [paper](https://hal.laas.fr/hal-01790971/document), the f_ext term is not a function of input variables (q, q_dot or tau). However, for our cases, the f_ext is a function of q and thus the ddq_dq output from `computeABAderivatives() [4/4]` differs from what we expected.

To be specific, I'm trying to solve the trajectory for pushing an object without specifying the point of contact. From FCL, I got the nearest points between the manipulator and the object and I assume those nearest points to be the contact position. I then express the contact force in the local frame of the joint and get the `f_ext`. This `f_ext` now becomes a function of `q` because of the contact position changes for different configurations. Here is the code for getting the `f_ext` acting on the object for reference:

I first get the nearest points between manipulator and the object using FCl:
```
computeCollisions(model, data, geom_model, geom_data, q);
computeDistances(model, data_next, geom_model, geom_data, q);
hpp::fcl::DistanceResult dr = geom_data.distanceResults[cp_index];
```

I then get the vector pointing from the object's root joint to the contact point in order to transform the force:
```
computeJointJacobians(model, data, q);
framesForwardKinematics(model, data, q);
pinocchio::SE3 root_joint_frame_placement = data.oMf[model.getFrameId("object_root_joint")];
Eigen::Vector3d object_r_j2c = root_joint_frame_placement.inverse().act(dr.nearest_points[1]);
```

Transform the contact force from the contact point to the root joint position to get f_ext. The contact force is assumed to be normal to the surface of the object at the contact point:
```
Eigen::VectorXd fext_object(6);
force_ocp = front_normal * exforce(i);
fext_object.head(3) = force_ocp;
fext_object(3) = -object_r_j2c(2) * force_ocp(1) + object_r_j2c(1) * force_ocp(2);
fext_object(4) = object_r_j2c(2) * force_ocp(0) - object_r_j2c(0) * force_ocp(2);
fext_object(5) = -object_r_j2c(1) * force_ocp(0) + object_r_j2c(0) * force_ocp(1);
fext_object_ref = fext_object;
PINOCCHIO_ALIGNED_STD_VECTOR(pinocchio::Force) fext_plus((size_t)model.njoints, pinocchio::Force::Zero());
fext_plus[object_joint_id] = pinocchio::ForceRef<pinocchio::Force::Vector6>(fext_object_ref);
```
As you can see in the code, I used the distanceresult ( which is a function of q ) to get the `f_ext` that acts on the object. My question is using Pinocchio, is it possible for us to get a ddq_dq, with such a f_ext(q), that also reflects the sensitivity of f_ext to the model's configuration? Any suggestions will be greatly appreciated! 

Thank you!

**Comment by jcarpent** [comment]
Could you send me a private email? I will forward you the technical details of this question.
