### ISSUE TITLE
update of pinocchio package

### ISSUE THREAD

**Issue by mfocchi** [stack-of-tasks/pinocchio#1237]
Hi 

I updated my pinocchio library (version 2.4.3) to the last one (version 2.4.5)
by running 
`sudo apt-get install robotpkg-py27-pinocchio`

for some reason this didn't install also **robotpkg-pinocchio** that seems 
to update the libraries and the sym links in /opt/openrobots/lib
therefore, when you try to import pinocchio got stuck because libpinocchio_pywrap it cannot find the right version of pinocchio cause libpinocchio.so  still points to libpinocchio.so.2.4.3

**Comment by jcarpent** [comment]
Hi @mfocchi,

On which version of Linux are you working on now?
In the meantime, you can maybe force the installation of pinocchio on the 2.4.5 version via:
```
sudo apt install robotpkg-pinocchio=2.4.5
```
@nim65s Do you know what happens here?
Best,

Justin

**Comment by nim65s** [comment]
@mfocchi : you can fix this with a `sudo apt upgrade`.
But yes, there is an issue in the packaging:
```bash
╰─>$ apt depends robotpkg-py27-pinocchio
[…]
 |Dépend: robotpkg-pinocchio (= 2.4.4)
 |Dépend: robotpkg-pinocchio (= 2.4.3)
 |Dépend: robotpkg-pinocchio (= 2.3.1)
  Dépend: robotpkg-pinocchio (= 2.4.5)
```

I'll fix this.

**Comment by mfocchi** [comment]
> Hi @mfocchi,
> 
> On which version of Linux are you working on now?
> In the meantime, you can maybe force the installation of pinocchio on the 2.4.5 version via:
> 
> ```
> sudo apt install robotpkg-pinocchio=2.4.5
> ```
> 
> @nim65s Do you know what happens here?
> Best,
> 
> Justin

I am on ubuntu 16.04, and that is what I did to force it without any luck. I am glad the issue was sorted out!

best,
Michele

**Comment by jcarpent** [comment]
Seems to be solved now. Thanks @mfocchi for raising this issue and to @nim65s for the fix.
