### ISSUE TITLE
C++ visualization

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/pinocchio#1239]
This is just an announce that may interest people using Pinocchio in C++.

I created https://github.com/jmirabel/pinocchio-gepetto-viewer/ that enables visualization of pinocchio Model in gepetto-viewer directly in C++.

At the moment, it depends on the devel branch of gepetto-viewer (not released yet).

**Comment by jcarpent** [comment]
Maybe, you can refer to it in the documentation and in the Readme, by adding a list of the supported viewer.

**Comment by cmastalli** [comment]
It would be great (for public visibility) if you, at some point, transferred the repository to `stack-of-tasks` organization.

**Comment by cmastalli** [comment]
Btw, I know I asked this before, but I would like to make again the same question. Is there an improvement in computation performance?

**Comment by jmirabel** [comment]
> Btw, I know I asked this before, but I would like to make again the same question. Is there an improvement in computation performance?

This wasn't my target. There are places where the code could be optimized.
If that worries you, we can put the viewer::display code in a separate thread.

**Comment by jcarpent** [comment]
This information now appears on the Readme.md.

**Comment by jmirabel** [comment]
Thank you for taking care of this. While reading through the README, I bumped into the lines

> NEWS: We are hiring! We are looking for a talented C++/Python software developer to enhance and promote Pinocchio inside the robotics community and beyond. Please contact @jcarpent for further details.

Next time this file is updated, we may put a date on this so that people know it is recent.

**Comment by jmirabel** [comment]
A follow-up: https://github.com/stack-of-tasks/pinocchio-gepetto-viewer/pull/2
