### ISSUE TITLE
Template instantiation

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/pinocchio#1245]
I gave a quick trial to template instantiation for C++ >= 11: dbffed2

With this commit, compiling file `lib.cc`:
```cpp
#include <pinocchio/algorithm/kinematics.hpp>

using namespace pinocchio;

Eigen::MatrixXd foo()
{
  Model model;
  Data data(model);
  Eigen::MatrixXd q;
}
```
with the `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.10)

project(test LANGUAGES CXX)

find_package(pinocchio REQUIRED)

add_library(lib_linked SHARED lib.cc)
target_link_libraries(lib_linked pinocchio::pinocchio)

add_library(lib_not_linked SHARED lib.cc)
target_link_libraries(lib_not_linked pinocchio::pinocchio)
target_compile_definitions(lib_not_linked PRIVATE "-DPINOCCHIO_ENABLE_TEMPLATE_INSTANTIATION=0")
```

Then, `time make lib_linked` (using template instantiation) gives:
> real	0m6,208s
user	0m5,707s
sys	0m0,482s

and `time make lib_not_linked` (using template instantiation) gives:
> real	0m8,290s
user	0m7,591s
sys	0m0,570s

The benefits in terms of compilation time is obvious.

**Comment by jcarpent** [comment]
This is duplicated with respect to #571. I will move the issue content to the correct thread.
