### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by andreadelprete** [stack-of-tasks/pinocchio#1269]
All the links to the code are broken in this page of the documentation:
https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/md_doc_d-practical-exercises_7-learn.html

I've seen that the code is available [here](https://github.com/stack-of-tasks/pinocchio/tree/master/doc/d-practical-exercises/src), but anyway it'd be nice to fix these links.

**Comment by jmirabel** [comment]
Since here, we can change *Learning to flight* to *Learn to fly* (*Learn* for consistency with the other practical exercises.

**Comment by nim65s** [comment]
Those tutorials are currently not maintained, and they will be remplaced by a more recent version from Nicolas, as soon as I can spend some time to review and adapt them.

**Comment by jcarpent** [comment]
Thanks @andreadelprete for raising this issue. I've updated doxygen to prevent it.
You can pull it and makde doc in your build directory to get the lattest version of the doc.

**Comment by andreadelprete** [comment]
Ok, thanks! Feel free to close the issue if you want.

**Comment by jcarpent** [comment]
Solved by #1270

**Comment by nim65s** [comment]
Fixed here: https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/devel/doxygen-html/md_doc_d-practical-exercises_7-learn.html
