### ISSUE TITLE
Can't install robotpkg-py37-pinocchio on ubuntu 18

### ISSUE THREAD

**Issue by JoeMWatson** [stack-of-tasks/pinocchio#1275]
The build appears to be broken: http://robotpkg.openrobots.org/rbulk/robotpkg/math/py-pinocchio/index.html

**Comment by jcarpent** [comment]
It is Python 3.6 the offician Python 3 on 18.04. You should then install:
robotpkg-py36-pinocchio

If you want an extended support of Python, please use conda insteal.

**Comment by jcarpent** [comment]
This issue seems to be solved. Feel free to reopen it @JoeMWatson.
