### ISSUE TITLE
About inverse rotation function

### ISSUE THREAD

**Issue by ddliu365** [stack-of-tasks/pinocchio#1277]
Is it possible to implement the following the `inverse rotate` function?
```
m = rotate('x', pi / 3).dot(rotate('y', pi / 5)).dot(rotate('z', pi / 7))
pi/3, pi/5, pi/7 = inverseRotate(m)
```

**Comment by jmirabel** [comment]
Check the rpy namespace (pinocchio.rpy of pinocchio::rpy).

**Comment by jcarpent** [comment]
You can also use the Eigen functions for that. It is a direct binding of Eigen Geometry module in Python. 
See AngleAxis for that.

**Comment by jcarpent** [comment]
There is also:
```python
import eigenpy
eigenpy.toEulerAngles(R)
```
with following doc:
```python
Docstring:
toEulerAngles( (object)mat (dim 3x3), (int)a0, (int)a1, (int)a2) -> object :
    It returns the Euler-angles of the rotation matrix mat using the convention defined by the triplet (a0,a1,a2).
```

**Comment by ddliu365** [comment]
Thanks @jcarpent @jmirabel  It works well now. The rotation order matters for `rpy`.
