### ISSUE TITLE
macro PINOCCHIO_CHECK_INPUT_ARGUMENT

### ISSUE THREAD

**Issue by florent-lamiraux** [stack-of-tasks/pinocchio#1280]
is used at many places to check the size of input configurations or velocity vectors. When the test fails, the expected size and
the actual size are not displayed. This would be very helpful to get this information in the exception message.

One way would be to define another macros named
```
PINOCCHIO_CHECK_ARGUMENT_SIZE(size1, size2)\
  std::ostringstream oss;\
  if (s1 != s2) {\
    oss << "wrong argument size: expected " << size2 << ", got " << size1 << ".";\
    PINOCCHIO_THROW(true, oss.str());\
  }

**Comment by jcarpent** [comment]
Solved by #1281.
