### ISSUE TITLE
Are joint friction parameters from URDF loaded to the robot model?

### ISSUE THREAD

**Issue by rshum19** [stack-of-tasks/pinocchio#1291]
Hi I have a similar question to #1147.  I'm trying to simulate a 7DOF robot arm and want to include joint friction and damping. In the URDF one can define the tag 
```
<joint>
    <dynamics damping="1.0" friction="1.0">
</joint>
```

I'm wondering if these parameters are used at all when loading the model? 

If this is not the case, then would the best way to include joint friction be by adding a joint friction model to the joint torque vector (tau) before computing the forward the dynamics like shown below?
``` 
tau = friction_model(q,v);
ddq = pinocchio::aba(model, data, q, v, tau);
```

thanks,

**Comment by jcarpent** [comment]
For the damping term, which affects the torque proportionally to the joint angular velocity, your trick does the job.
For handling the friction, it is a bit harder, as you have to solve a linear complementary problem: 
`tau < friction is orthogonal to ddq > 0`

**Comment by jcarpent** [comment]
What we may add, is the automatic loading of these parameters in the Model when parsing the URDF file.

**Comment by rshum19** [comment]
thank you for the fast response! 

I see, so adding damping can be easily done but friction requires more effort. I will look more into friction model and adding friction. Your response clarifies my question about what gets parsed from the URDF, so I will close this issue.

**Comment by gfadini** [comment]
Hi, I see that this issue has been closed, nonetheless I think that having those parameters parsed from the URDF automatically may be useful for some applications.
In my specif case I can use the coulomb friction and viscous damping by defining them though crocoddyl, but I guess that since they actually are physical parameters of the system they may be loaded in the model itself. What do you think about this, would this be relevant to other people as well?

**Comment by jcarpent** [comment]
Yes, this was my remark.
The new version of Pinocchio 3.x should include them. But, even with these values, the features of Crocoddyl will not allow you to handle correctly the friction, only the damping.

**Comment by gfadini** [comment]
Thanks for the answer @jcarpent , that would be a nice addition to the next version of pinocchio. I agree with you that including the static friction properly in crocoddyl won't be straightforward

**Comment by cmastalli** [comment]
@jcarpent we could boost the integration is you provide a roadmap with a rough description of the API.

**Comment by jcarpent** [comment]
I'm lacking of time for that. Sorry.

**Comment by cmastalli** [comment]
> I'm lacking of time for that. Sorry.

No problem at all, thanks :)

**Comment by Kongx231** [comment]
I see that damping shows up in the model parameter in Pinocchio3, but doesn't seem to be applying damping forces when applying forward dynamics. That's okay if its still not supported, I can use the solution from above. I just wanted to double check.

**Comment by jcarpent** [comment]
Not yet, this will be present in the final version ...
Sorry for the delay.
