### ISSUE TITLE
compute center of mass acceleration

### ISSUE THREAD

**Issue by WangKeAlchemist** [stack-of-tasks/pinocchio#1294]
Hi,

I want to use Pinocchio to compute center of mass acceleration in world frame, so I use `pin::forwardKinematics(model,data,q); acc_x = data.acom[0][0];` in C++, for each iteration. However later I realize that the acceleration I get is always 0, have I done anything wrong?

Thanks!

**Comment by jcarpent** [comment]
No, you should just call the function to compute it, which is `centerOfMass(model,data,q,v,a)`

**Comment by jcarpent** [comment]
By the way, `centerOfMass` is already calling `forwardKinematics`

**Comment by jcarpent** [comment]
If you want to compute the CoM from the current values of the kinematics stored in Data, you should just call:
`centerOfMass(model,data,2)` where `2`means ACCELERATION level (1 means VELOCITY and 0 means POSITION).

**Comment by olivier-stasse** [comment]
> If you want to compute the CoM from the current values of the kinematics stored in Data, you should just call:
> `centerOfMass(model,data,2)` where `2`means ACCELERATION level (1 means VELOCITY and 0 means POSITION).

Maybe an enum would be more informative ?

**Comment by jcarpent** [comment]
Yes, I do agree. This is what I realized after writing this answer.

**Comment by WangKeAlchemist** [comment]
Hi @jcarpent @olivier-stasse, your answer is very helpful and I just tried that. What I find is: if I use `centerOfMass(model,data,q,v)` only, then the resultant center of mass acceleration is still 0. That is probably because I don't provide joint acceleration (I cannot get joint acceleration directly from my simulation and can only get it by numerical differentiation). But when I use `centerOfMass(model,data,2)` and it does work! 
Just out of curiosity,  does `centerOfMass(model,data,2)`  use numerical differentiation to compute CoM acceleration given joint acceleration is not provided?

**Comment by jcarpent** [comment]
You have forgotten an argument: centerOfMass(model,data,q,v,**a**)

**Comment by WangKeAlchemist** [comment]
> You have forgotten an argument: centerOfMass(model,data,q,v,**a**)

Right, after adding **a** it works well, thanks!
