### ISSUE TITLE
Derivative of center of mass Jacobian

### ISSUE THREAD

**Issue by jakewelde** [stack-of-tasks/pinocchio#1297]
Hi, I am wondering if you could help direct me to the best way to use Pinocchio to compute the time derivative of the center of mass jacobian, i.e. for center of mass x, since x' = J v, then x'' = J v' + J' v and I want to compute J' (I am already computing the rest using jacobianCenterOfMass). Is there an analytical implementation I haven't been able to find, or could you offer a tip for where to look in the documentation to compute this via autodiff? Many thanks for your excellent library and helpful support.

**Comment by jcarpent** [comment]
`computeCentroidalMapTimeVariation` will compute `dAg/dt`, the time variation of the centroidal momemtum matrix. The 3 first rows do match the center of mass Jacobian time variation.
If you need a dedicated algorithm for computing this quantity, I may implement it.

**Comment by jakewelde** [comment]
I think the existing functionality fully satisfies my needs! thank you again.

**Comment by junhyeokahn** [comment]
@jakewelde @jcarpent Don't you need to divide ```dAg/dt``` by the ```total_mass``` of the robot to achieve a com jacobian dot?

**Comment by jakewelde** [comment]
Agreed, this is also a required detail

**Comment by jcarpent** [comment]
> @jakewelde @jcarpent Don't you need to divide `dAg/dt` by the `total_mass` of the robot to achieve a com jacobian dot?

Yes, you are correct.

**Comment by junhyeokahn** [comment]
@jcarpent @jakewelde  Thanks for verification!
