### ISSUE TITLE
Parse more info from SRDF

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#130]
There are more information available in SRDF that are required by HPP and SoT:

- end effectors info
- default configuration

**Comment by jmirabel** [comment]
Class `HumanoidRobot` members pointing to special joints are initialized by the two following functions, when reading URDF file (and NOT SRDF, as I mentioned earlier):
- https://github.com/humanoid-path-planner/hpp-model-urdf/blob/devel/src/urdf/parser.cc#L318
- https://github.com/humanoid-path-planner/hpp-model-urdf/blob/devel/src/urdf/parser.cc#L301

**Comment by nmansard** [comment]
Solved
