### ISSUE TITLE
Kinematic energy and potential energy

### ISSUE THREAD

**Issue by ddliu365** [stack-of-tasks/pinocchio#1302]
Hi, 

I am wondering if there is a function in `pinocchio` which can calculate potential energy and kinematic energy for each part and sum them in total?

**Comment by jcarpent** [comment]
Yes, of course. Have you taken a look into the documentation? There are functions called potentialEnergy and kineticEnergy that do the job.

**Comment by jcarpent** [comment]
Hope the answer is precise enough. I will close the issue then.
