### ISSUE TITLE
Create a JointGeneric accessor

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#131]
Create a struct containing a joint variant and expose joint visitor.

**Comment by nmansard** [comment]
JointAccessor is done, using a JointVariant has input of the construction.

I would be nice to have JointAccessor and JointVariant as a unique class, by inheriting JointVariant both from boost::variant and from JointModel.

@fvalenza will check that this second solution is feasible.

**Comment by jcarpent** [comment]
Solved by #182.
