### ISSUE TITLE
lower triangle of "data.M" for "pinocchio::getKKTContactDynamicMatrixInverse()"

### ISSUE THREAD

**Issue by hammoudbilal** [stack-of-tasks/pinocchio#1312]
Hi, 

if calling `pinocchio::getKKTContactDynamicMatrixInverse()` right after `pinocchio::forwardDynamics()` do i need to modify the mass matrix to include the lower triangular part ? 
I can see that you do this in the unit test [here](https://github.com/stack-of-tasks/pinocchio/blob/380fdefb172efa07f2dd9112ce2d389e25aa7a41/unittest/contact-dynamics.cpp#L122) but I am not sure if it is needed for `pinocchio::getKKTContactDynamicMatrixInverse()`

**Comment by jcarpent** [comment]
No. This one is directly filled symmetrically.
