### ISSUE TITLE
Jacobian structure clarification

### ISSUE THREAD

**Issue by rshum19** [stack-of-tasks/pinocchio#1313]
Hi,

I'm somewhat unclear on the structure of the Jacobian matrix obtained from 
```
pinocchio::getFrameJacobian()
```
For the 6-D Jacobian `J(q)` I'm not sure if the first 3 rows correspond to the position or velocity. If I multiply `J(q)*dq` does the resulting 6-D vector have the linear velocity in the first 3 entries and the angular velocity in the last 3 entries or the other way around?

Thank you!

**Comment by jcarpent** [comment]
The first three rows mactches the linear velocity. The three next correspond to the angular one.
In case you have some doubts, just remind that the spatial velocity `v = J(q)*dq/dt`, and then the former sentence makes sense and is helpful to retrive the correct meaning.
