### ISSUE TITLE
Display issues in wheels

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/pinocchio#1318]
Hi again,

To check #1317, I created a docker that install everything from pip, and then try to run [a jupyter notebook with talos saying hi](https://github.com/MeMory-of-MOtion/summer-school/blob/master/setup/load_talos.ipynb).

This is failing both with GepettoViewer and MeshcatViewer. If I have a `pinocchio.pinocchio_pywrap.GeometryObject` and try to access its `geometry` attribute, as it is done [here](https://github.com/stack-of-tasks/pinocchio/blob/17c479e2fe91905122713643f489feb8ddf135a3/bindings/python/pinocchio/visualize/meshcat_visualizer.py#L103), I get:
```
No to_python (by-value) converter found for C++ type: boost::shared_ptr<pinocchio::fcl::FakeCollisionGeometry>
```

To reproduce this (with meshcat):
```
docker run --rm -p 8888:8888 -p 7000:7000 -it gepetto/utils:wheel-3.9
```

**Comment by jcarpent** [comment]
This is not loading hppfcl Python bindings in fact.

**Comment by jcarpent** [comment]
Is the problem fixed?

**Comment by nim65s** [comment]
Not yet, I'm spending too much time on the robot, sorry

**Comment by jcarpent** [comment]
The problem here is that the current project is not compiled with HPP-FCL dependency.
