### ISSUE TITLE
undefined id, idx_q and idx_v of the root joint

### ISSUE THREAD

**Issue by khanhha** [stack-of-tasks/pinocchio#1337]
hi, 
I would like to ask why the fields id, idx_q and idx_v of the root joint of the model, loaded in python are undefined? I would like to use these index fields, but their values are negative.
![image](https://user-images.githubusercontent.com/2276264/98437592-af8f4800-20e3-11eb-9717-4fa7633ff7f4.png)
Thanks

**Comment by jcarpent** [comment]
The root joint as first joint of the kinematic tree starts at index 0.

**Comment by khanhha** [comment]
Thanks. I suppose that this is a bug right?

**Comment by jcarpent** [comment]
No. This is just non initialized values.

**Comment by jcarpent** [comment]
I made a mistake in my first answer. I’ve corrected it.

**Comment by khanhha** [comment]
but what does this joint mean/store? The joint after it in the list model.joints also have id==1

**Comment by jcarpent** [comment]
Index 0 refers to the world. So for instance, data.oMi[0] refers to placement of the world with respect to itself, so should be equal to Identity.
In the same vein, model.joints[0] refers to the joint that links the world to itself. In another word, this is a fixed joint which is not considered in Pinocchio.

**Comment by khanhha** [comment]
@jcarpent: I got it. Thank you for your clear explanation. 
Best
