### ISSUE TITLE
python3 installation issue

### ISSUE THREAD

**Issue by cjsend56** [stack-of-tasks/pinocchio#1349]
I tried: brew install pinocchio-python3 
but it gave me error saying that "No formulae found in taps"

**Comment by jcarpent** [comment]
brew does not support Python 2.7 anymore for almost a year now. You should just type:
`brew install pinocchio`
Where did you find the pinocchio-python3?

**Comment by cjsend56** [comment]
Okay, I thought something went wrong when I installed it.
I did "pinocchio-python3" because I remembered doing that a long time ago, so I thought that I needed to do the same. 
Thanks!
