### ISSUE TITLE
ROS_PACKAGE_PATH does not exist in ros2

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/pinocchio#1358]
https://github.com/stack-of-tasks/pinocchio/blob/f665f3f93669860beb8e80388ed3b52043ddd868/src/utils/file-explorer.hpp#L58 reads ROS_PACKAGE_PATH which does not exist in ros2.

Instead the line could read AMENT_PREFIX_PATH for ros2.

A strategy could be to test if one or the other variable exists.

**Comment by jcarpent** [comment]
Solved by #1359.
