### ISSUE TITLE
How to use Pinocchio to calculate G in this kinetic formula?

### ISSUE THREAD

**Issue by wjingdan** [stack-of-tasks/pinocchio#1360]
Hello, I want to know how to use Pinocchio to calculate G in this kinetic formula? Thank you so much.

![2020-12-15 21-11-58屏幕截图](https://user-images.githubusercontent.com/38741361/102219276-37a21200-3f1a-11eb-8fdf-fe85dbe342ec.png)

**Comment by jcarpent** [comment]
What is the G matrix? It is related to some contact constraints? Could you send a reference to understand its meaning?

**Comment by wjingdan** [comment]
[physcap-1.pdf](https://github.com/stack-of-tasks/pinocchio/files/5699796/physcap-1.pdf)

Hello. In the above paper, G is defined as such.

![11608083286_ pic_hd](https://user-images.githubusercontent.com/38741361/102294251-d9117e00-3f83-11eb-8102-b30ad3e2448c.jpg)

**Comment by jcarpent** [comment]
OK. This quantity corresponds to the action of the contact transformation (placement quantity of the contact point w.r.t. to the supporting joint) on the contact forces. It is nothing more than:
```python
M = pin.SE3.Random() # placement of the contact point w.r.t. the joint frame
f = pin.Force(fext,np.zeros((3))) # value of the contact force expressed as a spatial Force quantity
f_joint = M.act(f)
```

**Comment by jcarpent** [comment]
By the way, I don't think the phrasing of your reference paper is correct. There is a lot of ambiguities in the notation and the naming. If you need a correct reference, Featherstone is the correct book.

**Comment by wjingdan** [comment]
Thank you for your answers. 
In the sample code: contact-dynamics.cpp, after this step (**pinocchio::forwardDynamics(model, data, q, v, tau, J, gamma, 0.);**), you directly call data.lambda_c like this (**Eigen ::VectorXd dynamics_residual (data.M * data.ddq + data.nle-tau-J.transpose()*data.lambda_c);**), so data.lambda_c is the contact force and moment of "rleg6_joint" and "lleg6_joint" ( dim=6)?
![图片](https://user-images.githubusercontent.com/38741361/102326676-a7b6a380-3fbf-11eb-8e23-645a62f1f482.png)

**Comment by jcarpent** [comment]
Yes, exactly. But this is for rigid contact model.

**Comment by wjingdan** [comment]
Thank you very much.

**Comment by jcarpent** [comment]
Fine. I will close this issue then.

**Comment by BERSERKPH52** [comment]
> OK. This quantity corresponds to the action of the contact transformation (placement quantity of the contact point w.r.t. to the supporting joint) on the contact forces. It is nothing more than:
> 
> ```python
> M = pin.SE3.Random() # placement of the contact point w.r.t. the joint frame
> f = pin.Force(fext,np.zeros((3))) # value of the contact force expressed as a spatial Force quantity
> f_joint = M.act(f)
> ```
Hi, jcarpent.
I'm a beginner of Pinocchio and I also encountered the same problem when calculating G.
After reading your reply, I still have a question about how **f_joint** can know which joint frame it should be with respect to, because I didn't see any input about joint information.  
I‘d appreciate it if you can answer.

**Comment by jcarpent** [comment]
G is nothing more than the transformation that maps the contact point locomation to the joint local frame.
If you know the placement M_i of the contact point i, then you need to simply call `M_i.toDualActionMatrix().leftCols<3>()`.

**Comment by jcarpent** [comment]
By the way, a more complete approach for solving similar problems has been done by @zongmianli: https://www.di.ens.fr/willow/research/motionforcesfromvideo/research/li19mfv/

The whole implementation based on Pinocchio will be made open source very soon.

**Comment by BERSERKPH52** [comment]
Thank you very much for your patience to explain and share, I will follow zongmianli‘s work in the future.

**Comment by luyangzhu** [comment]
Hi Justin, any rough timeline for releasing the implementation for zongmian's paper? I am also new to pinocchio, want to find some tutorials of pinocchio on the inverse dynamics control with contact constraints? (e.g., a tutorial on how to control humanoid robot to track a reference walking motion considering the foot contacts)
