### ISSUE TITLE
Restitution value for different contacts in impulse dynamics

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/pinocchio#1369]
It would be useful to be able to define different restitution values (1 per contacts) in the impulse dynamics.

I understand that this is not trivial in terms of API, however, the simplest idea that I have is to use a tuple instead of a double. This tuple will define the restitution value, index for the initial and terminal constraints.

**Comment by jcarpent** [comment]
This feature is already in the pipe for Pinocchio 3.x
