### ISSUE TITLE
GeometryData::CollisionObjects is deprecated

### ISSUE THREAD

**Issue by florent-lamiraux** [stack-of-tasks/pinocchio#1373]
https://github.com/stack-of-tasks/pinocchio/blob/9389400a6018e97ec3822796d465a4b801630a1f/src/multibody/geometry.hpp#L198.

What should we use instead ?

**Comment by jcarpent** [comment]
As mentioned by:
https://github.com/stack-of-tasks/pinocchio/blob/9389400a6018e97ec3822796d465a4b801630a1f/src/multibody/geometry.hpp#L192-L197

the fcl object is contained in a GeometryObject under the field name `geometry`.

**Comment by florent-lamiraux** [comment]
Excuse me, but it is not obvious to me how to retrieve an `fcl::CollisionObject` instance from `geomModel.geometryObjects`.
Does the transformation `GeometryModel::geometryObjects[i].placement` correspond to `GeometryData::collisionObjects[i]::t`?

**Comment by jcarpent** [comment]
the `geomModel.geometryObjects.placement` is relative to the supporting joint Frame.
you can retrieve the geometry placement wrt the world in the field: `Data.oMg[geom_id]`.

Is it answering your question?

**Comment by jmirabel** [comment]
@florent-lamiraux I have a commit the removes all the deprecated use of this class member in HPP.

**Comment by florent-lamiraux** [comment]
Thank you @jmirabel and @jcarpent.
