### ISSUE TITLE
Fail to Run Meshcat Example

### ISSUE THREAD

**Issue by junhyeokahn** [stack-of-tasks/pinocchio#1375]
Hello,
Thanks for maintaining this nice repo.
I just installed the package using conda, and trying to run some examples.
Especially, I am running two examples ```meshcat-viewer-dae.py``` and ```python meshcat-viewer.py```, but getting the warning below and the empty scene on the web. 
```
/opt/anaconda3/lib/python3.8/runpy.py:127: RuntimeWarning: 'meshcat.servers.zmqserver' found in sys.modules after import of package 'meshcat.servers', but prior to execution of 'meshcat.servers.zmqserver'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
You can open the visualizer by visiting the following URL:
http://127.0.0.1:7000/static/
```
Am I missing any procedure to run the example?

**Comment by jcarpent** [comment]
How did you install meshcat?

**Comment by junhyeokahn** [comment]
Yes I installed it by following ```pip install meschat```.

**Comment by jcarpent** [comment]
You need to run it in an interactive manner, with:
```
python meshcat-viewer.py
```

**Comment by junhyeokahn** [comment]
It works!
I really appreciate your help.
