### ISSUE TITLE
Retreive joint configuration vector from pinocchio::Data

### ISSUE THREAD

**Issue by nuft** [stack-of-tasks/pinocchio#1379]
Hi,

Is there an inexpensive way to retrieve the pinocchio joint configuration vector q from pinocchio::Data?

Cheers,
Michael

**Comment by jcarpent** [comment]
At the time being, no. What would be your use case?

**Comment by nuft** [comment]
We're using 2 implementations of some algorithms, CppAD + codegen vs. analytical.
While the two approaches come with different design patterns, we're trying to keep the APIs identical.
In this particular case it would have been convenient to only use pinocchio::Data, but it's not really an issue for us.

**Comment by jcarpent** [comment]
Indeed, you can always inherit from these data and store what you need.
