### ISSUE TITLE
Redundant frame placement update in getFrameJacobian()

### ISSUE THREAD

**Issue by nuft** [stack-of-tasks/pinocchio#1384]
The method `pinocchio::getFrameJacobian()` updates the frame placement even though the documentation tells to call `pinocchio::framesForwardKinematics()` beforehand. I believe this frame placement update is unnecessary and can be removed. It would also allow taking data as a const reference, which would be more consistent with the computeX() and getX() pattern.

The same could be done `pinocchio::getFrameJacobianTimeVariation()`.

What do you think?

**Comment by jcarpent** [comment]
You're totally right. This is already accounted in Pinocchio 3x we hope to be able to release soon.

**Comment by nuft** [comment]
Glad to hear that it's already being addressed. Looking forward to Pinocchio 3x
