### ISSUE TITLE
Conversions between XYZQuat and SE3 in C++

### ISSUE THREAD

**Issue by MaximilienNaveau** [stack-of-tasks/pinocchio#1391]
Dear all,

I would like to have a utility in C++ to convert Eigen vector objects into a SE3 object and the opposite.

Hence porting the SE3ToXYZQUAT and opposite from this file to the official API:
https://github.com/stack-of-tasks/pinocchio/blob/17c479e2fe91905122713643f489feb8ddf135a3/bindings/python/utils/conversions.cpp

Is there a plan for this?

**Comment by jcarpent** [comment]
Yes, should be possible indeed. In the meantime, these functions are very easy to write to fill your need.

**Comment by jcarpent** [comment]
By the way, another compact representation of SE3 can be done via log6/exp6.
