### ISSUE TITLE
14.04 LTS breaking

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/pinocchio#14]
The type CoeffBaseProduct is breaking in 14.04 LTS. This is specific to joint-spherical-ZYX and was introduced by commit dac4a60.
See for instance [line 175](https://github.com/stack-of-tasks/pinocchio/blame/master/src/multibody/joint/joint-spherical-ZYX.hpp#L175)
I do not advice to revert but instead to fix it asap.
I'll try to propose a patch in the next following days.

**Comment by jcarpent** [comment]
It seems that commit f96a04b fixed the problem.

**Comment by fvalenza** [comment]
Exactly @jcarpent
