### ISSUE TITLE
Is \dot{M} - 2C skew-symmetric?

### ISSUE THREAD

**Issue by EpicDuckPotato** [stack-of-tasks/pinocchio#1410]
Hi,
I'm developing a controller which relies on \dot{M} - 2C to be skew-symmetric. When I take the Coriolis matrix from pinocchio, is it defined such that the above is true?
Thanks,
Anoop

**Comment by jcarpent** [comment]
Yes, sure!

**Comment by jcarpent** [comment]
Feel free to reopen this issue if needed.
