### ISSUE TITLE
Computing the COM jacobian in the Local frame. 

### ISSUE THREAD

**Issue by rshum19** [stack-of-tasks/pinocchio#1432]
Hi, 

I currently using this to obtain the center of mass jacobian. 
```
Eigen::VectorXd com = centerOfMass(model,data,q);
Eigen::MatrixXd Jcom = jacobianCenterOfMass(model,data,q);
```

However, I'm looking a quick way of obtaining the center of mass jacobian in a `LOCAL` frame instead of the `WORLD` frame. I have been looking from the documentation but could not find a function that this this like `getFrameJacobian(model, data, frame_id, rf, J)`. 

Could you provide some insight in how to obtain this quantity in the `LOCAL` frame?

Thank you,

**Comment by jcarpent** [comment]
If you want to express the center of mass in another frame, you just need to translate the quantity:
```
oMi[joint_id].actInv(com)
```
For the center of mass Jacobian, you just need to rotate it:
```
oMi[joint_id].rotation().transpose() * Jcom
```

**Comment by rshum19** [comment]
As always thank you @jcarpent for your prompt response. The support your provide make this Library so valuable!
