### ISSUE TITLE
modify kinematic trees after importing urdf file

### ISSUE THREAD

**Issue by timothy233** [stack-of-tasks/pinocchio#1451]
Hi, I am asking if it is possible to modify kinematic trees of robots in pinocchio? E.g, can we add/remove joints or change joints type (e.g. from revolute to spherical) after importing the urdf file?

**Comment by jcarpent** [comment]
You can `addJoint` of course. The removal of joints will be possible in the future, but not yet present. 
Otherwise, you can lock joints and build a reduced model of your robot.
