### ISSUE TITLE
velocityLimits returns highest double value when there is no limits

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/pinocchio#1462]
From my humble opinion, one might return a INF value when there is no limits in the robots.
What is the motivation of the current choice?
Could we change this policy as suggested?

**Comment by jcarpent** [comment]
I think we did that as it was making troubles with Python and Numpy at some points.
I think checking that a number is the biggest value as the same complexity as checking it is a inf. but this is no more the case when performing basic computations.

**Comment by jcarpent** [comment]
In addition, changing this behavior may impact others too.

**Comment by cmastalli** [comment]
Thank you for the answer. I will close this issue
