### ISSUE TITLE
Homogenize GeometryObject and Frame

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/pinocchio#1492]
Hi,

GeometryObject and Frame classes both have a parent joint and parent frame attributes but with different names. I keep forgetting which uses what.

I wonder whether it is a good idea to take the opportunity of version 3 to homogenize this. It's an API change, although it would be easy for users to update their code. Any opinion on this ?

**Comment by jmirabel** [comment]
I am fine with any naming (though I would say it is easier for users if only one of Frame or GeometryObject API do change).

I agree there are similar information but there are fields (type, inertia) of Frame which do not apply to GeometryObject and they are conceptually different. I would keep then separated or I would introduce a top class `TreeItem` that has parent joint and frame, name and placement.

**Comment by jcarpent** [comment]
OK. `previousFrame` seems fine for me. There is no ambiguity at all. Thanks for proposing the notion of `TreeItem`. Or `ModelItem` because we are not only dealing with trees.

**Comment by jcarpent** [comment]
@proyan Could you handle it?

**Comment by proyan** [comment]
Fixed by #1570
