### ISSUE TITLE
Pinocchio 2.6.3 on Conda contains broken path to urdfdom

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/pinocchio#1495]
I've installed Pinocchio in a fresh conda environment and can't configure projects based on Pinocchio:
```
conda create -n MyEnv
conda activate MyEnv
conda install -c conda-forge pinocchio==2.6.3
```

and then when configuring a downstream project I get:
```
CMake Error in CMakeLists.txt:
  Imported target "pinocchio::pinocchio" includes non-existent path

    "/home/wxm/miniconda3/envs/MyEnv/lib64/urdfdom/cmake/../../../include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Indeed, the urdfdom library directory is `lib` and not `lib64` as in the exported interface.**

**Comment by jcarpent** [comment]
I've rerun the build of Pinocchio here: https://github.com/conda-forge/pinocchio-feedstock/pull/64
The issue might come from https://github.com/conda-forge/urdfdom-feedstock/

**Comment by jcarpent** [comment]
Thanks @wxmerkt for the report, even if I think the best place would be https://github.com/conda-forge/pinocchio-feedstock/

**Comment by jcarpent** [comment]
It does work well on my side in a fresh docker image with the new Pinocchio conda update `hbcdfc36_1` (https://anaconda.org/conda-forge/pinocchio/files).

**Comment by jcarpent** [comment]
cf 

```cmake
INTERFACE_INCLUDE_DIRECTORIES "/root/miniconda3/envs/pin/include/eigen3;${_IMPORT_PREFIX}/include;/root/miniconda3/envs/pin/lib/urdfdom/cmake/../../../include;/root/miniconda3/envs/pin/include;/root/miniconda3/envs/pin/lib/urdfdom_headers/cmake/../../../include;/root/miniconda3/envs/pin/include;/root/miniconda3/envs/pin/include"
```

**Comment by wxmerkt** [comment]
Thank you for the swift resolution @jcarpent - it's working now. I'll report to the feedstock in case of future issues
