### ISSUE TITLE
deprecated.hpp does not seem to exist.

### ISSUE THREAD

**Issue by braunzel** [stack-of-tasks/pinocchio#1501]
deprecated.hpp does not seem to exist:
https://github.com/stack-of-tasks/pinocchio/blob/5daf5de1c158363e835d322435bab4aa2f9b9b0b/src/deprecation.hpp#L8

**Comment by jcarpent** [comment]
It does. You need to correctly configure your project via CMake.

**Comment by wxmerkt** [comment]
It gets generated at configuration time: https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/deprecated.hh.cmake

**Comment by jcarpent** [comment]
I will close this issue as it seems to be solved.
Thanks @wxmerkt for your quick and precise answer.
@braunzel Feel free to reopen it if needed.
