### ISSUE TITLE
How to obtain the Jacobian at a certain position on the manipulator link

### ISSUE THREAD

**Issue by WangXingfang** [stack-of-tasks/pinocchio#1515]
Now, I can use pin.getJointJacobian to obtain the Jacobian of the specified joint, and use pin.getFrameJacobian to obtain the Jacobian of the specified link. But, for a certain position on the link, how can I obtain its Jacobian.

**Comment by jcarpent** [comment]
At the time being, you should add a Frame to your model for that.
Soon, this won't be necessary anymore with Pinocchio 3x

**Comment by WangXingfang** [comment]
Great! Can you give me some examples or descriptions about how to add a Frame to my model?
Thanks for your fast response!

**Comment by jcarpent** [comment]
`model.addFrame(Frame("name",joint_support_id,0,placement))`

**Comment by WangXingfang** [comment]
Okay, thanks :)

**Comment by WangXingfang** [comment]
Hello, @ jcarpent. 
While using _model.addFrame_, does _framePlacement_ depend on the _parent_idx_ coordinate system? 
And after adding a frame, how can I change its _parent_idx_ and _framePlacement_ ?

"_model.addFrame(Frame (frame_name, parent_idx, 0, framePlacement, OP_FRAME))_"

**Comment by WangXingfang** [comment]
Hello, @ jcarpent. 
While using _model.addFrame_, does _framePlacement_ depend on the _parent_idx_ coordinate system? 
And after adding a frame, how can I change its _parent_idx_ and _framePlacement_ ?

"_model.addFrame(Frame (frame_name, parent_idx, 0, framePlacement, OP_FRAME))_"

**Comment by jcarpent** [comment]
The frame placement is wrt the parent joint frame.

**Comment by jcarpent** [comment]
> And after adding a frame, how can I change its _parent_idx_ and _framePlacement_ ?

Why do you need to change it?
But you can do by changing the fields within the frame (model.frames[your_frame_id].placement)

**Comment by WangXingfang** [comment]
> Why do you need to change it?

Because I want to get the Jacobian of a certain point on the manipulator, and the point's placement changes in real time. So  I need to change its parent and placement, do you have a better idea?

**Comment by jcarpent** [comment]
> o I need to change its parent and placement, do you have a better idea?

My previous answer will be then sufficient.

**Comment by WangXingfang** [comment]
Okay, I will try to solve the problem with your answer. Thanks :)

**Comment by Mingrui-Yu** [comment]
> At the time being, you should add a Frame to your model for that. Soon, this won't be necessary anymore with Pinocchio 3x

May I know if the Pinocchio 3x has been released? I noticed that the latest released version seems to be 2.7.0.

**Comment by nim65s** [comment]
@Mingrui-Yu not yet
