### ISSUE TITLE
Derivative of Buoyant Force with Respect to State

### ISSUE THREAD

**Issue by EpicDuckPotato** [stack-of-tasks/pinocchio#1516]
Hi,
I posted an issue previously concerning the robot below.
![humrs](https://user-images.githubusercontent.com/11475715/131429649-2f0cc314-5e7a-4fd5-8477-a094e08b6557.png)
I'm interested in adding buoyant forces to my model, where each link is subject to a constant upward force. Since the generalized buoyant force on the robot is dependent on the configuration, the forward dynamics derivatives would thereby change. Is there a convenient way to compute the forward dynamics derivatives in the presence of world-frame external forces on each link?

**Comment by jcarpent** [comment]
Please provide a set of equations to get more insight ?

**Comment by jcarpent** [comment]
We mostly need to know how does this external forces evolved, because I do think they are simply local forces ;)

**Comment by cmastalli** [comment]
The buoyancy forces are the ones obtained using the Archimedes principles. Therefore, if my understanding is correct, these forces are applied in the CoM point of each body, which indeed could be expressed as local forces.

**Comment by EpicDuckPotato** [comment]
![buoyancy](https://user-images.githubusercontent.com/11475715/131492734-d35025ae-9cae-4a97-aa50-e8174f4455e0.png)

In the image, F_b is the total buoyant force, and the summation is over links. J_l is the frame Jacobian for the center of buoyancy of link l. R_w^l rotates from the world frame into the local frame of link l. m_{l, b} is the mass of water displaced by the link, and g = -9.81. pinocchio's aba algorithm allows me to add forces in the local frame of joints, but in my case, I have a force that is always directed upward in the world frame.

**Comment by jcarpent** [comment]
Yes, you can use the LOCAL_WORLD_ALIGNED coordinate system.
Also, you can easily translate the expression of your external forces to express it in the LOCAL coordinate systems.
I think you have your answer. I will then close the issue.

**Comment by EpicDuckPotato** [comment]
Just to clarify, the force is always directed upward in the world frame, so the orientation in the local frame is actually not constant, which is why I'm not sure that I can do what you described.

**Comment by EpicDuckPotato** [comment]
I followed up in stack-of-tasks/pinocchio/#1521 since this issue was closed, but I guess I should just continue here. Do you have an answer my previous comment? i.e. if my forces are constant in the world frame (not local frame), is it still correct to transform them to the local frame and then compute the ABA derivatives? Because for an infinitesimal change in state, the local direction of the forces will change.

**Comment by jcarpent** [comment]
You need to add to the current derivatives wrt to q the term M^-1J^T where J is the Jacobian related to the point of application of your Buoyant force.

**Comment by jcarpent** [comment]
@EpicDuckPotato I do think these answers go a bit beyond what someone can expect from software developers. Isn't it?

**Comment by EpicDuckPotato** [comment]
Alright yeah sorry I guess as far as understanding fundamental physics, I should probably consult elsewhere
