### ISSUE TITLE
Derivative of Buoyant Force with Respect to State: Follow-Up

### ISSUE THREAD

**Issue by EpicDuckPotato** [stack-of-tasks/pinocchio#1521]
Hi,
Thanks for the help with stack-of-tasks/pinocchio#1516, but I just wanted to clarify, the forces I mentioned have a constant magnitude and direction in the world frame, not the local frame. If I transform them to the local frame and then compute the ABA derivatives, is this still correct? Because for an infinitesimal change in state, the local direction of the forces will change.

**Comment by jcarpent** [comment]
Please continue the discussion in #1516. Otherwise, issues will become a nightmare to follow and sort.
