### ISSUE TITLE
Pinocchio Derivatives with Respect to Orientation

### ISSUE THREAD

**Issue by EpicDuckPotato** [stack-of-tasks/pinocchio#1527]
When you calculate the derivative of the forward dynamics with respect to the orientation, are you calculating the derivative I'm showing in the attached images? I'm using q_0 as the current quaternion, and q as the perturbed version.

![dfd_ddtheta](https://user-images.githubusercontent.com/11475715/133333841-6f2b5c7f-58e3-4f92-9900-22a81dcf6a8f.png)

where

![error_quaternion](https://user-images.githubusercontent.com/11475715/133333843-1f3e8390-dba4-403d-bb7d-742af02e5e20.png)

**Comment by jcarpent** [comment]
Pinocchio is totally operating on the tangent space of the configuration space. So yes.
This leads to more stable and robust optimization schemes.

More details in https://hal.laas.fr/hal-01866228/document and https://hal.laas.fr/hal-01790971/file/18-rss-analytical-derivatives-carpentier.pdf
