### ISSUE TITLE
No module named 'pinocchio.pinocchio_pywrap'

### ISSUE THREAD

**Issue by Kongx231** [stack-of-tasks/pinocchio#1528]
I've built and installed pinocchio through the installation procedure, but I'm having trouble importing pinocchio from the build

From make install I get that pinocchio_pywrap is installed:

-- Set runtime path of "/usr/local/lib/python3/dist-packages/pinocchio/pinocchio_pywrap.cpython-36m-x86_64-linux-gnu.so.2.6.3" to ""
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/__init__.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/deprecated.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/deprecation.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/utils.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/robot_wrapper.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/romeo_wrapper.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/explog.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/shortcuts.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/visualize/__init__.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/visualize/base_visualizer.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/visualize/gepetto_visualizer.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/visualize/meshcat_visualizer.py
-- Installing: /usr/local/lib/python3/dist-packages/pinocchio/visualize/panda3d_visualizer.py

when I look in /usr/local/lib/python3/dist-packages/pinocchio, I see that pinocchio_pywrap is in there
deprecated.py
deprecation.py
explog.py
__init__.py
pinocchio_pywrap.cpython-36m-x86_64-linux-gnu.so
pinocchio_pywrap.cpython-36m-x86_64-linux-gnu.so.2.6.3
pinocchio_pywrap_default.cpython-36m-x86_64-linux-gnu.so
pinocchio_pywrap_default.cpython-36m-x86_64-linux-gnu.so.2.9.1
robot_wrapper.py
romeo_wrapper.py
shortcuts.py
utils.py
visualize

And my path contains 
 '/opt/openrobots/lib/python3.6/site-packages', '/usr/local/lib/python3/dist-packages/pinocchio', '/usr/local/lib/python3/dist-packages'

However, when I try to import pinocchio, I get the following error:
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pinocchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3/dist-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
ModuleNotFoundError: No module named 'pinocchio.pinocchio_pywrap'

Am I missing a step of the build and installation process?

**Comment by jcarpent** [comment]
Please remove all the Pinocchio path within your site packages folder. It seems you have a very dirty installation. Otherwise use pip or conda to get a fresh and clean install.

**Comment by nim65s** [comment]
Your setup from source in `/usr/local` and your setup from robotpkg binaries in `/opt/openrobots` are for the python interpreter of your system, which is python 3.6. The error you show at the end is a python 3.8 from conda. 

Conda is not compatible with anything else: please use only conda, or don't use conda at all.

Also, in your path, `/usr/local/lib/python3/dist-packages/pinocchio` is wrong: you should remove it.

**Comment by Kongx231** [comment]
Making those changes fixed the issue. Thank you!
