### ISSUE TITLE
FCL - error

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/pinocchio#153]
Dear all,
Pulling pinocchio from the repo master:master, I have an error with FCL when compiling:

``
include/pinocchio/multibody/geometry.hpp:144:36: error: no match for ‘operator==’ (operand types are ‘const fcl::CollisionResult’ and ‘const fcl::CollisionResult’)
       return (fcl_collision_result == other.fcl_collision_result
``

README.md does not specify which fcl version to take and the dependency.

Best,
Olivier.

**Comment by jcarpent** [comment]
You're fully right. 
The mandatory version of FCL is hpp-fcl (https://github.com/humanoid-path-planner/hpp-fcl/tree/devel) on the devel branch.

We have planed to put this version on the master branch of the repo and to push it on robotpkg.

**Comment by jcarpent** [comment]
I just pushed the devel on the master of hpp-fcl.

**Comment by olivier-stasse** [comment]
Thanks
