### ISSUE TITLE
Get parent joint index from frame index?

### ISSUE THREAD

**Issue by braunzel** [stack-of-tasks/pinocchio#1532]
Dear all,
what is the most efficient way to retrieve the index of a frame's parent joint?

Let's say I have given a `pinocchio::FrameIndex` frame_id, I was hoping to find something like 
joint_id = getParentJointIndex(frame_id)

Did I overlook some method like this? What would be the best way to retrieve the index of the parent joint of a frame?

**Comment by jmirabel** [comment]
`model.frames[frame_id].parent`

**Comment by braunzel** [comment]
Cool, thanks for the quick resolution!
