### ISSUE TITLE
computeImpulseDynamicsDerivatives returns zeros in the column associated to the joint velocity closest to the impact surface

### ISSUE THREAD

**Issue by Kongx231** [stack-of-tasks/pinocchio#1540]
I'm currently using Pinocchio3 and I'm using computeImpulseDynamicsDerivatives for a quadruped model where each leg has 3 joints (2 on the hip and 1 in the knee). When I apply the function, it returns zeros in the columns associated to joint velocities closest to the ground (knee joint velocities). However, if I use impulseDynamics and do a finite difference where I vary the knee velocity, I get variations in the other velocities. I'm wondering if I got the coordinates incorrect for the joint velocities or if this is meant to be.

**Comment by proyan** [comment]
Hi Kong231,
Thanks for your report. I'll have a look at it this week. Did you advance on your side, or is the status still the same as reported in this issue?

**Comment by Kongx231** [comment]
I still haven't been able to advance on my side and the issue still persists. Thanks for looking into the issue.

**Comment by Kongx231** [comment]
If it helps, I've implemented the full finite difference and I validate that the finite difference with some random perturbation.
[impulse-dynamics-debugging-finite-diff.tar.gz](https://github.com/stack-of-tasks/pinocchio/files/7522050/impulse-dynamics-debugging-finite-diff.tar.gz)

**Comment by proyan** [comment]
@Kongx231 
I see that the mesh names in your laikago folder point to example-robot-data path. Do you have Laikago locally in example-robot-data? If so, could you please make a PR there to officially add it to the main repo?

**Comment by proyan** [comment]
I just added the laikago_description from unitree site here: https://github.com/proyan/example-robot-data
Could you make a PR of your modifications on top of the devel branch please, so we could push to the main repo?

**Comment by Kongx231** [comment]
Just submitted the pull request. Please let me know if you need anything else.

**Comment by proyan** [comment]
@Kongx231  Could you please try https://github.com/proyan/pinocchio/tree/pinocchio3-preview branch and see if it works?

**Comment by Kongx231** [comment]
Both derivatives are still off on my end when using that branch. I've uploaded the full finite diff code that I'm working with now.
[impulse-dynamics-finite-diff-updated.tar.gz](https://github.com/stack-of-tasks/pinocchio/files/7585850/impulse-dynamics-finite-diff-updated.tar.gz)

**Comment by proyan** [comment]
I checked your fd from this file, and compared against my own.

> [impulse-dynamics-debugging.tar.gz](https://github.com/stack-of-tasks/pinocchio/files/7420488/impulse-dynamics-debugging.tar.gz)

The problem is solved with the above branch, I'll upload the file, look at the implementation of dRdq_fd and dRdv_fd, and compare against the original

```python
 164 print("dRdv_fd error", np.linalg.norm(dRdv + np.identity(model.nv) - dRdv_fd))                                                                                                                                
 165 print("dRdq_fd error", np.linalg.norm( dRdq - dRdq_fd))                                                                                                                                                       
```

```python
dRdv_fd error 7.70235172283836e-07
dRdq_fd error 1.21393614766353e-06
```

[impulse-derivatives-laikago-2.zip](https://github.com/stack-of-tasks/pinocchio/files/7586519/impulse-derivatives-laikago-2.zip)

Have a look, and let me know if there is still an issue

**Comment by Kongx231** [comment]
Great, I had an issue with my environment and was able to fix it and get the fix working. Thanks!
