### ISSUE TITLE
how to import pinocchio.casadi 

### ISSUE THREAD

**Issue by xeonz1** [stack-of-tasks/pinocchio#1576]
I compiled pinocchio 3 along with casadi support and py bindings. I have 
![image](https://user-images.githubusercontent.com/56295370/146156563-f5b01a26-b700-47f9-bef9-f2e894d9d5f5.png)
But I still cannot use pinocchio.casadi module. What should I do?

**Comment by jcarpent** [comment]
Did you install it?
If so, `import pinocchio.casadi as cpin` should work.

**Comment by xeonz1** [comment]
> 

It works for me. How should I use this module?

**Comment by jcarpent** [comment]
As normal Pinocchio, you can transform a classic model into a casadi one and perform as usual.
```
cmodel = cpin.Model(pin.Model())
cdata  = cmodel.createData()
```

**Comment by xeonz1** [comment]
> 

What about using symbolic q? I use ConfigVectorType variables and assign SX variables to them in C++. How to do in py?

**Comment by jcarpent** [comment]
You can directly pass Casadi Matrix types as usual with Casadi.

**Comment by xeonz1** [comment]
> You can directly pass Casadi Matrix types as usual with Casadi.

I use pinocchio.casadi.jointJacobian(robot, data, cs_q, 1) where cs_q is a casadi MX, but it says 

`Python argument types in
    pinocchio.pinocchio_pywrap_default.computeJointJacobian(Model, Data, MX, int)
did not match C++ signature:
    computeJointJacobian(struct pinocchio::ModelTpl<double,0,struct pinocchio::JointCollectionDefaultTpl> model, struct pinocchio::DataTpl<double,0,struct pinocchio::JointCollectionDefaultTpl> {lvalue} data, class Eigen::Matrix<double,-1,1,0,-1,1> q, unsigned __int64 joint_id)
`

**Comment by jcarpent** [comment]
It should be a Casadi SX.
