### ISSUE TITLE
Is Denavit Hartenberg parameters supported for industrial robots?

### ISSUE THREAD

**Issue by moliqingwa** [stack-of-tasks/pinocchio#1592]
Is Denavit Hartenberg parameters supported for industrial robots?

**Comment by jcarpent** [comment]
The quick answer is not directly but it should be easy to write a converter. Do you have a URDF model of your robot?

**Comment by moliqingwa** [comment]
Thanks for your quick response. No URDF models at hand currently but I'll dig into it some time :)

**Comment by jmirabel** [comment]
Going from DH to URDF is very easy. You can even use [online resources](https://adohaha.github.io/DH2URDF/) for this. It wouldn't be hard to implement, in case you happen to have some time for this.

The reverse is not as straightforward, but is also less useful.
