### ISSUE TITLE
Problem about joint jacobian reference frame and floating base pose

### ISSUE THREAD

**Issue by xeonz1** [stack-of-tasks/pinocchio#1593]
I have a floating base model with root_joint=pinocchio.JointModelFreeFlyer()

According to https://stack-of-tasks.github.io/pinocchio/assets/math-concepts.pdf, one can compute relative velocity between two joint-connected body 1 and 2 by = 2_v_12  = 2_J * v_j
Seems like the connection in pinocchio is a bit different from the URDF definition. 
```
import pinocchio.casadi
import casadi
import random
robot, robot_collison, robot_visual = pinocchio.casadi.buildModelsFromUrdf(
    "./robot.urdf", root_joint=pinocchio.JointModelFreeFlyer()
)
cs_q = casadi.SX.sym("cs_q", robot.nq)
cs_v = casadi.SX.sym("cs_v", robot.nv)
robot = pinocchio.casadi.Model(robot)
data = robot.createData()

pinocchio.casadi.forwardKinematics(robot, data, cs_q, cs_v)
pinocchio.casadi.computeJointJacobians(robot, data, cs_q)
pinocchio.casadi.updateFramePlacements(robot, data)


nice = casadi.Function(
    "nice", [cs_q, cs_v], [pinocchio.casadi.getFrameJacobian(robot, data, robot.getFrameId("left_wheel"), pinocchio.LOCAL)@cs_v,
                           pinocchio.casadi.computeFrameJacobian(
                               robot, data, cs_q, robot.getFrameId("left_wheel"), pinocchio.LOCAL)@cs_v,
                           pinocchio.casadi.getJointJacobian(robot, data, robot.getJointId(
                               "left_wheel_motor"), pinocchio.LOCAL)@cs_v,
                           pinocchio.casadi.computeJointJacobian(
                               robot, data, cs_q, robot.getJointId("left_wheel_motor"))@cs_v,
                           cs_v[8]
                           ])
for j in range(100):
    print("number: ", j)
    print(nice([0.5]*4 + [random.random() for i in range(9)], [random.random()
          for i in range(12)]))

```

**Comment by jcarpent** [comment]
You have provided an incomplete example. We don’t have access to the model.
@proyan could you provide help on this issue please?

**Comment by xeonz1** [comment]
> You have provided an incomplete example. We don’t have access to the model. @proyan could you provide help on this issue please?

Sorry, I uploaded the urdf in: 
https://github.com/xeonz1/hello-world/blob/master/robot.urdf

**Comment by xeonz1** [comment]
I may have solved the problem. Analysis is given by:
1. The generated quaternion may be irregular and lead to wrong SE3 transform. Therefore one can use:
```
euler2quat([random.random() for i in range(3)])
```
2. One should use only the joint velocity v_j instead of the generalized velocity of the model.

**Comment by proyan** [comment]
Glad you solved the problem. Regarding your analysis, 
1a) there is a `randomConfiguration(model, lowerLimits, upperLimits)` function available in pinocchio that you could use to generate random configurations, without worrying about quaternion normalization
1b) you could also use `.normalize()` function in quaternion in order to normalize the randomly generated quaternion.

Have fun using pinocchio :)
