### ISSUE TITLE
Get the current configuration 

### ISSUE THREAD

**Issue by nkashiri** [stack-of-tasks/pinocchio#1595]
Hello, 
As I would like to do a set of verifications for my implementation, while at one stage I set a configuration on my Data using forwardKinematics, I would like to get the configuration that is stored in my Data in another stage. Can I somehow retrieve/get the current joint configuration set the Data?
Thanks

**Comment by jcarpent** [comment]
Hi !

We do not store the configuration, velocity or any input arguments within Data for efficiency reasons.
You can easily add this feature, by inheriting from Data in Python or C++ and storing these quantities within the new class.

**Comment by nkashiri** [comment]
I see, thanks for the quick reply
