### ISSUE TITLE
Problem about JointModelFreeFlyer initial placement

### ISSUE THREAD

**Issue by xeonz1** [stack-of-tasks/pinocchio#1596]
Hi,

I want to ask if the initial placement of a JointModelFreeFlyer is related to the definition of floatingbase in urdf? For example:
```
<link
    name="floating_base">
    <inertial>
      <origin
        xyz="0.00024495 -0.0012722 -0.067949"
        rpy="0 0 0" />
```
I have a robot with leg and tried to find the foot position with some configuration. It appears that the orientation of the floating base is not as expected because when the foot position sign is opposite to expected.
Of course this can also be caused by the different definition of revolute joint zero position. I used rviz to check the zero position of revolute joints. What is the pinocchio convention of handling zero position?

**Comment by jcarpent** [comment]
Sorry, but your issue is not clear at all.
I don't get what do you expect.

**Comment by xeonz1** [comment]
> Hi @xeonz1 The `origin` in the `link` corresponds to the position of the `link` w.r.t it's parent. So for a zero joint configuration, the `floating_base` should appear at the position specified in the `origin` in your example

Thanks for the reply. I have a floating_base link defined as 
```
    <inertial>
      <origin
        xyz="0.00024495 -0.0012722 -0.067949"
        rpy="0 0 0" />
```
Then I run
```
import pinocchio
import numpy as np
from quat2euler import *
robot, robot_collison, robot_visual = pinocchio.buildModelsFromUrdf(
    "./robotfb.urdf", root_joint=pinocchio.JointModelFreeFlyer()
)
data = robot.createData()
q = np.array([0, 0, 0]+ euler2quat_math([0]*3))
print(pinocchio.centerOfMass(robot, data, q))
```
with the output 
```
[0.00024495 0.0012722  0.067949  ]
```
Why it is not the same as <inertial><origin xyz> and appears that the floating_base is revoluted by 180 degree w.r.t. its x-axis?

**Comment by jcarpent** [comment]
It depends on your convention for Euler angles I would say.
Use the eigenpy (Eigen Python bindings) to get the correct convention.
You can also use `pin.SE3ToXYZQuat(pin.SE3.Identity())`

**Comment by xeonz1** [comment]
> It depends on your convention for Euler angles I would say. Use the eigenpy (Eigen Python bindings) to get the correct convention. You can also use `pin.SE3ToXYZQuat(pin.SE3.Identity())`

For 
```
print(pinocchio.se3ToXYZQUAT(pinocchio.SE3().Identity()))
```
I get [0. 0. 0. 0. 0. 0. 1.]
and for my `euler2quat_math` I get for non-rotation quaternion [1,0,0,0]
What is the definition of quaternion in pinocchio?

**Comment by jcarpent** [comment]
This is the one of Eigen (x,y,z,w).

**Comment by xeonz1** [comment]
> This is the one of Eigen (w,x,y,z).

Ok. My problem is solved.
