### ISSUE TITLE
Computing the dynamics via RNEA

### ISSUE THREAD

**Issue by JunningHuang** [stack-of-tasks/pinocchio#1602]
Hey, 

I tried to use pinocchio to construct regression matrix and extract dynamic parameters from urdf files.
https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/md_doc_b-examples_c-dynamics.html#autotoc_md40, 
from the above link, it seems you plan to provide an explicit way to compute the inverse dynamics via Netwon-Euler equation, are you going to release this example recently?

Thanks and best wishes

**Comment by jcarpent** [comment]
What do you want to do exactly @JunningHuang?

**Comment by jcarpent** [comment]
Otherwise, you can do inverse dynamics as `tau = rnea(model, data, q, v, a, fext)`.
