### ISSUE TITLE
Empty `Model` has one joint

### ISSUE THREAD

**Issue by vnghia** [stack-of-tasks/pinocchio#1607]
I would like to ask why there is a joint in the empty model ?
```python
--> import pinocchio as pin
--> a = pin.Model()
--> a.joints
<pinocchio.pinocchio_pywrap.StdVec_JointModelVector object at 0x7fd854a506a0>
--> list(a.joints)
[
    JointModelRX
  index: 18446744073709551615
  index q: -1
  index v: -1
  nq: 1
  nv: 1
]
```

If we need an universal joint, does the size of [`fext`](https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/namespacepinocchio.html#a26d94ea6486d0eed1934b94767124a01) need to be equal to the number of real joints + 1 as that seems unnecessary to me ?

**Comment by jcarpent** [comment]
This joint is related to the universe. It has no meaning by the way. It is just the result of having it by default set to JointModelRX, as it is the default variant.
Fext should be of size `model.njoints`.
