### ISSUE TITLE
Old version in documentation (2.6.4 instead of 2.6.5)

### ISSUE THREAD

**Issue by Ren911** [stack-of-tasks/pinocchio#1616]
Hello! You have released version 2.6.5 about a month ago. https://github.com/stack-of-tasks/pinocchio/releases/tag/v2.6.5
But if I go to the documentation, there I find old version 2.6.4 ( https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/ on main github page) 

There was some bug with wrong Latex formula (https://github.com/stack-of-tasks/pinocchio/pull/1567), and still is, I think, for this reason.  
![image](https://user-images.githubusercontent.com/6950673/158594444-ed8b0d43-4c66-417a-9aeb-a1cba99cee4d.png)

**Comment by nim65s** [comment]
Hi,

It looks like master was stuck on 47e600e3287ee033be7ee19a82ab25f2eb366b58 on the mirror that generate the doc. I just made a force push ; the doc should update itself in a couple hours.
