### ISSUE TITLE
Pinocchio::log6 question

### ISSUE THREAD

**Issue by bhtxy0525** [stack-of-tasks/pinocchio#1617]
Hi, I would like to know which way is used to express the rotation in function **pinocchio:: log6** , is it quaternion?

**Comment by jcarpent** [comment]
The log6 operation takes as input a placement SE3 and outputs a Motion, is it answering your question?

**Comment by bhtxy0525** [comment]
> 

thanks for your reply, i have understood.

**Comment by bhtxy0525** [comment]
@jcarpent thanks for your reply, i have understood.
