### ISSUE TITLE
Position and orientation of end-effector

### ISSUE THREAD

**Issue by arjung128** [stack-of-tasks/pinocchio#1621]
I'm working with the frank panda robot:

```
Nb joints = 11 (nq=16,nv=15)
  Joint 0 universe: parent=0
  Joint 1 root_joint: parent=0
  Joint 2 panda_joint1: parent=1
  Joint 3 panda_joint2: parent=2
  Joint 4 panda_joint3: parent=3
  Joint 5 panda_joint4: parent=4
  Joint 6 panda_joint5: parent=5
  Joint 7 panda_joint6: parent=6
  Joint 8 panda_joint7: parent=7
  Joint 9 panda_finger_joint1: parent=8
  Joint 10 panda_finger_joint2: parent=8
```

When I do:

```
pin.forwardKinematics(model, data, q)
pin.updateFramePlacements(model,data)
```

then `data.oMf.tolist()` contains 25 frames. `model.frames[19]` corresponds to panda_hand_joint, and `model.frames[20]` corresponds to panda_hand -- which of these should I look at for the end-effector position? Thanks!

**Comment by jcarpent** [comment]
It seems you've added a free-flyer joint to your robot. Is it on purpose?

**Comment by jcarpent** [comment]
For control, you should always refer to the parent joint (frame.parent) quantity to get the closest supporting joint.
Is it answering your question?

**Comment by arjung128** [comment]
But `model.frames[frame_id].parent` for `frame_id` in `[15:20]` is `8` -- which of these do I look at?

**Comment by jcarpent** [comment]
model.joints[8] corresponds to the supporting joint.

**Comment by arjung128** [comment]
That gives me:

```
JointModelRZ
  index: 8
  index q: 13
  index v: 12
  nq: 1
  nv: 1
```
  
What would the frame_id be? Sorry I'm not following.

**Comment by jcarpent** [comment]
What is the name of your end-effector? This is on your side that you should know this information.

**Comment by arjung128** [comment]
Got it, thanks!

**Comment by jcarpent** [comment]
Perfect.
