### ISSUE TITLE
macos python : import pinocchio error

### ISSUE THREAD

**Issue by magic-alt** [stack-of-tasks/pinocchio#1627]
>>> import pinocchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/pinocchio/2.6.3/lib/python3.9/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
ImportError: dlopen(/usr/local/Cellar/pinocchio/2.6.3/lib/python3.9/site-packages/pinocchio/pinocchio_pywrap.cpython-39-darwin.so, 2): Library not loaded: /usr/local/opt/urdfdom/lib/liburdfdom_sensor.1.0.dylib
  Referenced from: /usr/local/Cellar/pinocchio/2.6.3/lib/python3.9/site-packages/pinocchio/pinocchio_pywrap.2.6.3.cpython-39-darwin.so
  Reason: image not found

**Comment by jcarpent** [comment]
Hello!

Could you use instead conda to install Pinocchio?
Best,

Justin
