### ISSUE TITLE
Optimal way to compute Jdot-times-v ?

### ISSUE THREAD

**Issue by alaurenzi** [stack-of-tasks/pinocchio#1628]
Hello Pinocchio community,
What is the recommended way to compute the frame acceleration component that is due to to the joints motion alone, i.e. `a_bias = Jdot*v`? Is there a more efficient way than (i) to compute the whole `Jdot`, or (ii) to call `forwardKinematics` with zero acceleration? 
Note that, in my application, (ii) would be kind of a "waste" since `forwardKinematics` must anyway be called with the correct joint acceleration vector in order to perform other calculations.

Thanks a lot for your work,
Arturo

**Comment by jcarpent** [comment]
Hi @alaurenzi,

The fatest way is to call `forwardKinematics(model, data, q, v, Eigen::VectorXd(model.nv))`.
This is a very fast operation, near `1us` for a humanoid robot on modern CPUs.
