### ISSUE TITLE
Can the input of pinocchio.forwardKinematics() be a set of joint angles?

### ISSUE THREAD

**Issue by WangXingfang** [stack-of-tasks/pinocchio#1634]
For a 6-DOF robot, we have a set of joint angles as follows.
q_all = np.array([[0, 0, 0, 0, 0, 0],[1, 1, 1, 1, 1, 1],[2, 2, 2, 2, 2, 2]]), which is a 3x6 matrix.
So can we take “q_all” directly as an input “q” to pinocchio.forwardKinematics(model, data, q)? 
Because the method used _for_ loop is time-consuming, let's say "q_all" is a 1000* 6 matrix.

**Comment by jcarpent** [comment]
Batch computation is not yet supported by Pinocchio. What is your application?

**Comment by jcarpent** [comment]
What is the application for? Which computations do you want to perform after this batch computation?

**Comment by WangXingfang** [comment]
> What is the application for? Which computations do you want to perform after this batch computation?
I want to use it in the reinforcement learning application of 7-DOF robot. For example, input 1000 joint angle samples to calculate their forward kinematics. If the _for_ loop is used for serial calculation, it takes a long time. Therefore, I want to use parallel computing to improve computing efficiency.

**Comment by WangXingfang** [comment]
> What is the application for? Which computations do you want to perform after this batch computation?

I want to use it in the reinforcement learning application of 7-DOF robot. For example, input 1000 joint angle samples to calculate their forward kinematics. If the for loop is used for serial calculation, it takes a long time. Therefore, I want to use parallel computing to improve computing efficiency.

**Comment by WangXingfang** [comment]
> 

Thanks for your advice! 
I'm working in Python. And I will consider the multi-threading computation.

**Comment by WangXingfang** [comment]
> Small question: what do you expect from the forward kinematics results? You can see to the pool structure implemented in Pinocchio to use them for multi-threading evaluation.
> 
> Do you work in C++?

Thanks for your advice!
I'm working in Python. And I will consider the multi-threading computation.
