### ISSUE TITLE
SystemError: initialization of pinocchio_pywrap raised unreported exception

### ISSUE THREAD

**Issue by BolunDai0216** [stack-of-tasks/pinocchio#1635]
I just install pinocchio using `conda install -c conda-forge pinocchio` on a 20.04 Ubuntu machine. and I got the following error when importing it
```
>>> import pinocchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bolun/miniconda3/envs/solo_env/lib/python3.8/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
SystemError: initialization of pinocchio_pywrap raised unreported exception
```

This did not occur when following the same procedure for installation on a MacBook. Can someone help me take a look and see what might be the issue?

Thanks in advance.

**Comment by jcarpent** [comment]
@proyan will take care of the answer.

**Comment by proyan** [comment]
Hi BolunDai0216,
Unfortunately, boost python hides the exceptions that python raises, and it becomes difficult to debug. This was reported in boost python some time ago: 
https://github.com/boostorg/python/issues/280

If you wish to debug this issue, I would suggest that you try to install the more updated version of boost python and try to see what the python raised error is.

However, if that is not possible for you, the only option that you have is to wade blindly. I would suggest that you check and re-check your installation directories, and see if there are ubuntu apt-installed packages that are clashing with the conda installations. These may include urdfdom*, libboost*, eigen3 etc. If I had to guess, I would say that you have multiple installations that are confusing conda.

**Comment by jcarpent** [comment]
> I just install pinocchio using `conda install -c conda-forge pinocchio` on a 20.04 Ubuntu machine. and I got the following error when importing it
> 
> ```
> >>> import pinocchio
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/bolun/miniconda3/envs/solo_env/lib/python3.8/site-packages/pinocchio/__init__.py", line 6, in <module>
>     from .pinocchio_pywrap import *
> SystemError: initialization of pinocchio_pywrap raised unreported exception
> ```
> 
> This did not occur when following the same procedure for installation on a MacBook. Can someone help me take a look and see what might be the issue?
> 
> Thanks in advance.

I've been able to start Pinocchio cleanly from a clean environment made from a fresh docker image of ubuntu 20.04.
I guess you have multiple install of Pinocchio on your system. Could you check it with `locate libpinocchio`?

**Comment by BolunDai0216** [comment]
When running `locate libpinocchio` actually I get nothing back. I do have multiple pinocchio installations on my system. I was able to get it working yesterday by building from source.

**Comment by BolunDai0216** [comment]
I ran `updatedb` and now I do see multiple libpinocchio
```
/home/bolun/Documents/pinocchio/build/src/libpinocchio.so
/home/bolun/Documents/pinocchio/build/src/libpinocchio.so.2.6.6
/home/bolun/miniconda3/envs/myenv/lib/libpinocchio.so
/home/bolun/miniconda3/envs/myenv/lib/libpinocchio.so.2.6.4
/home/bolun/miniconda3/envs/solo_env/lib/libpinocchio.so
/home/bolun/miniconda3/envs/solo_env/lib/libpinocchio.so.2.5.6
/home/bolun/miniconda3/pkgs/pinocchio-2.5.6-py38hd23d2ce_1/lib/libpinocchio.so
/home/bolun/miniconda3/pkgs/pinocchio-2.5.6-py38hd23d2ce_1/lib/libpinocchio.so.2.5.6
/home/bolun/miniconda3/pkgs/pinocchio-2.6.4-py310hf3e5c9c_1/lib/libpinocchio.so
/home/bolun/miniconda3/pkgs/pinocchio-2.6.4-py310hf3e5c9c_1/lib/libpinocchio.so.2.6.4
/opt/openrobots/lib/libpinocchio.so
/opt/openrobots/lib/libpinocchio.so.2.6.5
/usr/local/lib/libpinocchio.so
/usr/local/lib/libpinocchio.so.2.6.6
```
any idea on how to handle this and not confuse conda?

**Comment by jcarpent** [comment]
you should remove the one installed with apt and the ones in `/usr/local/lib`
