### ISSUE TITLE
Fix one axis of ZYX joint

### ISSUE THREAD

**Issue by xeonz1** [stack-of-tasks/pinocchio#1645]
Hi,

I wonder if there is any way to fix the z-axis rotation of ZYX spherical joint?

**Comment by jcarpent** [comment]
What do you mean?
If you want to fix it, you can use QP solvers by adding a constraint on the motion along the Z-axis.

**Comment by cmastalli** [comment]
You could append two rotating joints. This will avoid unnecessary complex optimization scheme.

**Comment by jmirabel** [comment]
Mind that a 2-dimension rotation group does not exist. The dimension is necessarily uneven. Most commonly in robotics, 1D for rotations in the plane and 3D for rotation in the euclidean space.
