### ISSUE TITLE
any demo for system identification?

### ISSUE THREAD

**Issue by undefinedcodezhong** [stack-of-tasks/pinocchio#1646]
Could you provide any demo about the function "computations of kinematic and dynamic regressors for system identification"? Thank you.

**Comment by jcarpent** [comment]
Sorry. We don't have resources for that currently. Could you handle this task?
Which system do you want to identify?

**Comment by jcarpent** [comment]
By the way, @undefinedcodezhong, it would be nice to add more politeness to your request: we are human beings.

**Comment by undefinedcodezhong** [comment]
Sorry, I didn't notice your reply before due to my carelessness. I apologize for my previous behavior sincerely. @jcarpent
