### ISSUE TITLE
EIGEN_MAKE_ALIGNED_OPERATOR_NEW in model and data classes

### ISSUE THREAD

**Issue by MaximilienNaveau** [stack-of-tasks/pinocchio#165]
To be able to instantiate a model and data using the `new` operator one should add
`EIGEN_MAKE_ALIGNED_OPERATOR_NEW`
as a public macro in the classes.
This is needed feature if you want to have pointers own and initialized in a single class.

**Comment by jcarpent** [comment]
@fvalenza Can you add this fix in your next PR?

**Comment by jcarpent** [comment]
Solved by #172.
