### ISSUE TITLE
Joint Model methods need more robust tests

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#167]
In Joint Configurations unittest, we need more trivial unit tests. @fvalenza Can you increase the number of trivial tests?

**Comment by jmirabel** [comment]
You may have a look at this (rather simple) test for inspiration: https://github.com/humanoid-path-planner/hpp-model/blob/devel/tests/test-configuration.cc

**Comment by jcarpent** [comment]
Solved by #234.
