### ISSUE TITLE
Make the python buiding build optionnal (true by default if needed)

### ISSUE THREAD

**Issue by MaximilienNaveau** [stack-of-tasks/pinocchio#168]
It would be awesome to be able to compile libpinocchio.so and install it without having tones of memory cache needed by the binding python.

**Comment by jcarpent** [comment]
You're right. Currently, the python bindings are build if eigenpy is found. But it is not necessarily a mandatory feature.This can be added to a future PR.

**Comment by jcarpent** [comment]
Solved by #170.
