### ISSUE TITLE
Why do I get extra number of frames when I do model.buildModelFromUrdf()?

### ISSUE THREAD

**Issue by winkhoo** [stack-of-tasks/pinocchio#1708]
Hello all,

I am fairly new to pinocchio. Pardon me if the question is considerably naive. According to RVIZ,

It should have only 3 frames as shown below:
![Screenshot from 2022-07-05 21-39-29](https://user-images.githubusercontent.com/92617946/177469596-258f9529-ac5c-4340-a075-141c22dcfbf4.png)

But as pinocchio returns 7 frames, namely with the additional frames named "universe", "root_joint", and also including all the joints and links. Instead of just three frames as showed by RVIZ.

![Screenshot from 2022-07-05 21-48-17](https://user-images.githubusercontent.com/92617946/177471526-49caa422-4506-484d-a027-fd2b576fc250.png)

Thank you in advance.

**Comment by jcarpent** [comment]
universe is a default frame in Pinocchio related to the universe.
Then, for each joint, the URDF parser in Pinocchio adds a Frame in such a way you can operate some easy operations just by using frames.

**Comment by winkhoo** [comment]
Thank you mate, this is helpful to me.
