### ISSUE TITLE
Compiling problem with geomId

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/pinocchio#171]
Hi,
Sorry I did not found geomId in geometry.hpp called here:
https://github.com/stack-of-tasks/pinocchio/blob/master/unittest/geom.cpp#L430
Is this a missing commit ?

**Comment by jcarpent** [comment]
No. This unit test is compiled with you have HPP and either your version of HPP is too old or this unit test must be updated to fulfil the last version of HPP.

**Comment by fvalenza** [comment]
The method name "geomId " may have changed in a previous rework of the way
a geometry model store the geometry objects. I do not have my laptop to
check it now but to solve it now it could be  "getCollisionId" or
"getVisualId"

this needs to be updated in the optional tests indeed
Le 20 mai 2016 13:34, "Justin Carpentier" <notifications@github.com> a
écrit :

**Comment by jcarpent** [comment]
Solved by #173.
