### ISSUE TITLE
Next PyPI release

### ISSUE THREAD

**Issue by stephane-caron** [stack-of-tasks/pinocchio#1745]
This issue is to keep track of the next PyPI release :pray: 

Presently PyPI is still at 2.6.4 while Pinocchio is at 2.6.9. More recent versions ship features and fixes that downstream projects rely on, e.g. https://github.com/stephane-caron/robot_descriptions.py/issues/6

**Comment by jcarpent** [comment]
The release of Pinocchio 2.6.10 is now out. We can proceed to an upgrade on PyPi from it.

**Comment by jcarpent** [comment]
It is now online ;)
Thanks @nim65s for the great job.
