### ISSUE TITLE
Cmake fails to find pinocchio when building with colcon

### ISSUE THREAD

**Issue by manumerous** [stack-of-tasks/pinocchio#1754]
Hi I am trying to include pinocchio in a ocs2_pinocchio_interface in a larger software project that is using using colcon as its build system. 

I can succesfully compile Pinocchio using:

```
colcon build --packages-select pinocchio --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release
```

If I try to include pinocchio in the CMakeLists of another colcom package and compiling all packages:

```cmake_minimum_required(VERSION 3.0.2)
project(ocs2_pinocchio_interface)

# Generate compile_commands.json for clang tools
# set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CATKIN_PACKAGE_DEPENDENCIES
  ocs2_core
  ocs2_robotic_tools
)

find_package(catkin REQUIRED COMPONENTS
  ${CATKIN_PACKAGE_DEPENDENCIES}
)

find_package(PkgConfig REQUIRED)

# find_package(pinocchio REQUIRED)
pkg_check_modules(pinocchio REQUIRED pinocchio)

find_package(Eigen3 3.3 REQUIRED NO_MODULE)

# Add pinocchio configurations
include(cmake/pinocchio_config.cmake)

###################################
## catkin specific configuration ##
###################################

catkin_package(
  INCLUDE_DIRS
    include
    ${pinocchio_INCLUDE_DIRS}
  LIBRARIES
    ${PROJECT_NAME}
  CATKIN_DEPENDS
    ${CATKIN_PACKAGE_DEPENDENCIES}
  DEPENDS
    pinocchio
  CFG_EXTRAS
    pinocchio_config.cmake
)

###########
## Build ##
###########

include_directories(
  include
  ${catkin_INCLUDE_DIRS}
  ${EIGEN3_INCLUDE_DIRS}
  ${pinocchio_INCLUDE_DIRS}
)

# ocs2 pinocchio interface library
add_library(${PROJECT_NAME}
  src/PinocchioInterface.cpp
  src/PinocchioInterfaceCppAd.cpp
  src/PinocchioEndEffectorKinematics.cpp
  src/PinocchioEndEffectorKinematicsCppAd.cpp
  src/urdf.cpp
)
add_dependencies(${PROJECT_NAME}
  ${catkin_EXPORTED_TARGETS}
)
target_link_libraries(${PROJECT_NAME}
  ${catkin_LIBRARIES}
  ${pinocchio_LIBRARIES}
)
target_compile_options(${PROJECT_NAME} PUBLIC ${OCS2_PINOCCHIO_FLAGS})
```
I get the following error:
```--- stderr: ocs2_pinocchio_interface   
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  CMakeLists.txt:19 (pkg_check_modules)
``` 
If I replace `pkg_check_modules(pinocchio REQUIRED pinocchio)` with `find_package(pinocchio REQUIRED)` I get the interesting error:

```
CMake Error at CMakeLists.txt:18 (find_package):
  Found package configuration file:

    /home/manu/src/aria_mpc_ws/install/pinocchio/lib/cmake/pinocchio/pinocchioConfig.cmake

  but it set pinocchio_FOUND to FALSE so package "pinocchio" is considered to
  be NOT FOUND.
```
So could it be that the Pinocchio colcom package is not finding any dependencies it needs despite compiling? Or why is Pinocchio labeled as not found despite finding `pinocchioConfig.cmake`? For the other components it worked to compile the catkin packages using colcom. But somehow not for this one which I don't understand. I am aware that this is not necessarily a Pinocchio issue but any help would be appreciated. Let me now if there is anything else I can provide. 

Thank you!

**Comment by jcarpent** [comment]
Thanks for raising this issue @manumerous.
@wxmerkt Do you know the correct solution for ROS settings? Thanks in advance for your help.

**Comment by wxmerkt** [comment]
Hi @manumerous 
Colcon works well as a buildsystem from source and from binary. I wonder if the included plugins in this project could cause an issue. Have you tried it with a minimal project in the same workspace? E.g. try https://github.com/wxmerkt/pinocchio_ros_example to see if you experience the same error above. I've tried this one in a colcon workspace on Ubuntu 20.04 using the latest Pinocchio `devel` branch with both `colcon build` and `colcon build --symlink-install` and it worked fine.

If the error persists, can you please share which version (branch/commit) of Pinocchio you are trying to build? And the generated `pinocchioConfig.cmake`. Many thanks!

**Comment by manumerous** [comment]
Hi Thanks a lot for your inputs. They helped a lot. I switched from master to devel this morning and downloaded your repository. Compiling the pinocchio_ros_example using colcon worked.

I figured out that the issue was that I disabled hpp-fcl in the Pinocchio CMakeLists.txt. compiling hpp-fcl with colcon and adding it back to the CMakeLists.txt solved the issue since my package seems to depend on it. 

It took me some while to figure this out since even when reducing the CMakeLists.txt of my package to:

```
cmake_minimum_required(VERSION 3.0.2)
project(ocs2_pinocchio_interface)

find_package(catkin REQUIRED)

find_package(pinocchio REQUIRED)
catkin_package()
```

I would still get the error:

```
CMake Error at CMakeLists.txt:18 (find_package):
  Found package configuration file:

    /home/manu/src/aria_mpc_ws/install/pinocchio/lib/cmake/pinocchio/pinocchioConfig.cmake

  but it set pinocchio_FOUND to FALSE so package "pinocchio" is considered to
  be NOT FOUND.
```

which does not help much in my opinion. I would be happy to contribute to improve the error message if you agree that this would be an improvement. 

Anyways thanks a lot for your help!

**Comment by nim65s** [comment]
There are several places in `pinocchioConfig.cmake` which could set `pinocchio_FOUND` to false. You could reproduce your issue, then edit this file, look for those places, and add some debug with `message(WARNING "something")` inside to find the culprit. This would be a first step to help adding a better error message I guess.

**Comment by jcarpent** [comment]
I'm closing the issue. Hope @manumerous you have found a solution.
