### ISSUE TITLE
Map from configuration to tangent coordinates

### ISSUE THREAD

**Issue by stephane-caron** [stack-of-tasks/pinocchio#1758]
For bounded joints (translations or bounded revolute joints), there is a one-to-one mapping between configuration and tangent coordinates. It would be convenient if Pinocchio computed it, as it would allow things like:

```python
for i in range(model.nq):
    if is_interesting(model, i):
        velocity[model.configuration_to_tangent(i)] = ...
```

For an unbounded rotational joint (revolute, spherical, ...), this map could be either undefined, or map the joint's configuration coordinates to the joint's first tangent coordinate.

**Edit:** there is a more concrete example in https://github.com/stack-of-tasks/pinocchio/pull/1756#issuecomment-1263662535.

**Comment by jcarpent** [comment]
This is not really ideal, as a configuration vector has not necessarily a 1-to-1 mapping between config coordinate and tangent coordinate. I think you are mixing stuff here.
The way Pinocchio operates on Manifold seems appropriate as many other software already use it.
Thinking twice, we should not try to hack it.
It would be better to have a clear discussion on the way you proceed, and to think how the current API may work on your problem.
