### ISSUE TITLE
Segmentation Fault when importing pinocchio in python on M1 Mac

### ISSUE THREAD

**Issue by KaufmannDavid** [stack-of-tasks/pinocchio#1772]
Hey everyone, I'm trying to get a python program using pinocchio to run on my M1 mac. Unfortunately I always encounter a segmentation fault when trying to run the program. I'm using a conda environment and installed pinocchio through conda-forge. Every program importing pinocchio fails with the same fault. When running the program with a fault handler this stack is returned:
```
python -Xfaulthandler test.py
Fatal Python error: Segmentation fault

Current thread 0x0000000102dc4580 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1176 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/davidkaufmann/miniforge3/envs/test/lib/python3.10/site-packages/pinocchio/__init__.py", line 6 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/davidkaufmann/development/ba/test.py", line 1 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator (total: 13)
zsh: segmentation fault  python -Xfaulthandler test.py
```
The Programm executed just imports pinocchio and prints hello world: 
```
import pinocchio
import faulthandler
faulthandler.enable()

print("Hello World")
```
For the conda environment, I only installed python and pinocchio.
I'm new to this space so maybe I just did something terribly wrong, but a friend working on a different machine had no issues following this workflow. Do you have any ideas about what is going on?
If something remained unclear I am happy to clarify. Thanks a lot for any help.

**Comment by jcarpent** [comment]
Could you replace `import pinocchio`  by `import numpy`?
Could also try to install Pinocchio via brew?

@lmontaut Could you try it on your side?

**Comment by fabinsch** [comment]
@lmontaut is using Pinocchio on M1 by compiling eingenpy himself, otherwise he got also import errors in python.

**Comment by jcarpent** [comment]
Do you have the error?

**Comment by jcarpent** [comment]
There is an issue in the conda pipeline for ARM64 (https://github.com/conda-forge/hpp-fcl-feedstock/commit/b9bb331958b7c6716c1f8b241aa7f3c75584c1d1#annotation_4774332301). I've relaunched the binary generation.

**Comment by KaufmannDavid** [comment]
Thanks a lot for the quick replies. I tried it with `import numpy` and `import eigenpy`, both work fine. What is meant by "compiling eigenpy himself"?

**Comment by fabinsch** [comment]
It should mean compile from source. But actually it seems to be coming from a conda problem with hpp-fcl as @jcarpent mentioned in his last comment. 

Can you try to install pinocchio via brew?

**Comment by nim65s** [comment]
universal2 wheels are available on PyPI, so `pip install pin` might work on M1, but I didn't test yet.

As always, if anyone try this, please double and triple check that you have only one package manager for those packages, so boost+eigenpy+hpp-fcl+pinocchio by pip, and no brew / conda / custom builds / etc.

**Comment by jcarpent** [comment]
@traversaro It seems that we have an issue with conda on M1 arch.
Indeed, `conda install -c conda-forge hppfcl` works perfectly, but `python -c "import hppfcl"` fails with the following error:
```
zsh: bus error  python -c "import hppfcl"
```
Have you heard of such issue with conda on M1?

**Comment by jcarpent** [comment]
Thanks in advance @traversaro for your help.

**Comment by traversaro** [comment]
> @traversaro It seems that we have an issue with conda on M1 arch.
> Indeed, `conda install -c conda-forge hppfcl` works perfectly, but `python -c "import hppfcl"` fails with the following error:
> ```
> zsh: bus error  python -c "import hppfcl"
> ```
> Have you heard of such issue with conda on M1?

Could it be connected to the clang version/boost-python problem that was worked around by setting clang 13 around? Is hpp-fcl using boost-python. I do not have an M1 machine now, but just to check can you try on bash instead of zsh?

**Comment by traversaro** [comment]
Perhaps here:   https://github.com/conda-forge/hpp-fcl-feedstock/blob/main/recipe/conda_build_config.yaml#L2 we should not have  # [osx and x86_64] but just # [osx] ? Perhaps we just had the problem in ci with x86_64 as we do not test the import in M1 with CI

**Comment by jcarpent** [comment]
OK. I will try your suggestion. Thanks a lot @traversaro for the quick feedback.

**Comment by jcarpent** [comment]
It looks like the suggestion made by @traversaro works perfectly. Thanks to him for the very useful feedback.
@KaufmannDavid You should be able to do:
`conda install -c conda-forge pinocchio --force-reinstall`

**Comment by traversaro** [comment]
Great! Let's hope this is just a temporary problem, otherwise we may neeed to think a more robust solution.
