### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by FehlerNotFound** [stack-of-tasks/pinocchio#1803]
Hi,

when pulling latest modifications error occurs while `cmake` under build dir. Here is the output I got:
```
[cmake] CMake Error at src/CMakeLists.txt:35 (MODERNIZE_TARGET_LINK_LIBRARIES):
[cmake]   Unknown CMake command "MODERNIZE_TARGET_LINK_LIBRARIES".
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

Env: Ubuntu 18.04 LTS
cmake version: 3.16.6
Branch: master 
tag: v2.6.12

**Comment by jcarpent** [comment]
You should git submodule update —init

**Comment by FehlerNotFound** [comment]
> You should run git submodule update —init

Thanks for your quick feedback! problem sloved. 

Cheers
