### ISSUE TITLE
pinocchio3 does not display the model properly using the gepetto-viewer

### ISSUE THREAD

**Issue by MariaBana** [stack-of-tasks/pinocchio#1804]
Hello,
I successfully displayed the model using pinocchio2+gepetto-viewer, but the same program doesn't work in pinocchio3, reporting the error `Node does not exist.`. The gepetto-gui window only shows one axis and the body tree does not load properly.
```
libpng warning: iCCP: known incorrect sRGB profile
qt5ct: D-Bus global menu: no
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
Node "c_base_link_0" does not exist.
Node "c_shoulder_link_0" does not exist.
Node "c_upper_arm_link_0" does not exist.
Node "c_forearm_link_0" does not exist.
Node "c_wrist_1_link_0" does not exist.
Node "c_wrist_2_link_0" does not exist.
Node "c_wrist_3_link_0" does not exist.
Node "c_ee_link_0" does not exist.
Node "v_base_link_0" does not exist.
Node "v_shoulder_link_0" does not exist.
Node "v_upper_arm_link_0" does not exist.
Node "v_forearm_link_0" does not exist.
Node "v_wrist_1_link_0" does not exist.
Node "v_wrist_2_link_0" does not exist.
Node "v_wrist_3_link_0" does not exist.
```
![image](https://user-images.githubusercontent.com/117265115/206441760-70c3e023-6be0-4f9f-849e-ffe0932cb045.png)

At the same time, when I change the name of the dae file, my code using pinocchio2 reports the error `the mesh directory may be wrong.` But when I use pinocchio3, this will not happen.

What has changed in the load model section of pinocchio2 and pinocchio3 and how should I display the model with pinocchio3+gepetto-viewer?

I am using ubuntu 20.04. Gepetto-viewer, gepetto-viewer-corba and pinocchio-gepetto-viewer are the master branches, they are all installed from source.
Other than that, I installed libopenscenegraph-dev3.6.4 and libopenscenegraph160 3.6.4 from binary packages, and osg3.6.4 from source.

This question has been bothering me for a long time and I hope you can give me some guidance. 

https://github.com/Gepetto/gepetto-viewer/issues/205#issuecomment-1342261519

**Comment by jcarpent** [comment]
Dear @MariaBana 

From what you mentioned, it is hard to extract any useful feedback.
Could you provide a reproducing example? 
There is no change between Pinocchio 2 and 3 that might explain.

If I were you, I would use the MeshCat backend to display things.
I'm not investing time to support Gepetto-viewer.

**Comment by jcarpent** [comment]
Why do you work in C++, and why not in Python?

**Comment by jcarpent** [comment]
Did you properly setup the ROS_PACKAGE_PATH to point to the meshes?
Who is your advisor?

**Comment by MariaBana** [comment]
@jcarpent 
> Did you properly setup the ROS_PACKAGE_PATH to point to the meshes?

I make sure the path is ok. ( Otherwise pinocchio2 will not run properly
> Who is your advisor?

I am still in my undergraduate program and currently do not have a advisor.
>Why do you work in C++, and why not in Python?

I mainly did embedded development before, so I am more familiar with c++. And some famous robotics projects are also developed in c++ (such as mit cheetah), so I think it's better to develop in c++?
  

Is there any lightweight tool that can display the robot status while learning the pinocchio library? I know how to use Webots and Vrep, but I think that would introduce some uncertainty in the beginning. Thank you very much for your guidance.

**Comment by jcarpent** [comment]
On which commit are you working on?
@fabinsch Could you try on your side? I don't have Linux ;)

**Comment by jcarpent** [comment]
> I mainly did embedded development before, so I am more familiar with c++. And some famous robotics projects are also developed in c++ (such as mit cheetah), so I think it's better to develop in c++?
> 
> Is there any **lightweight** tool that can display the robot status while learning the pinocchio library? I know how to use Webots and Vrep, but I don't think it's convenient to use them in the beginner stage. Thank you very much for your guidance.

I would say that to dive into Pinocchio, the best way is to start with Python and to move to C++ only when it is necessary.
This will avoid you to be stuck with such kind of issues ;)

**Comment by MariaBana** [comment]
@jcarpent 
>On which commit are you working on?

I am now working alone on the control algorithm of the bipedal wheeled robot.
>I would say that to dive into Pinocchio, the best way is to start with Python and to move to C++ only when it is necessary.
This will avoid you to be stuck with such kind of issues ;)

Thank you very much, I will take your advice.

**Comment by jcarpent** [comment]
> I am now working alone on the control algorithm of the bipedal wheeled robot.

I meant for Pinocchio's side (related to Pinocchio 3.x).

**Comment by MariaBana** [comment]
> I meant for Pinocchio's side (related to Pinocchio 3.x).

The latest commit of the pinocchio3-preview branch.

**Comment by MariaBana** [comment]
I tried meshcat and rviz and found this problem pointless, thanks for your help!

**Comment by jcarpent** [comment]
Good news.
