### ISSUE TITLE
Hello, I encountered with following error code at the step of installing pinnochio

### ISSUE THREAD

**Issue by camelxpnu** [stack-of-tasks/pinocchio#1810]
I typed the following command in order to install,
`sudo apt install -qqy robotpkg-py27-pinocchio`

and got this message
`E: Unable to locate package robotpkg-py27-pinocchio`.

There is any package or program should I prepare preliminary?

**Comment by nim65s** [comment]
Hi,

Actually, we still support python 2.7, at least on 18.04, because our robots are stuck there…

What are your OS and version ? Did you add robotpkg in your apt lists ? Did you add robotpkg key to apt keys ? Did you run `apt update` afterwards ?
