### ISSUE TITLE
[Bugs] Problem with mprint() function in python bindings

### ISSUE THREAD

**Issue by cJamesSmith** [stack-of-tasks/pinocchio#1820]
I find that the latest pinocchio(2.6.12) has 2 bugs in mprint() function in python bindings:

1. https://github.com/stack-of-tasks/pinocchio/blob/master/bindings/python/pinocchio/utils.py#L85

```python
TypeError: object of type 'bool' has no len()
```

it should be 

```python
if len(M.shape)==1:
```

2. https://github.com/stack-of-tasks/pinocchio/blob/master/bindings/python/pinocchio/utils.py#L99

```python
TypeError: 'float' object cannot be interpreted as an integer
```

it should be

```python
for i in range((ncol - 1) // NC + 1):
```

**Comment by jcarpent** [comment]
Thanks a lot @cJamesSmith for looking at this issue.
I've just opened a PR #1821 solving your issue.
