### ISSUE TITLE
Documentation is still 2.6.12?

### ISSUE THREAD

**Issue by stephane-caron** [stack-of-tasks/pinocchio#1854]
See https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/

The CI did not update the docs automatically upon release?

**Comment by jcarpent** [comment]
This handle by LAAS via @nim65s. The update is not related to GitHub releases.

**Comment by nim65s** [comment]
It's fixed, thanks for the heads up !
