### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#187]
It seems that the coverage of the C++ code on Travis is failing. The coverage percentage is then not meaningful.

**Comment by jcarpent** [comment]
coverage increases a lot the compilation time, that might be boring mainly during development period. I would suggest to remove this feature from travis and only update the coverage status when making new release. 

What do you think so far?

**Comment by nim65s** [comment]
I also think that we only need automatic coverage for master and PR to master.

**Comment by nmansard** [comment]
Agreed. Who can handle this issue and implement the change?

**Comment by jcarpent** [comment]
Solved by #287.
