### ISSUE TITLE
Assertion `isUnitary(R.transpose()*R) && "R is not a Unitary matrix"' failed. When running the CRBA algorithm

### ISSUE THREAD

**Issue by juandavid212** [stack-of-tasks/pinocchio#1903]
Assertion `isUnitary(R.transpose()*R) && "R is not a Unitary matrix"' failed. When running the CRBA algorithm.

Hello,
I have checked the issues related to transforming the joint space to a configuration vector for robots with continuous joints.  The robot has 7 DoF with the following types [ JointModelRUBZ, JointModelRZ, JointModelRUBZ, JointModelRZ, JointModelRUBZ, JointModelRZ, JointModelRUBZ], so I'm obtaining my configuration vector (lq_) as:

    lq_[2] = q_[1];
    lq_[5] = q_[3];    
    lq_[8] = q_[5];    

    lq_[0] = cos(q_[0]);
    lq_[3] = cos(q_[2]);    
    lq_[6] = cos(q_[4]);    
    lq_[9] = cos(q_[6]);

    lq_[1] = sin(q_[0]);
    lq_[4] = sin(q_[2]);
    lq_[7] = sin(q_[4]);
    lq_[10] =sin(q_[6]);
where q_ is the joint values (joint_states, size=7).
After the conversion, I'm normalizing the configuration vector as:
pinocchio::normalize(model_,lq_);

And then, I run the CRBA algorithm as follows:
pinocchio::crba(model_,data_,lq_);

The code runs well for some time, but at particular robot's configurations, it stops and throws the error:

 /opt/ros/noetic/include/pinocchio/spatial/symmetric3.hpp:418: pinocchio::Symmetric3Tpl<Scalar, Options> pinocchio::Symmetric3Tpl<Scalar, Options>::rotate(const Eigen::MatrixBase<OtherDerived>&) const [with
 D = Eigen::Matrix<double, 3, 3>; _Scalar = double; int _Options = 0]: Assertion `isUnitary(R.transpose()*R) && "R is not a Unitary matrix"' failed.         

I appreciate your help in solving this issue.
Thanks.

**Comment by jcarpent** [comment]
Thanks for raising this issue.
Could you share a complete reproducible example to test on our own?

Best,
Justin

**Comment by jcarpent** [comment]
I will close this issue as there is no reply.
