### ISSUE TITLE
Issue reading URDF files in pybindings

### ISSUE THREAD

**Issue by kingjin94** [stack-of-tasks/pinocchio#1940]
This might be related to / was hidden by #1938.

At the moment it seems that pinocchio's python bindings are unable to load URDFs. The error is `AttributeError: module 'pinocchio.pinocchio_pywrap' has no attribute 'getNumpyType'`

A simple script to demonstrate (using timor-python as a source for a simple demo URDF; it installs pin alongside from pip):

```
docker run -ti python:3.10 bash
pip install timor-python
python
import pinocchio as pin
from timor.utilities.file_locations import robots
panda_urdf = robots['panda'].joinpath('urdf').joinpath('panda.urdf')
pin.RobotWrapper.BuildFromURDF(panda_urdf, panda_urdf.parent)
```

**Comment by kingjin94** [comment]
Even shorter:
```

docker run -ti python:3.10 bash
pip install pinocchio
python
import pinocchio as pin
pin.RobotWrapper.BuildFromURDF("notImportantFile.urdf", "/dummy/package/dir/")
```
 Will result in the same error.

**Comment by stephane-caron** [comment]
Running into the same issue in this workflow: https://github.com/tasts-robots/pink/actions/runs/4830671896/jobs/8607169482?pr=50

```
  AttributeError: module 'pinocchio.pinocchio_pywrap' has no attribute 'getNumpyType'
```

**Comment by fabinsch** [comment]
fix is on the way #1941

**Comment by jcarpent** [comment]
A new release in in the pipe and should be available via conda in few hours.

**Comment by jcarpent** [comment]
The release update is in the pipe: https://github.com/conda-forge/pinocchio-feedstock/pull/97
