### ISSUE TITLE
example cpp code with urdf parser won't compile

### ISSUE THREAD

**Issue by Cfather** [stack-of-tasks/pinocchio#1947]
Hi, 

I have just built pinocchio from source. My system is Ubuntu 22.04 and g++ 12.1.0. I tried to build the example codes (such as [forward-dynamics-derivatives.cpp](https://github.com/stack-of-tasks/pinocchio/blob/master/examples/forward-dynamics-derivatives.cpp)) with "pinocchio/parsers/urdf.hpp" inside and here is the error that I get:

```
/usr/bin/ld: /tmp/ccqHmhcG.o: in function `pinocchio::ModelTpl<double, 0, pinocchio::JointCollectionDefaultTpl>& pinocchio::urdf::buildModel<double, 0, pinocchio::JointCollectionDefaultTpl>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pinocchio::ModelTpl<double, 0, pinocchio::JointCollectionDefaultTpl>&, bool)':
test.cpp:(.text._ZN9pinocchio4urdf10buildModelIdLi0ENS_25JointCollectionDefaultTplEEERNS_8ModelTplIT_XT0_ET1_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_b[_ZN9pinocchio4urdf10buildModelIdLi0ENS_25JointCollectionDefaultTplEEERNS_8ModelTplIT_XT0_ET1_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_b]+0x5b): undefined reference to `pinocchio::urdf::details::parseRootTree(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pinocchio::urdf::details::UrdfVisitorBaseTpl<double, 0>&)'
collect2: error: ld returned 1 exit status
```

I wonder if someone could double-check this for me. I would appreciate it!

**Comment by jcarpent** [comment]
I guess you are not using the right compilation line:
```g++ -std=c++11  ./test.cpp -o test $(pkg-config --cflags --libs pinocchio)```
You need first to install Pinocchio and to export the PKG_CONFIG_PATH variable:
```
export PKG_CONFIG_PATH=$CONDA_PREFIX/lib/pkgconfig
```
where `CONDA_PREFIX` is the install PREFI
