### ISSUE TITLE
Apparent factor of 2 error in so3 logarithm for small rotations

### ISSUE THREAD

**Issue by GGooeytoe** [stack-of-tasks/pinocchio#1964]
In the file pinocchio/src/spatial/log.hxx  lines 61-63:
`const Scalar t = ((theta > TaylorSeriesExpansion<Scalar>::template precision<3>())
                          ? theta / sin(theta)
                          : Scalar(1)) / Scalar(2);`

If theta is small, theta/sin(theta) is approximately 1, not 1/2.

This scenario doesn't seem to be explicitly tested in the explog.cpp unit tests, which would explain how the typo was missed.

**Comment by jcarpent** [comment]
There are parentheses. The expression looks good to me.
If you are sure of your assertion, providing a numerical example to showcase the error will be nice.

Best,
Justin
