### ISSUE TITLE
CI failing with libboost_python38.so.1.81.0 not found

### ISSUE THREAD

**Issue by stephane-caron** [stack-of-tasks/pinocchio#1967]
Since yesterday we have observed the Pink CI failing with:

```
  File "/home/runner/work/pink/pink/pink/configuration.py", line 28, in <module>
    import pinocchio as pin
  File "/home/runner/work/pink/pink/.tox/coverage/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
ImportError: libboost_python38.so.1.81.0: cannot open shared object file: No such file or directory
```

The PyPI dependency configured in this test environment is ``pin >= 2.6.4``.

**Update:** reproduced this issue locally in a fresh conda environment. :point_down:

**Comment by stephane-caron** [comment]
This issue may be related to https://github.com/stack-of-tasks/pinocchio/issues/1960

**Comment by stephane-caron** [comment]
Timing-wise, this issue started happening yesterday:

![image](https://github.com/stack-of-tasks/pinocchio/assets/1189580/1f09f713-db9f-4a1d-948d-688c6a2aca83)

**Comment by nim65s** [comment]
This is the same issue: I'm rebuilding everything for boost 1.82

**Comment by jcarpent** [comment]
Close as duplicated with #1960.
