### ISSUE TITLE
Can we get a stable version of pinocchio?

### ISSUE THREAD

**Issue by JakobThumm** [stack-of-tasks/pinocchio#1989]
Hi,
first of all, thank you for developing and maintaining pinocchio!
Unfortunately, in my last year of using pinocchio, I repeatedly had broken pip packages because the dependencies are not fixed.

Currently, I'm trying to run `pin==2.6.14`, using this conda environment as an example
```
name: pin-test
channels:
  - conda-forge
dependencies:
  - pip>=22.0.4
  - python=3.8
  - setuptools==65.5.0
  - pip:
    - pin==2.6.14
```
which runs into 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jakob/anaconda3/envs/pin-test/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
ImportError: libboost_python38.so.1.81.0: cannot open shared object file: No such file or directory
```

This version worked for about 2 months and then broke. 
Would it be possible that we get one stable version of pinocchio and all its dependencies?

Thank you a lot!

**Comment by nim65s** [comment]
As you prefer, but I have to warn this kind of practices must not be used in places where security, safety or production is important :)
