### ISSUE TITLE
robotpkg: file has unexpected size in Docker

### ISSUE THREAD

**Issue by hannes56a** [stack-of-tasks/pinocchio#1992]
Hi all, i cant install pinocchio anymore. It worked some weeks ago.
I o/did it in a docker build, so Iḿ sure I did he same as last time...
can somebody help me?

Failed to fetch http://robotpkg.openrobots.org/packages/debian/pub/dists/focal/robotpkg/binary-amd64/robotpkg-py38-hpp-fcl_2.3.0_amd64.deb  File has unexpected size (830880 != 827128). Mirror sync in progress? [IP: 140.93.1.117 80]
   Hashes of expected file:
    - SHA512:524b9ad05cf123738252caab5aca37458b9e72a59af750d1b20e9e2b9f305f32be9313c2c0f11d5955f692a567bf22b9f039a0fdf5cbceea9250110b610a8a0f
    - SHA256:a5ee4b9f15058918394dfb8b267c0cf6f0b502bf937840008f75835c257925e2
    - SHA1:eca266c186aa0f40a55748ce85e41f9b5b161c21 [weak]
    - MD5Sum:08e56948167c3855313ce04e4b1da0c9 [weak]
    - Filesize:827128 [weak]

**Comment by nim65s** [comment]
Hi,

When using docker, please run your `apt update` and `apt install` in the same `RUN`, otherwise your apt cache and your docker build cache conflicts with each others.

Here is a working example:

```Dockerfile
FROM ubuntu:jammy

ADD --chmod=644 http://robotpkg.openrobots.org/packages/debian/robotpkg.gpg /robotpkg.gpg
RUN echo "deb [arch=amd64 signed-by=/robotpkg.gpg] http://robotpkg.openrobots.org/packages/debian/pub jammy robotpkg" >> /etc/apt/sources.list.d/robotpkg.list
RUN --mount=type=cache,sharing=locked,target=/var/cache/apt \
    --mount=type=cache,sharing=locked,target=/var/lib/apt \
    apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y  \
    robotpkg-py310-pinocchio
```

**Comment by nim65s** [comment]
I guess this is fixed. Please re-open if this is not the case.
