### ISSUE TITLE
CppAd & codegen test compilation failure

### ISSUE THREAD

**Issue by ghost** [stack-of-tasks/pinocchio#1999]
Pinocchio: 2.6.19
Boost: 1.78
Eigen: 3.3.7
same log for codegen test
Log:
>/home/harper/miniconda3/envs/my_env/include/boost/math/constants/constants.hpp: In instantiation of ‘constexpr typename boost::math::constants::detail::constant_return<Real, Policy>::type boost::math::constants::pi() [with T = CppAD::AD<double>; Policy = boost::math::policies::policy<boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy>; typename boost::math::constants::detail::constant_return<Real, Policy>::type = CppAD::AD<double>]’:
/home/harper/miniconda3/envs/my_env/include/boost/math/constants/constants.hpp:259:3:   required from ‘constexpr typename boost::math::constants::detail::constant_return<T>::type boost::math::constants::pi() [with T = CppAD::AD<double>; typename boost::math::constants::detail::constant_return<T>::type = CppAD::AD<double>]’
/home/harper/Apps/pinocchio/build/include/pinocchio/math/fwd.hpp:27:46:   required from ‘const Scalar pinocchio::PI() [with Scalar = CppAD::AD<double>]’
/home/harper/Apps/pinocchio/build/include/pinocchio/multibody/liegroup/special-orthogonal.hpp:65:48:   required from ‘static typename Matrix2Like::Scalar pinocchio::SpecialOrthogonalOperationTpl<2, _Scalar, _Options>::log(const Eigen::MatrixBase<OtherDerived>&) [with Matrix2Like = Eigen::Matrix<CppAD::AD<double>, 2, 2, 0, 2, 2>; _Scalar = CppAD::AD<double>; int _Options = 0; typename Matrix2Like::Scalar = CppAD::AD<double>]’
/home/harper/Apps/pinocchio/build/include/pinocchio/multibody/liegroup/special-orthogonal.hpp:142:55:   required from ‘static void pinocchio::SpecialOrthogonalOperationTpl<2, _Scalar, _Options>::difference_impl(const Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<ScaleDerived>&) [with ConfigL_t = Eigen::Block<const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, 2, 1, false>; ConfigR_t = Eigen::Block<const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, 2, 1, false>; Tangent_t = Eigen::Block<Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, 1, 1, false>; _Scalar = CppAD::AD<double>; int _Options = 0]’
/home/harper/Apps/pinocchio/build/include/pinocchio/multibody/liegroup/liegroup-base.hxx:375:5:   required from ‘void pinocchio::LieGroupBase<Derived>::difference(const Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<OtherDerived>&, const Eigen::MatrixBase<ScaleDerived>&) const [with ConfigL_t = Eigen::Block<const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, 2, 1, false>; ConfigR_t = Eigen::Block<const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, 2, 1, false>; Tangent_t = Eigen::Block<Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, 1, 1, false>; Derived = pinocchio::SpecialOrthogonalOperationTpl<2, CppAD::AD<double>, 0>]’
/home/harper/Apps/pinocchio/build/include/pinocchio/multibody/liegroup/liegroup-algo.hxx:374:7:   [ skipping 9 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/home/harper/miniconda3/envs/my_env/include/boost/variant/variant.hpp:2404:52:   required from ‘typename Visitor::result_type boost::variant<T0, TN>::apply_visitor(Visitor&) const & [with Visitor = pinocchio::fusion::JointUnaryVisitorBase<pinocchio::DifferenceStep<pinocchio::LieGroupMap, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1> >, void>::InternalVisitorModel<boost::fusion::vector<const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>&, const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>&, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>&>, void>; T0_ = pinocchio::JointModelRevoluteTpl<CppAD::AD<double>, 0, 0>; TN = {pinocchio::JointModelRevoluteTpl<CppAD::AD<double>, 0, 1>, pinocchio::JointModelRevoluteTpl<CppAD::AD<double>, 0, 2>, pinocchio::JointModelMimic<pinocchio::JointModelRevoluteTpl<CppAD::AD<double>, 0, 0> >, pinocchio::JointModelMimic<pinocchio::JointModelRevoluteTpl<CppAD::AD<double>, 0, 1> >, pinocchio::JointModelMimic<pinocchio::JointModelRevoluteTpl<CppAD::AD<double>, 0, 2> >, pinocchio::JointModelFreeFlyerTpl<CppAD::AD<double>, 0>, pinocchio::JointModelPlanarTpl<CppAD::AD<double>, 0>, pinocchio::JointModelRevoluteUnalignedTpl<CppAD::AD<double>, 0>, pinocchio::JointModelSphericalTpl<CppAD::AD<double>, 0>, pinocchio::JointModelSphericalZYXTpl<CppAD::AD<double>, 0>, pinocchio::JointModelPrismaticTpl<CppAD::AD<double>, 0, 0>, pinocchio::JointModelPrismaticTpl<CppAD::AD<double>, 0, 1>, pinocchio::JointModelPrismaticTpl<CppAD::AD<double>, 0, 2>, pinocchio::JointModelPrismaticUnalignedTpl<CppAD::AD<double>, 0>, pinocchio::JointModelTranslationTpl<CppAD::AD<double>, 0>, pinocchio::JointModelRevoluteUnboundedTpl<CppAD::AD<double>, 0, 0>, pinocchio::JointModelRevoluteUnboundedTpl<CppAD::AD<double>, 0, 1>, pinocchio::JointModelRevoluteUnboundedTpl<CppAD::AD<double>, 0, 2>, pinocchio::JointModelRevoluteUnboundedUnalignedTpl<CppAD::AD<double>, 0>, boost::recursive_wrapper<pinocchio::JointModelCompositeTpl<CppAD::AD<double>, 0, pinocchio::JointCollectionDefaultTpl> >}; typename Visitor::result_type = void]’
/home/harper/miniconda3/envs/my_env/include/boost/variant/detail/apply_visitor_unary.hpp:48:72:   required from ‘typename Visitor::result_type boost::apply_visitor(Visitor&, Visitable&&) [with Visitor = pinocchio::fusion::JointUnaryVisitorBase<pinocchio::DifferenceStep<pinocchio::LieGroupMap, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1> >, void>::InternalVisitorModel<boost::fusion::vector<const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>&, const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>&, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>&>, void>; Visitable = const pinocchio::JointModelTpl<CppAD::AD<double>, 0, pinocchio::JointCollectionDefaultTpl>&; typename Visitor::result_type = void]’
/home/harper/Apps/pinocchio/build/include/pinocchio/multibody/visitor/joint-unary-visitor.hpp:69:36:   required from ‘static ReturnType pinocchio::fusion::JointUnaryVisitorBase<JointVisitorDerived, ReturnType>::run(const pinocchio::JointModelTpl<Scalar, Options, JointCollectionTpl>&, ArgsTmp) [with Scalar = CppAD::AD<double>; int Options = 0; JointCollectionTpl = pinocchio::JointCollectionDefaultTpl; ArgsTmp = boost::fusion::vector<const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>&, const Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>&, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>&>; JointVisitorDerived = pinocchio::DifferenceStep<pinocchio::LieGroupMap, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>, Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1> >; ReturnType = void]’
/home/harper/Apps/pinocchio/build/include/pinocchio/algorithm/joint-configuration.hxx:83:16:   required from ‘void pinocchio::difference(const pinocchio::ModelTpl<Scalar, Options, JointCollectionTpl>&, const Eigen::MatrixBase<MatRet>&, const Eigen::MatrixBase<TangentVectorType>&, const Eigen::MatrixBase<ReturnType>&) [with LieGroup_t = pinocchio::LieGroupMap; Scalar = CppAD::AD<double>; int Options = 0; JointCollectionTpl = pinocchio::JointCollectionDefaultTpl; ConfigVectorIn1 = Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>; ConfigVectorIn2 = Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>; ReturnType = Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>]’
/home/harper/Apps/pinocchio/build/include/pinocchio/algorithm/joint-configuration.hpp:147:105:   required from ‘void pinocchio::difference(const pinocchio::ModelTpl<Scalar, Options, JointCollectionTpl>&, const Eigen::MatrixBase<Matrix3Like>&, const Eigen::MatrixBase<MatRet>&, const Eigen::MatrixBase<TangentVectorType>&) [with Scalar = CppAD::AD<double>; int Options = 0; JointCollectionTpl = pinocchio::JointCollectionDefaultTpl; ConfigVectorIn1 = Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>; ConfigVectorIn2 = Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>; ReturnType = Eigen::Matrix<CppAD::AD<double>, -1, 1, 0, -1, 1>]’
/home/harper/Apps/pinocchio/unittest/cppad-joint-configurations.cpp:86:52:   required from here
/home/harper/miniconda3/envs/my_env/include/boost/math/constants/constants.hpp:259:3: error: no matching function for call to ‘boost::math::constants::detail::constant_pi<CppAD::AD<double> >::get(boost::math::constants::construction_traits<CppAD::AD<double>, boost::math::policies::policy<boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy> >::type)’
  259 |   BOOST_DEFINE_MATH_CONSTANT(pi, 3.141592653589793238462643383279502884e+00, "3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651e+00")
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/harper/Apps/pinocchio/build/include/pinocchio/autodiff/cppad.hpp:35:34: note:   template argument deduction/substitution failed:
In file included from /home/harper/Apps/pinocchio/build/include/pinocchio/math/fwd.hpp:10,
                 from /home/harper/Apps/pinocchio/build/include/pinocchio/autodiff/cppad.hpp:8,
                 from /home/harper/Apps/pinocchio/unittest/cppad-joint-configurations.cpp:5:
/home/harper/miniconda3/envs/my_env/include/boost/math/constants/constants.hpp:259:3: note:   ‘boost::math::constants::construction_traits<CppAD::AD<double>, boost::math::policies::policy<boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy> >::type’ {aka ‘std::integral_constant<int, 0>’} is not derived from ‘const mpl_::int_<N>’
  259 |   BOOST_DEFINE_MATH_CONSTANT(pi, 3.141592653589793238462643383279502884e+00, "3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651e+00")
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jcarpent** [comment]
From the given input, it is hard to reproduce your issue. @xeonz1 Could you provide a way to reproduce it?

**Comment by jcarpent** [comment]
I could not reproduce this issue locally on my machine with Boost 1.78 and Eigen 3.4.0.
@xeonz1 I suggest you provide a docker image that reproduces your issue.

**Comment by jcarpent** [comment]
Finally, I've been able to reproduce your issues. @xeonz1 a fix is being now tested in #2000.
