### ISSUE TITLE
pinocchio::sdf::buildModel error

### ISSUE THREAD

**Issue by areofire** [stack-of-tasks/pinocchio#2005]
I'm using pinocchio3-preview and trying to load a robot model with function "pinocchio::sdf::buildModel" .

Part of my code is:   
  Model model;
  pinocchio::urdf::buildModel(urdf_filename,model);
  PINOCCHIO_STD_VECTOR_WITH_EIGEN_ALLOCATOR(RigidConstraintModel) contact_models;
  pinocchio::sdf::buildModel(urdf_filename,model,contact_models);

But a segmentation fault come out in parseRootTree， const std::string childName=
       jotingElement->GetElement("child")->Get<std::string>();;

Maybe i miss something or the model i used is not correct, I  tried the model from here:
[models.zip](https://github.com/stack-of-tasks/pinocchio/files/10475001/models.zip), from #1839;
and here:
https://github.com/osrf/gazebo_tutorials/tree/master/kinematic_loop/four_bar_split_fixed_sdf/model.sdf

Both of them come out the same error above.

Is there a example of sdf model?

Many thanks

**Comment by jcarpent** [comment]
Please provide a reproducible example and the way to compile and launch it.

**Comment by areofire** [comment]
[pin_c_test_.zip](https://github.com/stack-of-tasks/pinocchio/files/11925608/pin_c_test_.zip)
cd build
cmake ..
make

**Comment by jcarpent** [comment]
@areofire Did you find a fix for your issue?

**Comment by areofire** [comment]
Not yet. I have spend much time on installing pin-view3, but all failed. As in example above, to use pinnocchio3, i have to include relevant  file in my project. 

I got  a pinocchio::sdf::buildModel error and  still working on fixing it.

**Comment by areofire** [comment]
Maybe the model i used is wrong, there wasn't a "static " parameter in graph.mapOfJoints. 
![debug](https://github.com/stack-of-tasks/pinocchio/assets/28983641/77debc8e-e727-4c40-9ed5-211ad46386ea)

**Comment by areofire** [comment]
Could you give an example of sdf file, thank you !

**Comment by areofire** [comment]
@jcarpent
