### ISSUE TITLE
issue with API getJacobianComFromCrba, no attribute 'getJacobianComFromCrba'

### ISSUE THREAD

**Issue by Zlsy32900** [stack-of-tasks/pinocchio#2011]
Hello, thank you for your impressive library. However, I've recently encountered an issue when attempting to use the 'getJacobianComFromCrba' API for a legged robot. The error message I receive is "AttributeError: module 'pinocchio' has no attribute 'getJacobianComFromCrba' ".

At first, I thought it might be due to my installing the library from robotpkg and perhaps certain APIs were omitted in that process. So, I also attempted installation from the source, but the same error persists. I would appreciate any guidance on resolving this error, or suggestions on possible alternate APIs that I could utilize instead.

a simple python case:
`In [1]: import pinocchio
In [2]: pinocchio.getJacobianComFromCrba

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 pinocchio.getJacobianComFromCrba

AttributeError: module 'pinocchio' has no attribute 'getJacobianComFromCrba'
`
Ubuntu 20.04.6
python 3.8
Eigenpy 2.9.2

**Comment by jcarpent** [comment]
This function is not exposed yet in Python.
In the meantime, you can use:
```python
pin.jacobianCenterOfMass(model,data,q)
```
