### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by bhtxy0525** [stack-of-tasks/pinocchio#2033]
![1691803913164](https://github.com/stack-of-tasks/pinocchio/assets/38209541/8f21af7d-d26d-4194-8a96-af1198c3f3d1)

I would like to install Pinocchio by the source form, but get the error during the "make" process, as shown in the above figure. Can you help me address this issue?

Thank you very much!

**Comment by jcarpent** [comment]
Please provide a reproducing docker file.

**Comment by bhtxy0525** [comment]
Thanks for your reply， but I don't quite understand what you mean. How should I do it? what is the reproducing docker file？where can i get it？

**Comment by jcarpent** [comment]
Could create a docker script which reproduces your issue ?
