### ISSUE TITLE
[Spatial.8] Change SE3Action to SE3ActOn and unify the naming

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#204]
Change the names SE3Action and SE3ActionInv (sometime suffixed by _impl) by SE3ActOn and SE3InvActOn.

**Comment by nmansard** [comment]
This is quite transparent for users, as they typically use this method through se3.act. I have no strong opinion. 

As it is not a major issue, I would advice to stick to the current naming (se3Action) and close this issue. Any disagreement?

**Comment by jcarpent** [comment]
For this suggestion, I think the use of SE3ActOn is relevant as it conforms with other method naming (addTo, setTo, evalTp, subTo, etc).

**Comment by jcarpent** [comment]
This has been solved in Pinocchio 2.0.0
