### ISSUE TITLE
log6 operator causes compilation error for pinocchio::SE3Tpl<casadi::SX> 

### ISSUE THREAD

**Issue by modu-robotics** [stack-of-tasks/pinocchio#2049]
## Bug description

Hello, I am trying to use `log6` operator with casadi symbolic variable.
As a part of computation, I am running the following code
```
  pinocchio::SE3Tpl<casadi::SX> oMi;
  pinocchio::log6(oMi);
```
But, the code isn't compiled with the following error:
```
pinocchio/spatial/log.hxx:57:20: error: no viable conversion from 'casadi::Matrix<casadi::SXElem>' to 'bool'
        res_(2) = (R (1, 0) > R (0, 1) ? Scalar(1) : Scalar(-1)) * (tmp[2] > Scalar(0) ? sqrt(tmp[2]) : Scalar(0));
```

This seems to be relevant to https://github.com/stack-of-tasks/pinocchio/pull/1156, but for `log6` operator.

## Expected behavior

The code is compiled without error.

### System

- OS: Mac
- Pinocchio version: Installed via Homebrew.

**Comment by jcarpent** [comment]
This is expected as not all the code on the master and devel branch is compatible with type overloading.
Instead, you switch to this [branch](https://github.com/stack-of-tasks/pinocchio/tree/pinocchio3-preview).
