### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#207]
For future, we must be compatible with Python 3, as Python 2 seems to be supported until 2020.

**Comment by jcarpent** [comment]
The first things to do is to replace the Python 2 functions which will be deprecated in Python 3.
Then, we have to be sure that the binding with boost python is fully compatible with Python3.

**Comment by jcarpent** [comment]
I checked and normally everything seems to work with Python3. The only requirement is to have boost-python built against python3.

**Comment by aelkhour** [comment]
:+1: Thanks for investigating this.
