### ISSUE TITLE
Remove dependancy on parsers from model

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#210]
geometry.hpp should not depend on SRDF. Remove the corresponding code a put it in parsers/srdf.hpp.

**Comment by jcarpent** [comment]
Where is exactly the problem?

**Comment by nmansard** [comment]
Line 30 of geometry.hxx, and consequently line 557 of geometry.hpp (and 
the corresponding implementation in the hxx).

**Comment by nmansard** [comment]
Solved by #227
