### ISSUE TITLE
VS shows as not installed and fails on doing so

### ISSUE THREAD

**Issue by pkornau** [stack-of-tasks/pinocchio#2128]
Hi community, 

I encounter a bug I can't solve myself yet. I am stuck because it always says my VS wouldn't be installed, even if the installer always ends successfully. 

## Bug description

Instead of finalizing the vs installs after I saw the VS Installing window finishing successfully it pops up with an error: 

Error
Error: Command failed: start /wait C:\Users\rubir\pinokio\bin\vs_buildtools.exe --passive --wait --includeRecommended --nocache --add Microsoft.VisualStudio.Workload.VCTools at C:\Users\rubir\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\sudo-prompt-programfiles-x86\index.js:577:25 at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

## Reproduction steps

1. Go to Discovery Page
2. Choose Repo ('Fooocus' in my case as I also use it locally in another env)
3. See that VS appears to not to be installed
4. Click Install 
5. See error

## Additional context

Pinokio 1.0.15 & Pinokio 1.0.16 
( I didn't try any earlier version yet) 

### Screenshots
![grafik](https://github.com/stack-of-tasks/pinocchio/assets/134508191/e9fff30a-0804-4e2d-ae05-7eadd5d8af8b)

![grafik](https://github.com/stack-of-tasks/pinocchio/assets/134508191/39a0a317-b37b-4bb4-8cfc-2dc28a69e555)

### System

Edition	Windows 11 Pro
Version	22H2
Installed   06.‎10.‎2022
OS-Build	22621.674
Windows Feature Experience Pack 1000.22634.1000.0

AMD Ryzen 5 5500                                  3.60 GHz
RAM	16,0 GB (15,8 GB verwendbar)
64-Bit-Betriebssystem, x64-basierter Prozessor
RTX 3060 (12GB)

Thanks in advance for help solving this <3

**Comment by nim65s** [comment]
Hi @pkornau,

I'm afraid this is the wrong project. You're looking for https://github.com/pinokiocomputer/pinokio, not pinocchio.
