### ISSUE TITLE
Change se3 namespace into pinocchio

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#215]
The namespace se3 is ambiguous and need to be relevant for the project. I suggest to rename it in pinocchio.

**Comment by nmansard** [comment]
Fair enough. 

Should we keep se3 as a sub namespace for the spatial module (::pinocchio::se3) ?

**Comment by jcarpent** [comment]
To be more generic, we can also use ::pinocchio::spatial for the spatial module.

**Comment by fvalenza** [comment]
+1 for ::pinocchio::spatial (no confusion with SE3 ( i remember some people of the team asking me if it was the same).

**Comment by olivier-stasse** [comment]
+1 for ::pinocchio::spatial

**Comment by jmirabel** [comment]
+1 for ::pinocchio::spatial

**Comment by nmansard** [comment]
I recently worked a lot with a third-party lib and came to quite love the short se3:: namespace. I think we should keep it.

**Comment by jcarpent** [comment]
I do not think so. The replacement is easy in the few related projects. 
The namespace se3 is not clear at all.

**Comment by jcarpent** [comment]
ping! hpp-devel branch is now merged into the devel branch. It seems that Pinocchio will be quite soon merged into HPP. I suggest to change the global namespace se3 into pinocchio(or pin which is shorter). Any remarks?

**Comment by jcarpent** [comment]
I'm going to address this issue in the very next weeks.
The idea is to replace `namespace se3`by `namespace pinocchio` and to add a shortcut to `pinocchio`namespace with `se3` nickname.

**Comment by jcarpent** [comment]
Solved by #588.
