### ISSUE TITLE
Call non-static member function isNormalized() in static function integrate_impl()

### ISSUE THREAD

**Issue by camfly-zlf** [stack-of-tasks/pinocchio#2154]
pinocchio/include/pinocchio/multibody/liegroup/special-orthogonal.hpp:179
assert (isNormalized(out));

isNormalized() is a non-static member function, I can't build with msvc unless comment out this line

**Comment by jcarpent** [comment]
It seems you are compiling in Debug mode (meaning with degraded performances)

**Comment by jorisv** [comment]
@camfly-zlf I can reproduce your issue and I will fix it

**Comment by camfly-zlf** [comment]
> It seems you are compiling in Debug mode (meaning with degraded performances)

yes, I will rebuild it in release mode later

**Comment by jorisv** [comment]
Fixed in #2155
