### ISSUE TITLE
VS Tools installation bug

### ISSUE THREAD

**Issue by Punsihmentor** [stack-of-tasks/pinocchio#2157]
## Bug description

When I try to install Stable Cascade, I open a window for stable Cascade in Pinokio, and then click the download button. After that, I see the window with the installation requirereds and click install. After that, it started to install all the components in new window that were needed but on the last component VS tools it just did not work, I tried to install it multiple times, and in the installation window it showed that the installation succeeded, but then when I click ok I see again windows with all needed components and down there I see VS - Not installed.

## Reproduction steps

1. Load to stable cascade
2. Click on download
3. Scroll down to  install

### Screenshots
![Screenshot_3](https://github.com/stack-of-tasks/pinocchio/assets/11591195/79e7dc69-b0e1-4610-8f28-a2e083a14c88)
![Screenshot_4](https://github.com/stack-of-tasks/pinocchio/assets/11591195/0bec53d4-2a80-422e-9bc6-b0c630172aca)

### System

- OS: Windows 11
- Pinocchio version:1.10

**Comment by fabinsch** [comment]
Hi @Punsihmentor, I think this here is the wrong repo. Maybe you are looking for: https://github.com/pinokiocomputer/pinokio ?

**Comment by Rhanderguimararaes** [comment]
It seems like it's a permission issue, but how to allow
