### ISSUE TITLE
ImportError: cannot import name 'casadi' from 'pinocchio'

### ISSUE THREAD

**Issue by lrchit** [stack-of-tasks/pinocchio#2159]
## Bug description

I'm doing nmpc with casadi and acados. Recently I need some dynamics to build a model, such as  Centroid dynamics. So I tried to bind pinocchio with casadi using python. When I did cmake and make, everything went well. But when I tried python, something was wrong. 
After everything was installed, I ran python3 and tried "from pinocchio import casadi", at which errors occured as followings:
![image](https://github.com/stack-of-tasks/pinocchio/assets/81569049/02c9b17f-3e02-4ba0-a3c2-8362b501c007)

![image](https://github.com/stack-of-tasks/pinocchio/assets/81569049/388c8854-f7c1-4542-be4d-70695ee467b1) 

### Code

Considering something needs eigenpy 2.7.10, I installed it in advanced.
I used following steps to build pinocchio with a virtual environment:

```
virtualenv env --python=/usr/bin/python3
source env/bin/activate
pip install cmake casadi compilers
pip install pinocchio
cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_WITH_CASADI_SUPPORT=ON
sudo make install
```
I tested pinocchio with my previous C++ project and that did well. As there was nothing wrong when compiling, so I don't know how to solve this. 
Is there anything wrong with the virtual environment or cmake procedure? Thanks in advance!

### System

- OS: ubuntu20.04
- Pinocchio version: pinocchio-preview3

**Comment by jcarpent** [comment]
You can install pinocchio3 preview with modern features via conda directly.
I recommend using the procedure detailed here: https://github.com/agimus-project/winter-school-2023/tree/main/simulation/sim1_rigid_body

Best,
Justin

**Comment by lrchit** [comment]
> You can install pinocchio3 preview with modern features via conda directly. I recommend using the procedure detailed here: https://github.com/agimus-project/winter-school-2023/tree/main/simulation/sim1_rigid_body
> 
> Best, Justin

> Thanks a lot for reply. I followed https://github.com/agimus-project/winter-school-2023/tree/main/simulation/sim1_rigid_body just now with conda, but overcome the same error:
![image](https://github.com/stack-of-tasks/pinocchio/assets/81569049/ae12ddc0-103c-42e4-af53-fab1c83bbf55)

> I guess maybe this is caused by the python version? I use python3.8. Looking forward to your reply. Thanks again.
> Best wishes!

**Comment by lrchit** [comment]
> You can install pinocchio3 preview with modern features via conda directly. I recommend using the procedure detailed here: https://github.com/agimus-project/winter-school-2023/tree/main/simulation/sim1_rigid_body
> 
> Best, Justin

Dear Justin, 
I followed https://github.com/agimus-project/winter-school-2023/tree/main/simulation/sim1_rigid_body. At first time, I used python3.8 and it turned out the same error. And I thus tried python3.10, and it made it! Thanks a lot for your kindness!

Cheers!
Lrc
