### ISSUE TITLE
Add arm64 macOS wheels to releases

### ISSUE THREAD

**Issue by devbanu** [stack-of-tasks/pinocchio#2165]
Currently installing Pinocchio via pip on arm64 macOS, i.e. on modern Macs, takes a significant amount of time 10-20minutes depending on platform.

This problems is easily solved by enabling the creation of arm64 wheels in the release workflow.

I have created a PR that solves this problem here: https://github.com/cmake-wheel/pinocchio/pull/8

Note that the PR is under `cmake-wheel/pinocchio` because it contains the `release.yml` file which is not available in `stack-of-tasks/pinocchio`.

I am creating this issue as a way to inform you about this.

**Comment by jcarpent** [comment]
Sounds perfect to us! Very nice initiative @devbanu. Thanks a lot for your helpful contribution

**Comment by cmastalli** [comment]
Hi @nim65s and @devbanu 

Thanks for your contribution. Would you be willing to do the same for Crocoddyl? Your support would be much appreciated by many users :)

**Comment by devbanu** [comment]
I will let @nim65s confirm, as he is more informed.

But it seems to me Crocoddyl's latest release (2.0.2 from Dec 7) already does provide arm64 macOS wheels.
