### ISSUE TITLE
Seek for COM Matrix

### ISSUE THREAD

**Issue by Mr-Red331** [stack-of-tasks/pinocchio#2176]
Hi,

Thanks for providing such a great dynamic library!

I am seeking a linear form of calculating Center of Mass, which can be expressed as:

`Com = qM` 

where `Com` means the Center of Mass of a robot, `q` means the joint position, and `M` is the Matrix I am seeking for.

I have checked the Pinocchio's manual but couldn't find it. I wonder if Pinocchio could provide such a matrix.

**Comment by jcarpent** [comment]
Please see the cheat sheet: https://github.com/stack-of-tasks/pinocchio/blob/master/doc/pinocchio_cheat_sheet.pdf
