### ISSUE TITLE
AttributeError: module 'pinocchio' has no attribute 'buildModelFromUrdf'

### ISSUE THREAD

**Issue by RitishShailly** [stack-of-tasks/pinocchio#2180]
Is 'buildModelFromUrdf' feature deprecated? If so, are there any alternatives I can use?

I am using this code:

```
import pinocchio as pin
import numpy as np

model = pin.buildModelFromUrdf('~/home/rshailly/Documents/ur10_urdf.urdf')
data = model.createData()

# Specify joint configuration
q = pin.neutral(model)

# Compute Jacobian at the end-effector
frame_id = model.getFrameId('tool0')  # Adjust as needed
J = pin.computeFrameJacobian(model, data, q, frame_id)

# Compute pseudo-inverse of Jacobian
pseudo_inverse_J = np.linalg.pinv(J)

```

and I am getting this error:
![image](https://github.com/stack-of-tasks/pinocchio/assets/85962862/6716b013-c9a3-4f41-89af-ca49ddc69d22)

**Comment by fabinsch** [comment]
Hi @RitishShailly , this function should be available. How did you install pinocchio and which version do you have now ? 

You could maybe check your conda or pip list or just do in python: `import pinocchio; pinocchio.__version__`
