### ISSUE TITLE
How to model robot with float-base

### ISSUE THREAD

**Issue by LIUHAITAO-CH** [stack-of-tasks/pinocchio#2182]
i want to know how to modeling the mobile manipulator with float-base,as shown below

<img width="595" alt="image" src="https://github.com/stack-of-tasks/pinocchio/assets/64388319/98c28209-3e94-4abe-a714-18efd44b7edd">

I can model the manipulator with traditional method,but i don't konw how to model the mobile . i would like to learn how pinocchio handles this kind of problem？

**Comment by jcarpent** [comment]
FOr the mobile platform, you can use PlanarJoint to work with X and Y translations and one rotation around the vertical axis.
Best,
Justin
