### ISSUE TITLE
Algo: optional update kinematics in jacobian com 

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#219]
The center-of-mass algorithms enable a "upadteKinematics" flags to spare computations, but the algorithm of the corresponding jacobian.

The same flag should be added. The resulting function signature should be:
const Data::Matrix3x & jacobianCenterOfMass(const Model & model, Data & data,
                       const Eigen::VectorXd & q,
                       const bool computeSubtreeComs,
                       const bool updateKinematics )

**Comment by jcarpent** [comment]
Solved by #222.
