### ISSUE TITLE
Missing release tarball for v1.1.2 

### ISSUE THREAD

**Issue by aelkhour** [stack-of-tasks/pinocchio#223]
v1.1.0 has [a release tarball](https://github.com/stack-of-tasks/pinocchio/releases/download/v1.1.0/pinocchio-1.1.0.tar.gz) which is packaged with submodules.

This does not seem to be the case for v1.1.2.

**Comment by jcarpent** [comment]
They are in fact stored on http://robotpkg.openrobots.org/distfiles/. As _robotpkg_ is the release binary builders of Pinocchio and its dependencies. See the install procedure https://github.com/stack-of-tasks/pinocchio/wiki/Installation for more details.

**Comment by jcarpent** [comment]
I will add the release tar.gz.

**Comment by jcarpent** [comment]
It is now done. I'll close the issue.

**Comment by aelkhour** [comment]
Thanks @jcarpent.
