### ISSUE TITLE
Ros related compatibility issues

### ISSUE THREAD

**Issue by fangnan99** [stack-of-tasks/pinocchio#2230]
I've been using pinocchio with ros and there seems to be compatibility issues between different releases.

I have installed the python bindings of Pinocchio from pip, and the C++ bindings from ros (i.e. `apt install ros-noetic-pinocchio`).
However, if I then run a python ros node that uses Pinocchio I get segmentation faults. This was not happening last year though
After looking into the problem I found that
* When I did pip install, the libraries hpp-fcl and eigenpy are installed in the dist-packages directory, including .so files and python wrappers.
* When I install from ros, another copy of .so files were installed in /opt/ros/noetic/lib/x86_64-linux-gnu with cpp headers in the ros include directories. Since the ros release of `eigenpy`, `hpp-fcl`, and `pinocchio` have not been updated since a few months, I get an older version of them.
* When I source the ros setup.bash, the ros lib directory is added to LD_LIBRARY_PATH. Then when I import Pinocchio in a python script, it finds the .so libraries in the ros lib folder and leads to errors.

I could confirm this by removing /opt/ros/noetic/lib/x86_64-linux-gnu from LD_LIBRARY_PATH and the issue is solved. This is, however, not a good solution because there could be cases when the ros library is required.
Therefore, I wonder what is the best practice for using Pinocchio with ros in both python and cpp. Should I compile from source?

**Comment by jcarpent** [comment]
You cannot install pinocchio from apt and use the one in pip together.
You should isolate your different installations to be able to properly have several Pinocchio installed on your OS.

For Python usage, you can easily isolate your system using conda for instance.
