### ISSUE TITLE
undefined reference to `boost::filesystem::detail::path_algorithms::find_root_directory`

### ISSUE THREAD

**Issue by ZijianWu1121** [stack-of-tasks/pinocchio#2237]
## Bug description

cannot build the project in ubuntu20.04

## Reproduction steps
I follow the installation step and when I use make, it returns the erros

/usr/bin/ld: ../src/libpinocchio.so.2.7.1: undefined reference to `boost::filesystem::detail::path_algorithms::append_v3(boost::filesystem::path&, char const*, char const*)'
/usr/bin/ld: ../src/libpinocchio.so.2.7.1: undefined reference to `boost::filesystem::detail::path_algorithms::find_root_directory(boost::filesystem::path const&)'
/usr/bin/ld: ../bindings/python/pinocchio/pinocchio_pywrap.cpython-38-x86_64-linux-gnu.so.2.7.1: undefined reference to `boost::python::instance_holder::allocate(_object*, unsigned long, unsigned long, unsigned long)'
collect2: error: ld returned 1 exit status
make[2]: *** [unittest/CMakeFiles/test-cpp-python_parser.dir/build.make:99: unittest/test-cpp-python_parser] Error 1
make[2]: Leaving directory '/home/ubuntu/hand/pinocchio/build'
make[1]: *** [CMakeFiles/Makefile2:2076: unittest/CMakeFiles/test-cpp-python_parser.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/hand/pinocchio/build'
make: *** [Makefile:144: all] Error 2

### System

- OS: Ubuntu20.04
- Pinocchio version: master branch

i use the command dpkg -S /usr/include/boost/version.hpp and check the boost version of my system
libboost1.71-dev:amd64: /usr/include/boost/version.hpp

**Comment by nim65s** [comment]
Can you provide the output of the `env` command ?

**Comment by nim65s** [comment]
You have conda in there, and it is possible that conda provide another boost version somewhere.

You must choose either
1. using conda (and in this case you should not have things finding `/usr/include/boost`)
2. not using conda ( and in this case, you should not have anything with "conda" in this `env` output)

**Comment by abussy-aldebaran** [comment]
Some additional infos.

I had the same problem. I was building in a conda environment where I had pinocchio installed with `conda install pinocchio`. `conda` correctly installed the boost dependencies, but cmake was finding boost in `/usr/...`.

To correct this while using `conda` (option 1 above), I added `-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=True` to the cmake command. This way, cmake finds the config.cmake files for boost in the conda env, and thus the boost version installed with conda.

**Comment by fabinsch** [comment]
Hi @abussy-aldebaran,

I also encountered this before and for me it depends on which cmake I am using.

did you also `conda install cmake` in your activated conda environment? You can check by doing `which cmake` if you are using cmake from your env or another one. 

If I use cmake from the corresponding env, it usually correctly finds boost/other desps in the env and not from my system somewhere else without additional flags. Maybe this can help.

**Comment by jorisv** [comment]
Hi @abussy-aldebaran,

You can also find a full working conda environment in this file https://github.com/stack-of-tasks/pinocchio/blob/master/.github/workflows/conda/environment_macos_linux.yml

It's the same used by the CI.

**Comment by abussy-aldebaran** [comment]
I'm using my system's cmake. I guess that if I want to build within a conda environment, I should go all the way and install the toolchain within the env.

Thanks @jorisv !
