### ISSUE TITLE
Possible bug in urdf parser when multiple collision are attached

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#232]
In parser/urdf/geometry.hxx, line 167
` const std::string & collision_object_name = link_name;`
The new collision object is named as the link. What happen if several collision object are attached to a same body? Shouldnt we append to the collision name a id number? link_name + std::string("_") + std::string(num), with num an integer corresponding to the number of collision objects already attached?

**Comment by jcarpent** [comment]
I'm in favour of this solution.

**Comment by jmirabel** [comment]
This is the solution chosen in HPP though it's not fully safe.

**Comment by jcarpent** [comment]
Solved by #248.
