### ISSUE TITLE
Inverse Dynamics with Constraints in Pinocchio 3.1.0

### ISSUE THREAD

**Issue by Sang-SC** [stack-of-tasks/pinocchio#2356]
I'm working on a project that involves calculating inverse dynamics for a four-bar linkage leg mechanism. I've been using RBDL's `RigidBodyDynamics::InverseDynamicsConstraints` function for this purpose, but I'm looking to transition to Pinocchio 3.1.0.

My question is: Does Pinocchio 3.1.0 have a function similar to RBDL's `RigidBodyDynamics::InverseDynamicsConstraints`?

I've searched through the Pinocchio documentation and codebase, but I haven't been able to find an equivalent function. The closest I've found is the `constraintDynamics` function, which calculates forward dynamics with constraints, not inverse dynamics.

If such a function exists in Pinocchio 3.1.0, could you please point me in the right direction? If not, are there any plans to implement this functionality in the future?

Any guidance or suggestions on how to approach this problem using Pinocchio would be greatly appreciated.

Thank you for your time and assistance.

**Comment by ManifoldFR** [comment]
Hello, thanks for your interest in using Pinocchio!

We do not have such a thing yet as a first-class function in Pinocchio. However we do have an implementation of constrained+underactuated inverse dynamics (for bilateral constraints) in our numerical OC library **aligator**, see [here](https://github.com/Simple-Robotics/aligator/blob/main/include/aligator/modelling/multibody/constrained-rnea.hpp). It's not perfect in terms of performance and the algorithm is a mere QR decomposition of a linear system, so the behaviour will not be perfect (you're essentially getting a least-squares solution).

**Comment by Sang-SC** [comment]
Thank you very much for your thorough and helpful response to my question!

**Comment by zacharyyamaoka** [comment]
@Sang-SC Did you end up finding a good solution for this? I am also interested in doing inverse dynamics for a parralel 5 bar linkage robot! Thanks :)
