### ISSUE TITLE
[devel] Pinocchio does not compile when BUILD_PYTHON_INTERFACE is disabled 

### ISSUE THREAD

**Issue by stonneau** [stack-of-tasks/pinocchio#236]
if  BUILD_PYTHON_INTERFACE is disabled,
the file parsers/sample-models.cpp is not added to the source list 
(src/CMakeLists.txt, line 51).

As a result the method se3::buildModels::humanoidSimple(se3::Model&, bool) is not 
implemented

This results in at least one test not compiling, since it explicitely calls the method:
Aba::test_aba_simple::test_method(): file unittest/aba.cpp, line 45

**Comment by nmansard** [comment]
Solved by #237 (waiting for somebody else to merge)

**Comment by jcarpent** [comment]
Solved by #238
