### ISSUE TITLE
Identical files between "constraint" and "motion-subspace"

### ISSUE THREAD

**Issue by EtienneAr** [stack-of-tasks/pinocchio#2381]
Hello,

While debugging some feature, I realized that the following files were identical :
* [include/pinocchio/multibody/constraint-base.hpp](https://github.com/stack-of-tasks/pinocchio/blob/c989669e255715e2fa2504b3226664bf20de6fb5/include/pinocchio/multibody/constraint-base.hpp) and [include/pinocchio/multibody/joint-motion-subspace-base.hpp](https://github.com/stack-of-tasks/pinocchio/blob/c989669e255715e2fa2504b3226664bf20de6fb5/include/pinocchio/multibody/joint-motion-subspace-base.hpp)
* [include/pinocchio/multibody/constraint-generic.hpp](https://github.com/stack-of-tasks/pinocchio/blob/c989669e255715e2fa2504b3226664bf20de6fb5/include/pinocchio/multibody/constraint-generic.hpp) and [include/pinocchio/multibody/joint-motion-subspace-generic.hpp](https://github.com/stack-of-tasks/pinocchio/blob/c989669e255715e2fa2504b3226664bf20de6fb5/include/pinocchio/multibody/joint-motion-subspace-generic.hpp)
* [include/pinocchio/serialization/joints-constraint.hpp](https://github.com/stack-of-tasks/pinocchio/blob/c989669e255715e2fa2504b3226664bf20de6fb5/include/pinocchio/serialization/joints-constraint.hpp) and [include/pinocchio/serialization/joints-motion-subspace.hpp](https://github.com/stack-of-tasks/pinocchio/blob/c989669e255715e2fa2504b3226664bf20de6fb5/include/pinocchio/serialization/joints-motion-subspace.hpp)

Is it intentional ?
I am guessing it is oversight of the renaming from "constraint" to "motion subspace" because the "constraint" files are used nowhere now.

Should the "constraint" files be removed ?

**Comment by jcarpent** [comment]
Yes, they should have been removed before the release of Pinocchio 3, but we have forgotten to do it.
`constraint` name choice was not good. We can then remove these files.

Thanks a lot @EtienneAr for raising this issue.
