### ISSUE TITLE
Add normalized and isNormalized algorithms

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#239]
This issues is linked to humanoid-path-planner/hpp-pinocchio#14.

Sometimes, due to serialization, integration, etc ... the configuration can lose its normalization property. The idea is to add two algorithms: one which checks the normlization of an input config vector, the other one which normlalizes the config vector given as input.

**Comment by jmirabel** [comment]
Do you accept default implementation for method like `normalized_impl` in JointModel ?

**Comment by jcarpent** [comment]
solved by #241.
