### ISSUE TITLE
Unable to run example rviz-viewer.py

### ISSUE THREAD

**Issue by meisbokai** [stack-of-tasks/pinocchio#2423]
## Bug description

Hello, i would like to ask if there could be more examples regarding the usage of ROS with pinocchio?
When attempting to run `python examples/rviz-viewer.py`, I am facing this error 

```bash
Traceback (most recent call last):
  File "rviz-viewer.py", line 21, in <module>
    viz = RVizVisualizer(model, collision_model, visual_model)
TypeError: Can't instantiate abstract class RVizVisualizer with abstract methods captureImage, disableCameraControl, drawFrameVelocities, enableCameraControl, setBackgroundColor, setCameraPose, setCameraPosition, setCameraTarget, setCameraZoom
```

## Expected behavior

Example should run without issues

## Reproduction steps

1. Build pinocchio from source
2. Attempt to run `rviz-viewer.py` in example folder

### Docker image

- NIL

### Code

- NIL

## Additional context

- NIL

### System

- OS: Ubuntu 20
- Pinocchio version: 3.2.0 (master branch)

**Comment by jcarpent** [comment]
Solved via #2425
