### ISSUE TITLE
Error when compiling with -march=native

### ISSUE THREAD

**Issue by egordv** [stack-of-tasks/pinocchio#2434]
## Bug description

Hello!
Trying to use pinocchio functions in project compiled with "-march=native" option always results in different types of memory related errors (std::bad_alloc / double free or corruption / boost::bad_get) depending on the environment

## Reproduction steps

1. Clone https://github.com/stack-of-tasks/pinocchio-minimal
2. Compile and run "as is" according to repo's readme - binary works as expected
3. Add ```target_compile_options(main PUBLIC -march=native)``` to the end of repo's CMakeLists.txt
4. Will cause ```terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_get>'
  what():  boost::bad_get: failed value get using boost::get
Aborted (core dumped)``` when trying to run the binary

### System

- OS: Ubuntu 22.04
- Pinocchio version: 3.0.0r1 amd64 installed via robotpkg

**Comment by jcarpent** [comment]
With march native on, you should compile pinocchio and all the dependencies (that depends on Eigen) using the same option, as it activates specific alignment within Eigen.
