### ISSUE TITLE
Model: avoid redundant addJoint methods

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#244]
In Model, we have several methods addJoint and addJointAndBody. All of them can be achieved equivalently by calling then nominal addJoint(parent,type,placement,inertia,names), followed possibly some few additional methods to complete the call. I would like to suggest to remove this redundancy:
A. either by simply removing the redundant methods, while only keeping the basic ones
B. or by, at least, calling the basic methods in the complex ones, while removing the code duplicate. 

I vote for A.

**Comment by nmansard** [comment]
In one of the methods, neutralConfiguration is assigned to be the middle point of the joint range. If this behavior is important, I suggest to write a dedicated algorithm that force the neutral configuration to be the range median, explicitly and a posteriori.

**Comment by nmansard** [comment]
This becomes a HPP reqiuirement: we do not have the same behavior. I will implement the above-mentioned proposition.

**Comment by jcarpent** [comment]
Partially solved by #251.

**Comment by jcarpent** [comment]
Entirely solved by #251.
