### ISSUE TITLE
Import Error: libeigenpy.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kchen50** [stack-of-tasks/pinocchio#2467]
## Bug description

Pinocchio is not importing properly (Pinocchio installed from here: https://github.com/stack-of-tasks/pinocchio-ros-release/tree/release/noetic/pinocchio)

1. Install Pinocchio ROS release from the link above
2. Run "python" in terminal
3. Run "import pinocchio" in terminal

### Screenshots

![image](https://github.com/user-attachments/assets/d1dbfac6-b52f-46ea-baf8-e20273e33c29)

### System

- OS: Ubuntu 22.04
- Python version: 3.11
- Pinocchio version: Most recent version from here: (Pinocchio installed from here: https://github.com/stack-of-tasks/pinocchio-ros-release/tree/release/noetic/pinocchio)

Thank you for the help!

**Comment by nim65s** [comment]
Hi,

conda packages and ros packages are not compatible. Please use one or the other.
