### ISSUE TITLE
module 'pinocchio' has no attribute 'visualize'

### ISSUE THREAD

**Issue by Libre007** [stack-of-tasks/pinocchio#2488]
Hello developers,

I'm encountering an issue while using Python to import Pinocchio. When I attempt to check the path of the meshcat_visualizer module, it indicates that Pinocchio does not have a 'visualize' attribute. Could someone please explain why this might be happening?

Here's the detailed process that led to this issue:
```python
Python 3.8.20 (default, Oct  3 2024, 15:24:27) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pinocchio
>>> print(pinocchio.visualize.__file__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pinocchio' has no attribute 'visualize'
>>> import pinocchio.visualize as pin_vis
>>> print(pin_vis.__file__)
/opt/openrobots/lib/python3.8/site-packages/pinocchio/visualize/__init__.py
>>> 
```
Looking forward to your response.

**Comment by nim65s** [comment]
Hi @Libre007,

If you want to use robotpkg, you must use the python interpreter provided by your linux distribution, and not conda.

On the other hand, if you want to use conda, you can not use robotpkg, but can install pinocchio from conda-forge
