### ISSUE TITLE
CollisionObject and CollisionGeometry

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#253]
We have a CollisionObject (ie a CollisionGeometry plus a FCL placement) in the GeomModel. The placement is never used. We also have a FCL placement in GeomData. 
We should rather have a CollisionGeometry in the model. It would also be nice to have rather a CollisionObject in the GeomData, rather than simply a placement, as it is not more costly and eases the call to collision/distance computations.

**Comment by jcarpent** [comment]
Solved by #270.
