### ISSUE TITLE
CollisionPair

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/pinocchio#254]
The current implementation of CollisionPair inverts the index to have them in logical order. It is not very convenient.
A user who wants to read the distance results to get the closest points has no way to know that the indexes have been inverted and that the closest points have to be inverted.

I seems this is used only to ensure that there is no duplicates in the list. If this is the case, I see two options:
- option A : the user must remember whether the indexes have been inverted,
- option B: add an operator== to CollisionPair which handle inverted pairs.

I'm in favour of option B because I do not like the fact that the inversion of collision pairs is done in the back of the user.

**Comment by jcarpent** [comment]
Just  to be clear, I sum up your proposition B:
You want to suppress the forced ordering and have any ordering. And add an operator== which takes into account the two situations. Isn't it?

I also suggests to add a method to sort all collision pairs by first index value for example. Just to be efficient in the when calling algorithms.

**Comment by jmirabel** [comment]
I mean this:
`ColPairA == ColPairB` <=> `(ColPairA.first == ColPairB.first && ColPairA.second == ColPairB.second) || (ColPairA.first == ColPairB.second && ColPairA.second == ColPairB.first) || `

About the method to sort, I agree. But I think the method should not be called automatically. Or, at least, ahoud be such that the user can disable sorting the pairs.

**Comment by jmirabel** [comment]
I can do a pull-request with option B.

**Comment by jcarpent** [comment]
Let's do that !

**Comment by jcarpent** [comment]
Solved by #255.
Maybe we still need to check the Python interface.
