### ISSUE TITLE
Use njoint instead of nbody for joint visitors

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#259]
Currently, nbody is used while njoint must be used inside all algorithms. This is a bug which must be solved quickly.

**Comment by nmansard** [comment]
BTW: I dont like this redundancy of information, by explicitly storing the size of the lists (e.g. have njoint which is equal to joints.size()). Dont you think that we should get rid of it?

**Comment by jcarpent** [comment]
Indeed. And it must be the same for nbody.

**Comment by nmansard** [comment]
Ok. Should we remove nbody first and use njoint instead, and then do a second PR (later, less urgent) removing njoint, ngeom etc?

**Comment by jcarpent** [comment]
I agree as njoint is safe.

**Comment by jmirabel** [comment]
This means that, from now on, we should use `model.joints.size()` rather than `model.joints.njoints`, right ?

**Comment by jcarpent** [comment]
Both `model.joints.size()`and `model.njoint` are ok. But to avoid redundant info, it might interesting to only consider the first solution. 
Right, you should avoid to use `model.nbody`which may lead to bugs as nbody >= njoint

**Comment by nmansard** [comment]
For njoint: it rather was a question. Should we keep it or remove it. Maybe keep it is cheap and easy to assert, and simplify downstream use. 
In any case, we should mark nbody as deprecated.

**Comment by jcarpent** [comment]
Solved by #288.
