### ISSUE TITLE
Axis protected in unaligned joint models

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#261]
In JointModelPrismaticUnaligned and JointModelRevoluteUnaligned, axis is protected and there is no accessor on it. I need to have access (in read only) to this attribute. 

Is there any rationnal to but axis protected? I suggest to simply pass it as a public attribute.

**Comment by jcarpent** [comment]
I'm fixing current bugs in integrate. I will do it in the same PR.

**Comment by nmansard** [comment]
Thx. Could you also fix obstacle placement BTW? See humanoid-path-planner/hpp-pinocchio#27

**Comment by jcarpent** [comment]
Ok.

**Comment by nmansard** [comment]
Solved by direct push.
The second point is PR #264.
