### ISSUE TITLE
Remove subtreeCoM option from centre of mass algo

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#268]
The scalar division of a vector3 is only 3ns, or less to be compared to SINCOS which is around 20ns per call.
The option subtreeCoM can be safely deleted without adding further computation costs.

**Comment by nmansard** [comment]
3ns*30joints = .1us, which is significant even if only a tenth of the total computation. This code is harmless and marginally beneficial. We should keep it as it is.
