### ISSUE TITLE
Finite differences with joints

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#271]
If one wants to do finite differences with revolute joints and similar, one must take care of scalar precisions ... Just because of the presence of cos and sin. So if you want to work with cos for example, with a precision a sensitivity variation around 1e-8, theta must vary around 1e-4 or less to be sensible (it comes from the Taylor expansion).

**Comment by jcarpent** [comment]
This remarks is a reason of #256.

**Comment by jcarpent** [comment]
I suggest that each joint give has a method which returns a scalar increment for finit diff purposes.

**Comment by nmansard** [comment]
Solved by #274
