### ISSUE TITLE
Namespace name

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#272]
Somes namespace names can conflict with other project. For example, Eigen also use the namespace internal for its traits.
For boost, and std, they have for example the same shared_ptr name for shared pointer. So, for c++11 application, we must deal with the two namespaces.

**Comment by jcarpent** [comment]
To be more precise, some compilers cannot guess the right namespace path.

**Comment by nmansard** [comment]
This is not yet a bug for the pinocchio user, so I remove the label for clarity purpose.
