### ISSUE TITLE
Shared ptr

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#273]
The geometry module uses shared_ptr, that are now integrated in the std for C++11 and more. Should we keep the boost version, or use a typedef in case of CXX11?

**Comment by jcarpent** [comment]
This bug appears with recent compilers like gcc6.

**Comment by nmansard** [comment]
Shared_ptr are inhereted from hpp::fcl. I think we should simply follow their convention.

**Comment by nmansard** [comment]
After check, Pinocchio always explicitly specifies boost:: when using shared_ptr. The issue might be reported to hpp::fcl.
