### ISSUE TITLE
Use std::copy in algo/copy

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#275]
For efficiency reason, use std::copy in algo/copy.hpp.

**Comment by nmansard** [comment]
std::copy is not faster here and less readable. Memcpy might be faster (I did not benchmarked) but that can not be significant. I keep the clean version of the code.

**Comment by jcarpent** [comment]
According to the std documentation, std::copy is as simple as:
`std::copy(from_vector.begin(), from_vector.end(),to_vector);`
Also, it seems that std::copy is faster than std::memcpy according to http://stackoverflow.com/questions/4707012/is-it-better-to-use-stdmemcpy-or-stdcopy-in-terms-to-performance
