### ISSUE TITLE
Stable API at the current status of devel branch

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/pinocchio#299]
Hi Pinocchio developpers,

The API of the devel branch is not stable enough for downstream libraries. Every week, something is changing in the API and I see a lot of issues which involves other API changes.

Would it be possible to have a branch which would be updated with the bug fixes but not all the API changes ? It could be the master branch (updated to the current devel branch) or another branch.

Thanks

**Comment by jcarpent** [comment]
Currently, some methods or functions are set to deprecated, that means that they will be suppress in the near future. So, you have time to adapt your code.
During the meantime, the API is increased with new features. Then, they won't affect your code.

Concerning the Collision part, the API must be adapted to fulfil your requirements. Then it is hard to stabilise everything together.

**Comment by jcarpent** [comment]
Also, if you want to directly discuss with Pinocchio developers, there is the email address pinocchio@laas.fr

**Comment by jcarpent** [comment]
What I propose is to add a devel-stable or hop-stable branch inside the repo, which will be only filled with bug fixes. What do you think?

**Comment by jmirabel** [comment]
Yep, a hpp-stable or devel-stable branch would be nice.

**Comment by jcarpent** [comment]
Ok, I just pushed a new branch dedicated to the merge of Pinocchio inside HPP (https://github.com/stack-of-tasks/pinocchio/tree/hpp-devel). We'll try to maintain it up to date for bug fixes.

**Comment by jcarpent** [comment]
Can we close this Issue?
