### ISSUE TITLE
Bug in parsing HYQ urdf model

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#315]
In HYQ, a geometry is attached to the base_link, which is not properly handled by Pinocchio urdf parser.
Hack: If needing to use the URDF model of HYQ with both kinematic and geometry information, you need to comment out this geometry.
  \<link name="base_link"\>
    \<!-- \<visual\> --\>
    \<!--   \<geometry\> --\>
    \<!--     \<cylinder length="0.01" radius="0.01"/\> --\>
    \<!--   \</geometry\> --\>
    \<!-- \</visual\> --\>
  \</link\>

**Comment by jmirabel** [comment]
Branch hpp-devel should fix this problem. Could you try with this branch?

**Comment by nmansard** [comment]
It is difficult to try yet because hpp-devel is yet not compiling with Python.

**Comment by jcarpent** [comment]
The problem seems solved with recent modifications.
