### ISSUE TITLE
SRDF parser not tested.

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/pinocchio#317]
There is not unittest for the SRDF parser. Maybe it could be added to `unittest/urdf.cpp`.

**Comment by jcarpent** [comment]
Split if you can, it will be easier to maintain. I prefer several unit test files than a big one.

**Comment by jmirabel** [comment]
The suggested file is merely loading a URDF, and is less than 10 lines of actual code. To test the SRDF, the easiest is to first load a URDF. So you will anyway copy the same 10 lines of code.

**Comment by jcarpent** [comment]
Yes, and we will add new parsing of infos, like end effectors, etc ... and then the test number will increase with time. So, to avoid future refactoring, I propose to directly add such a dedicated file.

**Comment by jcarpent** [comment]
As this is not mandatory, I remove the label.

**Comment by jcarpent** [comment]
Solved by #342.
