### ISSUE TITLE
Choose root joint type

### ISSUE THREAD

**Issue by aelkhour** [stack-of-tasks/pinocchio#32]
The URDF parser currently gives the user the choice of adding a free-flyer joint to the root link.
It would be interesting to allow adding other types of joints (prismatic, revolute, etc.)

**Comment by fvalenza** [comment]
Taken into Account. Added to developments to be done

**Comment by aelkhour** [comment]
Thanks.

**Comment by jcarpent** [comment]
Thanks to #53, one is now able to set his/her desired root joint (eg. Free Flyer, Planar, etc).
