### ISSUE TITLE
viewing mesh with scale parameter in gepetto-viewer

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/pinocchio#362]
This might be a bug. If a scale is specified in the urdf file for the meshes, this scale is not transmitted to gepetto-viewer for display.

Meshes are added to the viewer by `self.viewer.gui.addMesh(meshName, meshPath)` in robot_wrapper.py. This does not take into account any additional information available in the urdf. There should ideally be a way to transmit the full information of the urdf to the viewer.

**Comment by jmirabel** [comment]
From the viewer side, there is a function setScale. So if Pinocchio keeps
scale information, the fix should be easy.

**Comment by jcarpent** [comment]
@proyan You should update the class `GeometryObject` with a scale parameter and keeps this information when parsing the URDF file. That's pretty easy and straight forward.

**Comment by jmirabel** [comment]
If you do so, please make it explicit that the scale has already been taken into account. I mean:
`GeometryObject.meshPath` + `GeometryObject.scale` -> `GeometryObject.fcl`

**Comment by proyan** [comment]
In case of other objects being loaded, (e.g. Cylinder/Box/sphere), should the default scale be set to (1,1,1)?

**Comment by jcarpent** [comment]
What should be the other solution you have in mind?

**Comment by proyan** [comment]
#363 Pull request created

**Comment by jcarpent** [comment]
Solved by #363.
