### ISSUE TITLE
Pinocchio does not compile with Eigen 3.3.3

### ISSUE THREAD

**Issue by andreadelprete** [stack-of-tasks/pinocchio#385]
Pinocchio doesn't seem to compile with Eigen 3.3.3, which is the last stable release of Eigen. This doesn't allow me to benefit from the last developments of Eigen, such as the implementation of the [Complete Orthogonal Decomposition](https://eigen.tuxfamily.org/dox/classEigen_1_1CompleteOrthogonalDecomposition.html).

**Comment by jcarpent** [comment]
I checked a bit, but it seems that the problem comes from humanoid-path-planner/hpp-fcl#10 where @jmirabel added by default the use of Eigen vectors inside FCL instead of internal linear algebra library.

**Comment by jcarpent** [comment]
To tackle this issue, you can set the flag FCL_EIGEN to OFF when installing hpp-fcl.

**Comment by andreadelprete** [comment]
Actually after some tests I found out that the problem was that I had not recompiled pinocchio with Eigen 3.3.3, so I in my library I was mixing Eigen 3.2 (used to compile pinocchio) with Eigen 3.3.3. After recompiling pinocchio everything seems to work fine.

**Comment by jcarpent** [comment]
Ok. Perfect. I close the issue then.
