### ISSUE TITLE
Pinocchio v1.2.3 on robotpkg lacks some files

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/pinocchio#386]
@gabrielebndn found that, when installing pinoccho v1.2.3 from robotpkg, there is an
`#include "pinocchio/multibody/liegroup/liegroup.hpp"` in `algorithm/joint-configuration.hpp`, but there is no `pinocchio/multibody/liegroup` folder.

**Comment by jcarpent** [comment]
The problem could appear if you install pinocchio using robotpkg. The PLIST file was incomplete. The problem is now fixed.
