### ISSUE TITLE
fcl code without WITH_HPP_FCL

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/pinocchio#401]
Accidentaly found this… By forgetting hpp-fcl.

here: https://github.com/stack-of-tasks/pinocchio/blob/devel/bindings/python/multibody/geometry-object.hpp#L67

As this is a compilation option, shouldn't we test it with CI ?

**Comment by jcarpent** [comment]
I have a fix about it since a while. I need to find it back and then push it.

**Comment by jcarpent** [comment]
Solved by #408.
