### ISSUE TITLE
Name in classes se3::LieGroupOperationBase

### ISSUE THREAD

**Issue by florent-lamiraux** [stack-of-tasks/pinocchio#404]
For debugging purposes, I need to know the name of the classes deriving from se3::LieGroupOperationBase 
  - SpecialEuclideanOperation,
  - SpecialOrthogonalOperation,
  - VectorSpaceOperation,
  - ...
I plan to add a method "name" in LieGroupOperationBase that returns the name of the object.
Is there any objection or suggestion ?

**Comment by jcarpent** [comment]
For me this is fine. 
If you plan to use theses classes together with variants, you can have a direct map trough the variant itself. But maybe this is too hard or can induce some difficulty for the review of the code.

**Comment by jcarpent** [comment]
Solved by #406.
