### ISSUE TITLE
Romeo's models

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/pinocchio#424]
Hi,

I noticed that https://github.com/stack-of-tasks/pinocchio/tree/master/models/romeo/meshes/romeo is the same as https://github.com/laas/romeo/tree/master/romeo_description/meshes/V1.

The package robotpkg-romeo-description installs the version in laas/romeo, and there is no packaging of the folder in this package, so maybe we should remove it ?

**Comment by jcarpent** [comment]
You're right. The first idea was to have a single repo without too many submodules.
We may just check that the two models are identical at the URDF level.

**Comment by nim65s** [comment]
I clone both repos, and launch meld on those folders. It said they are no differences.
