### ISSUE TITLE
Problem with mprint function

### ISSUE THREAD

**Issue by zhangOSK** [stack-of-tasks/pinocchio#427]
Hello there!
I am a new user for pinocchio. When I follow Tutorails 1.0, there are some errors. Could you please help tell me how to solve them?
![mprint](https://user-images.githubusercontent.com/34937108/34434846-771ae374-eccc-11e7-87f4-129fa20778fb.png)
![se3](https://user-images.githubusercontent.com/34937108/34434847-789d2180-eccc-11e7-968f-7266ab0c9199.png)

Another thing is currently the latest versions of omniORB is omniORB 4.2.2 and omniORBpy 4.2.2. But for me, it is not working. Perhaps it's better to mention in the installation part that the old version (ORB4.1.x and ORBpy 3.x) is preferred. 
Thanks!

**Comment by jcarpent** [comment]
Hi,
We forgot to overload the operator* for vector of dimension 3 types. I will fix it soon.
Please use `op = oM1.act(_1p)` instead.

**Comment by zhangOSK** [comment]
Thanks for your reply and happy new year!
The other problem I met is 'Model' object has no attribute 'addJointAndBody'.
Could you please also help me solve this problem. Thank you a lot.

![Uploading Screenshot from 2018-01-02 17:15:08.png…]()

**Comment by jcarpent** [comment]
Happy new year too!

To replace this method `addJointAndBody`, you can first call `addJoint` followed by `appendBodyToJoint`. It will do the same.

**Comment by jcarpent** [comment]
I've just fixed the first issue with commit 98481df18bf7ea7a8ef070306adee3521b8bbb9c. 
You can update your repository and proceed to a new installation.

**Comment by zhangOSK** [comment]
Thanks for your help!
I tried to use addJoint, but I met a augment error.  
What does the "Model" or "se3::Model{lvalue}" mean?

![screenshot from 2018-01-02 22 25 11](https://user-images.githubusercontent.com/34937108/34485151-5ee47a0c-f00c-11e7-8303-755e328ab713.png)

Besides, I used robotpkg to installed pinocchio, how can I make change of the first issue by robotpkg?

**Comment by jcarpent** [comment]
`addJoint` takes four arguments:
- parent
- jointModel
- jointPlacement
- jointName
and `appendBodyToJoint` takes three arguments:
- parent_id (id of the supporting joint)
- bodyInertia
- bodyPlacement

And `se3::Model{lvalue}`is equivalent of the Python self argument for methods. It is automatically generated by boost-python.

I will update soon pinocchio on robotpkg to fix your issues.
Best,

Justin

**Comment by zhangOSK** [comment]
Thanks a lot! 
Now the addJoint and appendBodyToJoint function work well.
However,, another issue appeard
![screenshot from 2018-01-02 23 25 06](https://user-images.githubusercontent.com/34937108/34486707-5e0174ac-f014-11e7-8708-f1f12b5cc690.png)
How can I fix this,

**Comment by zhangOSK** [comment]
And also missing of geometry, like this
![screenshot from 2018-01-02 23 29 59](https://user-images.githubusercontent.com/34937108/34486838-f7d294e4-f014-11e7-982c-89527e6e002b.png)

**Comment by jcarpent** [comment]
I guess you are on very old tutorials. @nmansard Can you provide the most recent versions of your tutorials?

There is no more model.nbody parameter. You can remove this info from printing.
`se3.geometry` has been replaced by `se3.forwardKinematics`.

**Comment by nmansard** [comment]
See https://github.com/stack-of-tasks/pinocchio-tutorials

**Comment by jcarpent** [comment]
@zhangOSK Did you fix your issues?

**Comment by zhangOSK** [comment]
Thank you!
I have fixed the issue with your help!

**Comment by jcarpent** [comment]
Perfect!
