### ISSUE TITLE
Pinocchio and C++-11

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/pinocchio#429]
On ubuntu 16.04 LTS, when compiled in C++-03, the binary prototype of buildModel has three additionnal boost::detail::variant::void_ to its original header.
This is the default option when compiled using robotpkg. 
Once installed using apt-get installed you can checked that:
``
nm -a /opt/openrobots/lib/libpinocchio.so | grep buildModel | c++filt
``
gives
``
se3::urdf::buildModel(boost::shared_ptr<urdf::ModelInterface> const&, boost::variant<se3::JointModelRevolute<0>, se3::JointModelRevolute<1>, se3::JointModelRevolute<2>, se3::JointModelRevoluteUnaligned, se3::JointModelSpherical, se3::JointModelSphericalZYX, se3::JointModelPrismatic<0>, se3::JointModelPrismatic<1>, se3::JointModelPrismatic<2>, se3::JointModelPrismaticUnaligned, se3::JointModelFreeFlyer, se3::JointModelPlanar, se3::JointModelTranslation, se3::JointModelRevoluteUnbounded<0>, se3::JointModelRevoluteUnbounded<1>, se3::JointModelRevoluteUnbounded<2>, boost::recursive_wrapper<se3::JointModelComposite>, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, se3::Model&, bool)::__PRETTY_FUNCTION__
``
When compiled in C++-11,  this disappear. However right now pinocchio does not compile using -std=c++11. Indeed hey are two access errors to boost::variant::extract in model.hpp and parsers.hpp.

Pull request #428 proposes a fix to this. It has been tested and compiles in both C++-03 and C++-11 on xenial. But I would recommend the latest being the default because jrl-walkgen and sot-torque-control both use the C++-11 flag. Having pinocchio compiled in C++03 makes the link phase breaks due to the difference of prototype.

**Comment by jcarpent** [comment]
This is mostly due to compilations issues coming from package having Pinocchio as dependency. They are not induced by Pinocchio itself.
The boost::detail::variant::void_ are default template parameters to mimic variadic template.
Then, they appeared in the libpinocchio.so.
If C++11 flags is used when compiling, then Boost switch to Variadic templates version of variants, where there is no need of fake boost::detail::variant::void_.
