### ISSUE TITLE
spatial velocity computed by forwardKinematics?

### ISSUE THREAD

**Issue by zongmianli** [stack-of-tasks/pinocchio#430]
After a function call of se3::forwardKinematics(model, data, q, vq), are the spatial velocities stored in data.v[j] expressed in world frame (i.e., ^o\nu_{o,j}) or the joint's local frame (^j\nu_{o,j})? Originally and after checking the source code I believe it's the later. Could you confirm this?

**Comment by jcarpent** [comment]
Local frame indeed. Please refer to Featherstone's book for such details.

**Comment by zongmianli** [comment]
Thanks @jcarpent !

**Comment by jcarpent** [comment]
@zongmianli Your welcome.

**Comment by nmansard** [comment]
Featherstone is a good reference for the general organization. Unfortunately, the details of the algorithms is not the same, so some times it is a good idea to look in the textbook, some times it is not. 

@zongmianli , if you have an idea where to put this information in the code comments, could you make a PR with it?
