### ISSUE TITLE
Computing gradients and hessians

### ISSUE THREAD

**Issue by Bilalhmd** [stack-of-tasks/pinocchio#437]
Is there an implementation to compute gradients and hessians of the dynamics ? i can find a finite-difference implementation in algorithms, will I be able to use this ?

**Comment by jcarpent** [comment]
Which derivatives do you need?

**Comment by Bilalhmd** [comment]
rearranged my dynamics into the form dx/dt = f(x,u), wondering if there is functions to compute df/dx, df/du etc .. or if there is a general way that these are computed when solving typical optimization problems 

Thanks alot

**Comment by cmastalli** [comment]
I would take this opportunity to open a discussion about automatic differentiation. I know that we can find analytical derivatives of some rigid body algorithms, but do you think we can do it for all the algorithms? In negative case, it would be nice to extend Pinocchio with CppAd

**Comment by jcarpent** [comment]
@Bilalhmd  It really depends on the choice of your robot. Is a free floating base system or not.
I would really recommand you to first use finite differences for prototyping your codes.
We already provide some derivatives for doing such kind of computations. 
We hope to be able to integrate the analytical derivates in Pinocchio, but it remains a work in progress.

**Comment by jcarpent** [comment]
@cmastalli It would be interested indeed, but AD does not solve all the problems. It is also a hard to make all the code compliant with operator overloading.
We let this task as a very low priority.

**Comment by jcarpent** [comment]
@Bilalhmd Do you need additional help for derivatives? I will close this issue.
Feel free to open it again if you have other questions.

**Comment by jcarpent** [comment]
@Bilalhmd A while ago, you asked for computing derivatives in Pinocchio.
This message just to inform you that they are now available on the devel branch of Pinocchio.
There is a RSS paper which explains the computations: https://hal.laas.fr/hal-01790971

Best,

Justin

**Comment by hammoudbilal** [comment]
Hi, this have been really helpful, it seems to me that the terms regarding the contact/external forces are not included in the code, for example in the forward dynamics derivative  dFD/dq should i just simply add (dM_inv/dq).J^T.f_{ext}  + M_inv.(dJ^T/dq).f_{ext}  ?

best 
Bilal

**Comment by jcarpent** [comment]
They are taken into account on the devel branch.

**Comment by hammoudbilal** [comment]
found it, thanks! it seems that only the python binding was missing for the extended version of the function, i will stop posting on this thread.

**Comment by jcarpent** [comment]
Do you need them?

**Comment by hammoudbilal** [comment]
no everything works fine, thanks again
