### ISSUE TITLE
[CMake] Installing .pyc files

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/pinocchio#464]
Hi,

In https://github.com/stack-of-tasks/pinocchio/blob/master/bindings/python/CMakeLists.txt#L214 we try to install .pyc files.

First of all, I don't understand why.
Does someone have an explanation ?

Then, in python 3.2+, [PEP 3147](https://www.python.org/dev/peps/pep-3147/) states that compiled files are no more `$filename.pyc`, but `__pycache__/$filename.<magic>.pyc` with `<magic>` something like `cpython-35`, so the project is not building, because cmake is still looking for `$filename.pyc`.

**Comment by jmirabel** [comment]
I guess it is mostly a copy-paste from https://github.com/jrl-umi3218/jrl-cmakemodules/blob/d22de8c53c3507df785b1fb3ab260d9fdfb65233/python.cmake#L183

**Comment by jmirabel** [comment]
As of now, I could not find any pros and cons. You have found an important cons.

**Comment by jcarpent** [comment]
It is just an historical reason.
You can remove this pass inside the CMakeLists.txt.

**Comment by nim65s** [comment]
will do :)

**Comment by jmirabel** [comment]
Can you open an issue in https://github.com/jrl-umi3218/jrl-cmakemodules as well ?

**Comment by jcarpent** [comment]
Solved by #465
