### ISSUE TITLE
eigen 3.3.4 compatibility & Eigen::internal

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/pinocchio#471]
Hi,

I'm forwarding some comments from https://git.openrobots.org/issues/164:

> In https://github.com/stack-of-tasks/pinocchio/blob/master/src/spatial/explog.hpp#L41
> I don't see why [Eigen::internal] is necessary, it should probably be dropped since it's used only to create an identity matrix. At least it breaks with eigen-3.3.4, which says:
>> error: 'Options' is not a member of 'Eigen::internal::traits<blah blah
>
> See this for reference: http://eigen.tuxfamily.org/dox/TopicFunctionTakingEigenTypes.html

**Comment by jcarpent** [comment]
This bug has been solved by #472.
