### ISSUE TITLE
possibly outdated commands in Tutorial 1

### ISSUE THREAD

**Issue by miggia** [stack-of-tasks/pinocchio#475]
Hi,
I'm following the tutorials and happened to notice that the method `Model.addJointAndBody` (as used in tutorial 1.2, `model.addJointAndBody(parent, jointModel, jointPlacement, bodyInertia, jointName, bodyName)`) is not available any more
If I understand correctly, it has been substituted by `Model.addJoint` and `Model.appendBodyToJoint`.
Also it seems `Model.nbody` and `Model.njoint` have been replaced by `Model.nbodies` and `Model.njoints` respectively.

It could be useful to update the documentation.
I'm pasting here the code snippets I used, if you ever found them convenient for copying.

```python
# Example of creation of a simple robot model with one single revolute joint rotating around axis X.
model = se3.Model.BuildEmptyModel()
name                          = "first"                             # Prefix of the name.
jointName,bodyName            = [name+"_joint",name+"_body"]        # Names of joint and body.
jointPlacement, bodyPlacement = se3.SE3.Random(),se3.SE3.Random()   # SE3 placement of the joint wrt chain init.
parent                        = 0                                   # Index of the parent (0 is the universe).
jointModel                    = se3.JointModelRX()                  # Type of the joint to be created.
bodyInertia                   = se3.Inertia.Random()                # Body mass/center of mass/inertia => useless for
                                                                    # this tutorial.
```

```python
model.addJoint(parent,jointModel,jointPlacement,jointName)
model.appendBodyToJoint(model.getJointId(jointName), bodyInertia, bodyPlacement)
print('Model dimensions: {:d}, {:d}, {:d}'.format(model.nbodies,model.nq,model.njoints))
```

Finally the method `XYZQUATToViewerConfiguration` mentioned in tutorial 1.1 yields deprecation warnings of the type:
```
.../display.py:55: DeprecatedWarning: Call to deprecated function XYZQUATToViewerConfiguration. Now useless.
  XYZQUATToViewerConfiguration(se3ToXYZQUAT(M)) )
```

**Comment by jcarpent** [comment]
@miggia . I want to thank you for this issue.
Can you give the link of the tutorials that you are currently using?

**Comment by miggia** [comment]
Hi @jcarpenter,
I'm looking at the tutorial at https://stack-of-tasks.github.io/pinocchio/tutorials.html#Tutorial_1

As a side note, it took me a while to figure out that to instantiate `se3.SE3` objects, Pinocchio expects "vertical" matrices (differently from what is pointed out in [Tutorial 4](https://stack-of-tasks.github.io/pinocchio/tutorials.html#objective) where the `se3.SE3` object is created as `cost.Mdes = se3.SE3( eye(3),np.matrix([0.2,0,0.1+t/100.]) )`). 

For example, `se3.SE3( eye(3),np.matrix([0.0, 0.0, 0.0]))` returns an error of the type:
```
ArgumentError: Python argument types in
    SE3.__init__(SE3, matrix, matrix)
did not match C++ signature:
    __init__(_object*, se3::SE3Tpl<double, 0> other)
    __init__(_object*, int trivial arg (should be 1))
    __init__(_object*, Eigen::Matrix<double, 3, 3, 0, 3, 3> Rotation, Eigen::Matrix<double, 3, 1, 0, 3, 1> translation)
    __init__(_object*)
    __init__(_object*)
```
while `se3.SE3( eye(3),np.matrix([0.0, 0.0, 0.0]).T)` works OK.
Maybe I'm doing something wrong, but if that's not the case it might be useful to provide an example in the tutorial.

**Comment by nmansard** [comment]
@nim65s integrated the new tutorials ("labs") in the documentation of the current master. It is published at the following address:
http://projects.laas.fr/gepetto/doc/stack-of-tasks/pinocchio/master/

We should remove the link to the old version of the tutorial, that are referred in the github.io of pinocchio. @nim65s , would you have the time to do so?

**Comment by nim65s** [comment]
Hi,

Thanks for the report :)

The links in https://stack-of-tasks.github.io/pinocchio/ for the tutorial and the documentation have been updated respectively in b03e1c0551e56dc0c76f5300b29b13ff1badb9ea & 95fc4f15121f45f32c72a535f9c258c7052ab490

**Comment by miggia** [comment]
Thank you for the feedback.
I'll start looking at the new tutorials.
Best regards.
