### ISSUE TITLE
[Doc] Implementation of the structure

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#514]
Once the outline has been validated, the structure of the doc can be implemented with empty sections so that files exists that we can just allocated and fill.
I think the outline is now validated enough so that we can start implementing the structure.

**Comment by gabrielebndn** [comment]
Minor point we didn't comment on in the previous thread: what about the unit tests? Do they need any documentation? I don't think so, they seem self-explanatory. If we do document them, there is a "unit tests" entry as the final element of "features". Does it really belong there? Shouldn't it be in a separate part? Or maybe grouped with the benchmarks?

**Comment by jcarpent** [comment]
I do not think that unit test should be documented. They are completely outside the scope of the documentation.

**Comment by nmansard** [comment]
I would say they are part of the features of Pinocchio. A minimal entry (to say unit test exists, and are automatically run at merge time) would not be bad.

**Comment by gabrielebndn** [comment]
Saw the implementation of the structure. Seems good.
Just one thing: I see there is one "Examples" section, where each example consists of one page with a "Python" section and a "C++" section.
Is this the way we want to implement it? I think "Python Examples" and "C++ examples" could be two separate sections, or maybe two different subsections of "Examples".

**Comment by jcarpent** [comment]
Or maybe, for each example, we can have its Python and C++ versions, with a sort of unrolling box when clicking!

**Comment by nmansard** [comment]
At least for some examples, I would suggest to have the two codes side 
by side. I don't know how easy it would be to implement that, and 
whether we should have it for all examples.

BTW: I am not able to make doc on the last branch. I am investigating why.

**Comment by nim65s** [comment]
About the "examples" section, every file lies in https://github.com/stack-of-tasks/pinocchio/blob/topic/doc-v2/examples/ ; like https://github.com/stack-of-tasks/pinocchio/blob/topic/doc-v2/examples/a-model.cpp or https://github.com/stack-of-tasks/pinocchio/blob/topic/doc-v2/examples/a-model.py for the first ones.

We have to fill those files, they are included in the doxygen part, and we will also be able to use them as tests.

**Comment by nim65s** [comment]
I mean it doesn't matter how we will present those code samples, we can decide that later, whether they are show side-by-side, or in two separate sections, or in a fancy javascript/css way that allows a user to see only what he wants to see

**Comment by nmansard** [comment]
We have the structure ready. I close this issue.
