### ISSUE TITLE
Why is liegroup inside multibody?

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/pinocchio#517]
Hi all,

Is there a specific reason why liegroup was chosen to be put inside multibody?

**Comment by jcarpent** [comment]
It is because it is closed to joints. 
But normally, the basic Lie groups (SE(3),SO(3), etc) should be inside the spatial namespace.
And LieGroupMap should be related to Configuration and Vectorial Spaces.

**Comment by jcarpent** [comment]
I close the issue. If you need additional information feel free to open it again.
