### ISSUE TITLE
Coverage is buggy

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#525]
It seems that the coverage of Pinocchio is not well updated at each master branch pushes.
@nim65s Can you fix this issue?

**Comment by nim65s** [comment]
Are you talking about coveralls.io integration, or gitlab-ci ?

**Comment by jcarpent** [comment]
coveralls.io. But of course, we can synchronize gitlab with it, if you prefer.

**Comment by nim65s** [comment]
Ok, I'll look at it

**Comment by jcarpent** [comment]
Solved by #530!
