### ISSUE TITLE
[python] python test folder is broken

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/pinocchio#533]
The whole python folder is a mess. Most tests seem to be broken.
- One test did not even parse properly because of a typo. I discovered it while working on pull request #531, the correction is there, but that's the only thing I corrected
- Still, once the typo is corrected, tests.py does not even run to completion because some tests load the romeo model and the path is wrong, raising an uncaught exception. I corrected those errors, but I did not include the correction in the pull request, because I don't think romeo should be used in the tests anyway
- Once the above problems are corrected, lots of tests fail. I did not check the errors

By the way, I don't like the name "python", it's confusing, it is not clear that it only contains tests.

**Comment by nim65s** [comment]
Clément Bonnefont already worked on that, but I can't find it again.
Making this work has been in my todolist for a long time, but I'm surprised that there is not already an issue about that.

**Comment by jcarpent** [comment]
This is also due to the fact that Python is not more tested during the unit tests procedure.
It should be reactivated for producing much more stable releases.

**Comment by jcarpent** [comment]
Solved by #550
