### ISSUE TITLE
[doc] Create the overview section

### ISSUE THREAD

**Issue by nmansard** [stack-of-tasks/pinocchio#540]
The outline of the overview is 
- ABSTRACT (taken from SII paper)
- Installation link
- Simplest example with compilation command (load urdf and run rnea)
- More complete example with C++ and Python (load model and run a loop for an IK with 3D task)
- About Python wrapings (philosphy and example)
- How to cite Pinocchio
- Presentation of the content of the documentation.

I think all this subsection can be wrote at once by a single dev. Otherwise, please create subtask for concurrent allocation.

**Comment by nmansard** [comment]
I did a first version of the overview. Please review and validate.

**Comment by jcarpent** [comment]
I will have a look before the end of the week.

**Comment by gabrielebndn** [comment]
Solved by #541
