### ISSUE TITLE
dIntegrate_dq and dIntegrate_dv

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#542]
The two functions `dIntegrate_dq` and `dIntegrate_dv` correspond to the partial derivatives of the LOG of integrate operation with respect to the configuration and the tangent vector.

I will also implement a similar object but with respect to the coordinates of the configuration vectors resulting from the integration process. In other words, if we denote `y = x ⊕ dx` with x the configuration vector and dx a vector lying on its tangent, I'm going to implement dy/dx operation.

I would like to rename `dIntegrate_dq` and `dIntegrate_dv` by `dLogIntegrate_dq` and `dLogIntegrate_dv`. @jmirabel Do you agree with this modification?

**Comment by jmirabel** [comment]
I do not understand why you talk about the logarithm. `y = x ⊕ dx` does an exponential and `dIntegrate_dv` and `dIntegrate_dq` represent its derivative.

It could be interesting to add (or rename, I do not remember if I worked on it...) `dDifference_dq1` and `dDifference_dq2`, the derivatives of the log operation: `v = q1 - q2`. The names are open for discussion.

**Comment by jcarpent** [comment]
For instance,  in your implementation of `Jexp6` works from the tangent to the tangent.
What I mean is that I would like to have something like:
`M_next = M ⊕ dm` with `M_next`and `M` being two SE(3) elements and dm belongs to se(3).
and I would like to have an operator dM_next/dm when `dm` goes to zero.

You can go to the unit test to see https://github.com/stack-of-tasks/pinocchio/blob/054d4bdd2ecb066833f5ea9f00683ea23e7bbfc9/unittest/liegroups.cpp#L262 why I'm speaking about the partial derivatives of the log of the exponential mapping and not directly the partial derivatives of the components of the configuration vector with respect to the tangent around 0 (namely the identity).

**Comment by jmirabel** [comment]
> M_next = M ⊕ dm with M_nextand M being two SE(3) elements and dm belongs to se(3).
and I would like to have an operator dM_next/dm when dm goes to zero.

Let `M_next = f(M, v)`. Is this not `df/dv (M,0)` ?

This matrix maps velocities (relative to 0) in se(3) expressed in 1 with the velocity expressed in 0, with `M = ^0M_1`. If it does not, them it is a mistake.

**Comment by jmirabel** [comment]
> For instance, in your implementation of Jexp6 works from the tangent to the tangent.

I precise that it *should* also be the case for `dIntegrate_dq` and `dIntegrate_dv`. If it isn't, then it is a mistake.

**Comment by jcarpent** [comment]
From my side, when you write `M_next = f(M,v)`, `df/dv` provides the variation of `M_next` With respect to the variation of v around 0.

What you mention concerns the change of reference frame to express a quantity.
Do you agree ?

In this case, the naming you chose is confusing. I would suggest to modify the naming to reflect it.

**Comment by jmirabel** [comment]
> From my side, when you write M_next = f(M,v), df/dv provides the variation of M_next With respect to the variation of v around 0.

`df/dv` is itself a function a M and v so `df/dv(M,v)` gives the variation of M_next around M and v.

**Comment by jcarpent** [comment]
But, in your case, your provide the variation in the tangent of M_next, which is not directly the variation of the components of M_next.
While integrate goes from the tangent of SE(3) to SE(3) itself.
Then, it is mostly a naming and documentation issue.

**Comment by jmirabel** [comment]
I think putting the word *log* is a bad idea. It is very misleading.

After discussing with @florent-lamiraux : we expect the derivative to represent:

![image](https://user-images.githubusercontent.com/2388209/46740697-c6b0a100-cca3-11e8-897a-414d368ae3d2.png)
