### ISSUE TITLE
Build error related to fcl on pinocchio v1.3.2

### ISSUE THREAD

**Issue by aelkhour** [stack-of-tasks/pinocchio#566]
While trying to build pinocchio v1.3.2, I encountered this build error:

```
[  3%] Building CXX object src/CMakeFiles/pinocchio.dir/parsers/sample-models.cpp.o
/usr/bin/g++   -DWITH_URDFDOM -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion -fPIC -O3 -DNDEBUG   -o sample-models.cpp.o -c src/parsers/sample-models.cpp
sample-models.cpp: In function ‘void se3::buildModels::addManipulatorGeometries(const se3::Model&, se3::GeometryModel&, const string&)’:
sample-models.cpp:198:53: error: ‘Sphere’ is not a member of ‘se3::fcl’
                                   boost::shared_ptr<fcl::Sphere>(new fcl::Sphere(0.05)),
```

Is this the expected behavior when hpp-fcl (optional dependency) is not installed ?

**Comment by jcarpent** [comment]
Not expected at all. The addGeometry module should be dependent of HPP_FCL.
Thanks for raising this bug!

**Comment by gabrielebndn** [comment]
In the future, to avoid this kind of problems, maybe automated tests should also be run for build configurations where optional dependencies are not installed. @nim65s, what do you think?

**Comment by nim65s** [comment]
I think that at some point I already did that, but we changed our minds and I removed it.
I also think that we already run 10 tests that takes up to more than 2h.
And I also think that nobody run those tests anyway: https://gepgitlab.laas.fr/stack-of-tasks/pinocchio/pipelines the last one was 3 weeks ago.

**Comment by jcarpent** [comment]
#568 has normally fixed the issue. @aelkhour Can you check it?

**Comment by aelkhour** [comment]
@jcarpent Tested, it builds now :+1:

**Comment by jcarpent** [comment]
OK. Very nice.
I will make a new release now.
Thanks again for reporting the bug.
