### ISSUE TITLE
Taylor expansion threshold

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#581]
It appears that Jlog6 and Jlog3 do not have the same threshold for the Taylor expansion.
1e-4 for [Jlog6](https://github.com/stack-of-tasks/pinocchio/blob/912418bd2d1b707800162f131e2013d6acb3bfc6/src/spatial/explog.hpp#L488) and 1e-6 for [Jlog3](https://github.com/stack-of-tasks/pinocchio/blob/912418bd2d1b707800162f131e2013d6acb3bfc6/src/spatial/explog.hpp#L209).
It would be nice to make uniform the behavior of explog Taylor expansions.

@jmirabel and @florent-lamiraux What do you think?

**Comment by florent-lamiraux** [comment]
I agree.

**Comment by jmirabel** [comment]
I agree too.

**Comment by jcarpent** [comment]
Fixed by #584.
