### ISSUE TITLE
RNEA with floating base and contact forces

### ISSUE THREAD

**Issue by aelkhour** [stack-of-tasks/pinocchio#61]
Currently I can call se3::rnea(model, data, q,v,a) to compute the torques, but the external forces are not taken into account AFAIK.
If I want to run the RNEA for a floating base robot with external contact forces, is there currently a workaround, or do I have to implement a new function passing the forces as an argument?

**Comment by jcarpent** [comment]
You can easily add contact forces without writing any other functions.
You just need to compute the jacobian of contacts points and then adding the term J.transpose()*forces_ext to left hand-side term M*a + b

**Comment by aelkhour** [comment]
Thanks @jcarpent
