### ISSUE TITLE
[geometry] Templatization of GeometryModel by type in Pinocchio 2.0

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/pinocchio#613]
I don't find any discussion on this. If it is a known issue, I apologize.

In  Pinocchio 2.0, all classes and algorithms are templated. In particular, one parameter is the scalar type. However, I see `GeometryModel` and all related stuff are *not* templated by type, as they only work with `double`.
I think it only makes sense that `GeometryModel` also support other scalar types, given everything else does.

I took a look at hpp-fcl, and I see it only supports double, so I guess that's why.
But it also seems the current official version of FCL *does* support float (check https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/geometry/collision_geometry.h).

Do you agree this is a concern? How should this be handled? I see three options:
- Modify hpp-fcl directly to handle different scalar types (how long would it be?)
- Switching to FCL official version (possible? advisable?)
- Syncing hpp-fcl with the official FCL repository, as suggested in humanoid-path-planner/hpp-fcl#17 . (possible? advisable? too much work? that issue is two years old)

**Comment by jcarpent** [comment]
This indeed a known issue. We have already discussed that with @jmirabel and @florent-lamiraux.
They are planning to merge back to the official FCL repository but it will require some tough work.

**Comment by jcarpent** [comment]
I will close this issue as there is no feedback. Feel free to open it again.

**Comment by gabrielebndn** [comment]
I talked with @florent-lamiraux . He told he was rather thinking of implementing scalar type parametrization on hpp-fcl and keep it separate from the official FCL distribution
