### ISSUE TITLE
Minor pb.

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/pinocchio#621]
In https://github.com/stack-of-tasks/pinocchio/blob/d2026ed40574314da4f6b0e2d554a3b4a547332b/unittest/finite-differences.cpp#L37
should not it be model.nv instead of model.nq ?

**Comment by jcarpent** [comment]
You’re right. But it should not lead to any bug or segmentation fault because `nq > nv`. 
Do you have seg faults?

**Comment by olivier-stasse** [comment]
Dear Justin, that was just a very minor pb. Nothing is going wrong, btw I am very impressed by the coverage of pinocchio.

**Comment by jcarpent** [comment]
Fixed by #630. Thanks to @olivier-stasse for this report.
