### ISSUE TITLE
Good news, Travis now supports 16.04

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#629]
It would then be nice to make a smooth transition to this version of Ubuntu, 14.04 will be deprecated soon.
@nim65s Do you think that you can make it?

See https://docs.travis-ci.com/user/reference/xenial/ for further details.

**Comment by nim65s** [comment]
will do :)

**Comment by jcarpent** [comment]
Thank you very much!

**Comment by jcarpent** [comment]
Solved by #633.
