### ISSUE TITLE
How to use rnea with fext in python?

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/pinocchio#632]
I am trying to use `se3.rnea` with `fext` in python. How do I provide the argument corresponding to the external forces at the joints?

Currently I am giving the force vector in the form of a list, and it is not working.
`force_list = [se3.Force.Zero()]*robot.model.njoints`
`se3.rnea(robot.model, robot.data, q, v, ddq_ref, force_list)`

Concretely, what is the python equivalent of `container::aligned_vector<ForceDerived> & fext`?

**Comment by jcarpent** [comment]
@proyan You should use StdVec of Forces as mentioned in #626 
This should change with #555.

**Comment by proyan** [comment]
Thanks. This solves my problem for now. I'll close this issue.
