### ISSUE TITLE
Changing SquaredDistanceStep API

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/pinocchio#634]
Currently, `SquaredDistanceStep` takes a vector of double as return type and the index of the distance value to fill.
I would like to change this behavior to just return a scalar value of the computed distance.

@jmirabel What do you think of this change of API?

**Comment by jmirabel** [comment]
I think the pros are rather limited and the major cons is that users may have to change their code.

**Comment by jcarpent** [comment]
We can keep both also.

**Comment by jcarpent** [comment]
Yes, the pro is that it will simplify a bug fix ;)

**Comment by jmirabel** [comment]
I don't think it has much impact. Do as you want.
