### ISSUE TITLE
Encountering issues in examples

### ISSUE THREAD

**Issue by FCam1** [stack-of-tasks/pinocchio#642]
Hi,
I am trying to execute some examples like [this](http://homepages.laas.fr/nmansard/teach/robotics2018/tp3_example_mobilerobot_py.html) one but I have an error at the line `robot.increment(q,vq*DT)`. It seems that this function doesn't exist anymore, by which one can I replace it ? Thanks

**Comment by proyan** [comment]
`se3.integrate(robot.model, q, vq*DT)`

**Comment by proyan** [comment]
I'll close this.
