### ISSUE TITLE
Encountering issues in 1st example

### ISSUE THREAD

**Issue by FCam1** [stack-of-tasks/pinocchio#643]
Hi,
I am trying to execute this ["example"](https://github.com/stack-of-tasks/pinocchio/blob/f665f3f93669860beb8e80388ed3b52043ddd868/doc/d-practical-exercises/1-directgeom.md) but `visualRef  = robot.viewerNodeNames(visualObj)` doesn't exist anymore, by which one can I replace it ? I tried `viewerVisualGroupName` and others but is not working.
Thanks

**Comment by gabrielebndn** [comment]
Ho @FCam1, the method functionality has been replaced by
`robot.getViewerNodeName(geometry_object, geometry_type)`
For a visual object, as in your case, you should use
`robot.getViewerNodeName(visualObj, pinocchio.GeometryType.VISUAL)`
