### ISSUE TITLE
Error when trying to import pinocchio

### ISSUE THREAD

**Issue by Adrien987k** [stack-of-tasks/pinocchio#644]
Hi,

I am trying to import pinocchio on linux (ubuntu) but I get the following error : 

~~~
Traceback (most recent call last):
  File "load-urdf.py", line 6, in <module>
    import pinocchio as pin
  File "/opt/openrobots/lib/python2.7/site-packages/pinocchio/__init__.py", line 18, in <module>
    from pinocchio.robot_wrapper import RobotWrapper
  File "/opt/openrobots/lib/python2.7/site-packages/pinocchio/robot_wrapper.py", line 17, in <module>
    import libpinocchio_pywrap as se3
ImportError: libassimp.so.3: cannot open shared object file: No such file or directory
~~~

I installed pinocchio and configured environment variables exactly as it is described. Moreover assimp is installed on my system.

Thank you in advance.

**Comment by nim65s** [comment]
Hi @Adrien987k 

On my system on 16.04, where `import pinocchio as pin` works, I have:
```
$ ldd /opt/openrobots/lib/python2.7/site-packages/pinocchio/libpinocchio_pywrap.so | grep assimp
	libassimp.so.3 => /usr/lib/x86_64-linux-gnu/libassimp.so.3 (0x00007f1a49a7b000)
$ dpkg -S /usr/lib/x86_64-linux-gnu/libassimp.so.3
libassimp3v5: /usr/lib/x86_64-linux-gnu/libassimp.so.3
```

Can you check if you have something similar, and if the package `libassimp3v5` is correctly installed ?
If this does not leads you to the solution of your issue, can you provide your ubuntu version ?

**Comment by nim65s** [comment]
I assumed that you installed it with the APT package `robotpkg-py27-pinocchio`, otherwise, can you tell me which method did you use ?

**Comment by jcarpent** [comment]
@Adrien987k everything goes fine?

**Comment by Adrien987k** [comment]
Yes, I am sorry I forgot to reply.

FinaIly, I am using the virtual machine where everything is already installed.

**Comment by jcarpent** [comment]
Ok. Sounds good.
