### ISSUE TITLE
non-correspondence between number of joints and number of neutralConfiguration parameters

### ISSUE THREAD

**Issue by lliill** [stack-of-tasks/pinocchio#646]
We work with NAO in inverse kinematics. 
NAO have 44 joints while the `model.neutralConfiguration` gives 65 parameters. There is a non-correspondence between number of joints and number of neutralConfiguration parameters, so we cannot program the next step by setting each joint.

**Comment by jcarpent** [comment]
With the model I have in the attached file, everything goes well. Which model of Nao are you using?

[nao.urdf.zip](https://github.com/stack-of-tasks/pinocchio/files/2776440/nao.urdf.zip)

**Comment by Adrien987k** [comment]
We have a NAO h25V33,

The problem is that a configuration is of size 65 and there are 44 joints. We want to find out which value of the configuration correspond to wich joint. Is there an easy way to do that with pinicchio ?
