### ISSUE TITLE
Definition of neutral configuration

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/pinocchio#656]
We currently have two definition for a neutral configuration for a model.
1) model::neutralConfiguration, which can be set by srdf, and is being used for loading the half-sitting posture of a robot.

2) pinocchio::neutral(model) in joint-configurations.hpp, which returns the equivalent of zero for the joint manifold.

In my opinion, we should change one of these names. Both of these could be used for either of the purposes.

I would recommend changing neutralConfiguration to something else.

**Comment by jcarpent** [comment]
We already discussed this point with @jmirabel and we decided to modify the neuralConfiguration.
I would be more to remove it completely and let the SRDF parser returns the value as a ConfigVector type.

**Comment by proyan** [comment]
I would be okay with this change.
However, we still need to give a name to what used to be neutralConfiguration for loading with srdf.
If you are not saving it in model anymore, I would recommend defaultConfiguration as the replacement.

**Comment by jcarpent** [comment]
I would prefer `referenceConfigurationVector`but this one should not be in Model class.

**Comment by proyan** [comment]
I like that name.

I'll put neutralConfiguration and the srdf function to deprecated, and create a PR with the new names.

**Comment by jcarpent** [comment]
OK. Sounds good to me!

**Comment by nmansard** [comment]
If not added to model, where do you want to put it?

**Comment by jcarpent** [comment]
I think this information should not be inside model because you may have various referenceConfigurationVector. But we may provide just a function to load it from a SRDF file.

**Comment by jmirabel** [comment]
For me, referenceConfigurationVector means there are several configurations. I don't think Vector adds anything. I would name it referenceConfiguration(s) depending on the number of reference configuration.

If there are several configurations, I think I would store them into a map in order to assign a name to each.

Having a function to extract it from a SRDF is not convenient. It forces developers to store somewhere either the filename or the configurations. In most places where you want this configuration, you don't have the filename.

**Comment by proyan** [comment]
I think srdf files are meant to be customizable by the developers. So saving this map `name->configuration` in an srdf file, and making this file available in the <robot>-description should not be a  problem.
As developers, we are storing the urdf filenames as well when we load a robot. i don't see why srdf should be different.

**Comment by jcarpent** [comment]
@proyan Can you take in charge the requested modifications?

**Comment by proyan** [comment]
I am not sure if we all agree on the same modifications. Are you okay if I implement the suggestion of @gabrielebndn?

**Comment by jcarpent** [comment]
I think we all agree that `neutralConfiguration`is now deprecated, and should be replaced by something much more generic like referenceConfigurations.
I think the idea of @jmirabel of having a map<string,ConfigVectorType> is nice and very flexible.

Then, the loading of a reference configuration vector from a SRDF file should take as input the name of the reference configuration inside the SRDF file + the name of the configuration to store inside the new map.

**Comment by gabrielebndn** [comment]
@jcarpent so you would keep the map<string,ConfigVectorType> as a variable inside the Model class?

**Comment by pFernbach** [comment]
Related to https://github.com/humanoid-path-planner/hpp-pinocchio/issues/83 in hpp-pinocchio. I am also in favor of a map name->configuration and a method that initialize this map with all the group_state tags defined in the srdf.

**Comment by jcarpent** [comment]
@pFernbach It sounds reasonable.

**Comment by jcarpent** [comment]
> @jcarpent so you would keep the map<string,ConfigVectorType> as a variable inside the Model class?

@gabrielebndn Sorry for the late reply, but currently this is the only option I see.

**Comment by proyan** [comment]
Ok. I'll implement this change.

**Comment by jcarpent** [comment]
Solved by #666
