### ISSUE TITLE
Joint-configuration algorithms are performing memory allocation

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/pinocchio#658]
A lot of emphasis is put on the idea that Pinocchio algorithms *never* perform any memory allocation, relying on storage inside `Data` or in the user passing the required memory,  as in the case of `getJointJacobian(model, data, jointId, rf, J)`, where the result is written in matrix `J`.

However, pretty much all algorithms contained in [joint-configuration.hpp](https://github.com/stack-of-tasks/pinocchio/blob/devel/src/algorithm/joint-configuration.hpp) do not follow this pattern. Instead, the result vector is allocated and returned.

Should we adopt a pattern which mimics the Jacobian case? Do you think it is worth it? In this case, should we deprecate the current signatures, or leave them as a more friendly option? This last question arises from the fact that for instance in most cases `randomConfiguration` and `neutral` are just used as one-shot calls with the specific purpose of initializing a vector with a bogus value at the beginning of a program, and forcing the user to pre-allocate their memory would just make their use clunkier with no real benefit.

**Comment by jcarpent** [comment]
For simplicity, both should exist, an extended signature with output results in the arguments, and the simpler one, with the default return value. What do you think?

**Comment by gabrielebndn** [comment]
I agree

**Comment by jcarpent** [comment]
@gabrielebndn Can you take in charge the corresponding PR?

**Comment by gabrielebndn** [comment]
Ok. Will do it as soon as possible

**Comment by jcarpent** [comment]
solved by #679
