### ISSUE TITLE
Compiling pinocchio v2.0.0 and RobotWrapper

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/pinocchio#660]
RobotWrapper doesn't work with default cmake settings for pinocchio v2.0.0. compilation. Indeed, pinocchio (Python) module haven't functions such as `buildGeomFromUrdf`. 

I figured out that it's needed to enable BUILD_UTILS in the cmake setup. I wonder if there is any reason for this, or if this is a compilation bug.

**Comment by jcarpent** [comment]
Do you have installed hpp-fcl?

**Comment by cmastalli** [comment]
No, I don't

**Comment by jcarpent** [comment]
`buildGeomFromUrdf` is only compiled if hpp-fcl is found. Because it loads meshes and so on. But, the `RobotWrapper` should still work.

**Comment by jcarpent** [comment]
Can you provide a self-content example?

**Comment by jcarpent** [comment]
@cmastalli do you still face this issue?

**Comment by cmastalli** [comment]
I just want to report that I don't face this issue if I install hpp-fcl.
