### ISSUE TITLE
ssh-path in .gitmodules limits easy access for certain users.

### ISSUE THREAD

**Issue by markusgft** [stack-of-tasks/pinocchio#667]
Hi all,
when cloning the source-code of the current master, certain users may encounter the following problem: currently, there is a SSH-address hard-coded in ".gitmodules", namely
`
url = git://github.com/jrl-umi3218/jrl-cmakemodules.git
`
From within some institutions and universities, it is impossible to access external sources via SSH. It would be great if you could change the URL to
`url = https://github.com/jrl-umi3218/jrl-cmakemodules`, which avoids unnecessary overhead when cloning pinocchio.

Keep up the great work! :)

**Comment by jcarpent** [comment]
Ok. Sounds reasonable.
I will fix it now.

**Comment by jcarpent** [comment]
Solved by #669.

**Comment by nim65s** [comment]
For me, the solution is `url = ../../jrl-umi3218/jrl-cmakemodules`
This way, if you use `git clone --recursive https://github.com/stack-of-tasks/pinocchio` the submodule will be cloned in https, and if you use `git clone --recursive git@github.com:stack-of-tasks/pinocchio` the submodule will be cloned in ssh.

**Comment by jcarpent** [comment]
Looks fine to me too.
I will update my PR with it. @nim65s Thanks for this nice detail.

**Comment by jcarpent** [comment]
Solved by #670.

**Comment by markusgft** [comment]
Thanks for addressing this issue. Would you mind, however, to also cherry-pick this to the master branch?

**Comment by jcarpent** [comment]
@markusgft Sorry, I did not see your comment. I will do that tomorrow.

**Comment by jcarpent** [comment]
@markusgft Done!
