### ISSUE TITLE
Passing static constructors of Eigen-types to pinocchio methods

### ISSUE THREAD

**Issue by markusgft** [stack-of-tasks/pinocchio#668]
Hi all,
this is not an urgent issue, but for the sake of documentation, let me note it here:

For newer Eigen versions (tested with 3.3.5 and 3.3.3), there is a compilation error when passing statically constructed arguments to pinocchio methods. 

For example, if you try to compile
`pinocchio::forwardKinematics(model_, data_, JointPosition_t::Zero());`

you will obtain the compiler-error
`
/usr/local/include/pinocchio/multibody/joint/joint-free-flyer.hpp:244:95: error: ‘Options’ is not a member of ‘Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, 7, 1, 0, 7, 1> >’
       typedef typename Eigen::Quaternion<typename ConfigVector::Scalar,ConfigVector::Options> Quaternion;
                                                                                               ^
/usr/local/include/pinocchio/multibody/joint/joint-free-flyer.hpp:245:44: error: ‘Options’ is not a member of ‘Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::Matrix<double, 7, 1, 0, 7, 1> >’
       typedef Eigen::Map<const Quaternion> ConstQuaternionMap;
`

If you instead use the argument
`const JointPosition_t zeroPos = JointPosition_t::Zero();
pinocchio::forwardKinematics(model_, data_, zeroPos);`
compilation works fine.

**Comment by jcarpent** [comment]
Ok. I won't have time to fix today, but I will do it in the next few days.
@markusgft Thanks a lot for raising this important issue.

**Comment by jcarpent** [comment]
solved by #689.
