### ISSUE TITLE
Python unit tests failing in non-Release mode

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/pinocchio#677]
Python unit tests [bindings_com.py](https://github.com/stack-of-tasks/pinocchio/blob/devel/unittest/python/bindings_com.py), [bindings_dynamics.py](https://github.com/stack-of-tasks/pinocchio/blob/devel/unittest/python/bindings_dynamics.py) and [explog.py](https://github.com/stack-of-tasks/pinocchio/blob/devel/unittest/python/explog.py) seem to pass in Release mode, but they fail badly in other compilation modes.

In particular:  when assertions are enabled (not only in Debug mode, tested on Mac OS 10.11), `bindings_com.py` and `bindings_dynamics.py` raise an assertion.
In Debug mode, additionally, `explog.py` segfaults (tested on Ubuntu 16.04).

Although the tests nominally work in Release mode, these error might reflect some subtler problems which were somehow not appearing in the unit tests, therefore it is worth to investigate this.

I will take a look

Related to #673

**Comment by jcarpent** [comment]
This also means that we need to enforce the debugging check with Travis too.

**Comment by gabrielebndn** [comment]
I do agree

**Comment by jmirabel** [comment]
To avoid making Travis take longer by increasing the number of compilations, you also have the possibility to force the compilation flags.

Something like `-O3`, without `-DNDEBUG` and `-g`, would keep the assertions while still doing some optimization. It should do the work.

**Comment by gabrielebndn** [comment]
I think @jmirabel's solution is a good compromise. At least the assertions will be checked.

**Comment by jcarpent** [comment]
I would add that using O3 and no hard compilation flags won't provide the computation tree, and they may lead to different results.
I think it would be better to add also the Debug flag in Travis too, at least on 16.04. By the way, we may think to stop 14.04, as it will be deprecated in two months now.

**Comment by gabrielebndn** [comment]
Solved by #678
