### ISSUE TITLE
examples/overview-simple.cpp does not compile

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/pinocchio#681]
After the recent commits, examples/overview-simple.cpp is not compiling anymore.
I get the error: fatal error: cppad/cppad.hpp: No such file or directory

I believe cppad needs to be linked.

**Comment by jcarpent** [comment]
@proyan Thanks for raising this issue.
I found the bug, I will fix it asap.

**Comment by jcarpent** [comment]
Fixed by #688.
