### ISSUE TITLE
Why do we have the JointData::F variable?

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/pinocchio#683]
This is just a small question. Why do we have the F variable inside some JointData classes? I tried to look for the use, but couldn't find one. Perhaps I haven't been thorough enough.

Is it useful?

**Comment by jcarpent** [comment]
We don't need it at all. It has been implemented at the origin of the project.
It should be removed in a future release.

**Comment by proyan** [comment]
Ok. Thanks. I'll close this.
