### ISSUE TITLE
Could you release the examples?

### ISSUE THREAD

**Issue by littleggghost** [stack-of-tasks/pinocchio#699]
Hi,  @jcarpent  @nim65s 
The examples under /pinocchio/examples path you give now are empty, and I hope you can release them as soon,  especially the c++ version!
![pino](https://user-images.githubusercontent.com/5058791/53282552-264faa80-3774-11e9-9a5f-381d9f911905.PNG)

By the way, I really hope the v2.0.0 version with robotpkg can be released too.

Best regards!

**Comment by nim65s** [comment]
Hi @littleggghost,

Those examples have not been written yet. We are trying to find a way to get them ASAP. Meanwhile, you can maybe have a look at the practical exercises:
- https://github.com/stack-of-tasks/pinocchio/tree/master/doc/d-practical-exercises for the source
- http://projects.laas.fr/gepetto/doc/stack-of-tasks/pinocchio/master/md_doc_d-practical-exercises_intro.html for a built version

About the second point, cf. #686

**Comment by littleggghost** [comment]
Thanks for your quick reply! @nim65s 
The practical exercises are all python type, and I wonder if there have some c++ exercises?
And, I really want to confirm the release date of examples, one month, or half a year? 
Regards!

**Comment by nim65s** [comment]
Hopefully between one month and half a year. @nmansard thinks we should organize some kind of hackathon to gather people to write those examples. We just need to find a good date for it.

**Comment by littleggghost** [comment]
It's my great honor to participate in this young project.
