### ISSUE TITLE
Error about createData() in practical-exercises?

### ISSUE THREAD

**Issue by littleggghost** [stack-of-tasks/pinocchio#707]
Hi, all
I do the practical-exercises in [1.1) Creating and displaying the robot](http://projects.laas.fr/gepetto/doc/stack-of-tasks/pinocchio/master/md_doc_d-practical-exercises_1-directgeom.html)
I meet an error:
`Traceback (most recent call last):
  File "exercise_1_1.py", line 29, in <module>
    robot = RobotWrapper(URDF, [PKG])
  File "/usr/local/lib/python2.7/site-packages/pinocchio/robot_wrapper.py", line 52, in __init__
    self.data = self.model.createData()
AttributeError: 'str' object has no attribute 'createData'`
Maybe the robot_wrapper.py is the old version? I'm sure I have compiled the v2.0.0 and installed it successfully.

**Comment by jcarpent** [comment]
Yes, the code needs to be updated according to the new signature of the RobotWrapper constructor.

**Comment by littleggghost** [comment]
Then where can I find the newest code?

**Comment by jcarpent** [comment]
We just need to update the exercises. Can you do it please?

**Comment by littleggghost** [comment]
I'm tring to do this. While I learn how to use pinocchio, I meet quite much errors. 
I wish the bug issues can be solved so that I can proceed.

**Comment by littleggghost** [comment]
For this error, where should I start? or who could I contact that in charge of this before?

**Comment by littleggghost** [comment]
Or where to find the related function of `self.model`? It seems the functions are under libpinocchio_pywrap.so file.

**Comment by littleggghost** [comment]
I got it. The bug is right for v1.3.3, but for v2.0.0, it should be:
```
model_path = "the path to ur5"
mesh_dir = model_path
urdf_filename = "ur5_gripper.urdf"
urdf_model_path = model_path + "/ur5_description/urdf/" + urdf_filename
robot = RobotWrapper.BuildFromURDF(urdf_model_path, [mesh_dir], se3.JointModelFreeFlyer())
```

**Comment by littleggghost** [comment]
Should this correction make by you or a pull request by me?

**Comment by littleggghost** [comment]
By the way, there are still some changes should make in `ur5_gripper.urdf` and `ur5.urdf` files.
`ur_description` should be replaced as `ur5_description`.

**Comment by jcarpent** [comment]
You may open a PR and I will review it. It will avoid being overloaded for us.

**Comment by jcarpent** [comment]
@littleggghost Can you provide the fix you suggested last week?

**Comment by littleggghost** [comment]
I noticed that this changes belong to `robotpkg-ur5-description`, and I should't make a PR here.
I post it here just for reference.
[urdf.zip](https://github.com/stack-of-tasks/pinocchio/files/2934176/urdf.zip)
