### ISSUE TITLE
Segmentation fault when using computeCollision() or computeCollisions()?

### ISSUE THREAD

**Issue by littleggghost** [stack-of-tasks/pinocchio#708]
Hi
While I do this  [5.0) prerequisites](http://projects.laas.fr/gepetto/doc/stack-of-tasks/pinocchio/master/md_doc_d-practical-exercises_5-planner.html) in python,  like calling:
`se3.computeCollision(robot.collision_model, robot.collision_data, 2)` or
`se3.computeCollisions(robot.collision_model, robot.collision_data, False)`
the program only crashed with `Segmentation fault (core dumped)`. 
I even don't know what happens. 
And should two objects bounce off when collision happens? Because I didn't find the forces should generated in corresponding file.

**Comment by jcarpent** [comment]
Good catch. I will work on it next week. Thanks @littleggghost for this nice and helpful feedback.

**Comment by jcarpent** [comment]
@littleggghost I have pushed a new Python example doing collision checking. Can you try it?
See this README: https://github.com/stack-of-tasks/pinocchio/tree/devel/examples/python

**Comment by littleggghost** [comment]
After a little modify for v2.0.0, it meets an error:
```
  File "collision_detection.py", line 23, in <module>
    geom_model = pin.buildGeomFromUrdf(model,urdf_model_path,pin.GeometryType.COLLISION)
ValueError: Mesh package://romeo_description/meshes/V1/collision/TrunkYaw.dae could not be found.
```
I'm sure the dae file is exists.

**Comment by littleggghost** [comment]
By the way, it will be better if it can add a ground collision box and be visualized on gepetto-viewer.

**Comment by jcarpent** [comment]
It is very hard to identify such a bug, as it is working on a clean installation.
can you show that the file exists?
By the way, I won't be able to provide additional help. I think this is the max that I can do remotely.

**Comment by jcarpent** [comment]
> By the way, it will be better if it can add a ground collision box and be visualized on gepetto-viewer.

Sorry, but I cannot provide more help for this feature. The only thing I can tell you is I'm willing to help you build such an example.

**Comment by littleggghost** [comment]
You can check this pic:
![romeo](https://user-images.githubusercontent.com/5058791/53809056-cf757c80-3f8e-11e9-8ec1-b1c5992b784a.PNG)

**Comment by jcarpent** [comment]
You've commented line 17  the correct line and put another one.

**Comment by littleggghost** [comment]
Or I will get:
`Traceback (most recent call last):
  File "collision-detection.py", line 17, in <module>
    geom_model = pin.buildGeomFromUrdf(model,urdf_model_path,[model_path],pin.GeometryType.COLLISION)
Boost.Python.ArgumentError: Python argument types in
    pinocchio.libpinocchio_pywrap.buildGeomFromUrdf(Model, str, list, GeometryType)
did not match C++ signature:
    buildGeomFromUrdf(pinocchio::ModelTpl<double, 0, pinocchio::JointCollectionDefaultTpl> Model to assosiate the Geometry, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filename (string), pinocchio::GeometryType Geometry type, boost::shared_ptr<hpp::fcl::MeshLoader> Mesh loader)
    buildGeomFromUrdf(pinocchio::ModelTpl<double, 0, pinocchio::JointCollectionDefaultTpl> Model to assosiate the Geometry, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > filename (string), std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > package_dirs (vector of strings), pinocchio::GeometryType Geometry type, boost::shared_ptr<hpp::fcl::MeshLoader> Mesh loader)
    buildGeomFromUrdf(pinocchio::ModelTpl<double, 0, pinocchio::JointCollectionDefaultTpl>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Model to assosiate the Geometry, pinocchio::GeometryType filename (string))
    buildGeomFromUrdf(pinocchio::ModelTpl<double, 0, pinocchio::JointCollectionDefaultTpl>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Model to assosiate the Geometry, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > filename (string), pinocchio::GeometryType package_dirs (vector of strings))
`

**Comment by jcarpent** [comment]
Have you reinstalled pinocchio from devel?

**Comment by littleggghost** [comment]
I install v2.1.0 today through robotpkg

**Comment by jcarpent** [comment]
Ok. You can then replace `[model_path]` by `pin.utils.fromListToVectorOfString([model_path])`.
The current devel branch is in advance and it is now more flexible.

**Comment by littleggghost** [comment]
I modified two lines here and it has no error now:
1. change `pin.removeCollisionPairs(model,geom_model,srdf_model_path)`
to             `pin.removeCollisionPairs(model,geom_model,srdf_model_path, True)`
2. change `pin.loadReferenceConfigurations(model,srdf_model_path)`
to             `pin.loadReferenceConfigurations(model,srdf_model_path, True)`
Is there some packages version is out of date?

**Comment by littleggghost** [comment]
I will keep exploring pinocchio!

**Comment by jcarpent** [comment]
You have to install the devel version, which supports this new signatures.

**Comment by nim65s** [comment]
Or wait for a new release ;)

**Comment by jcarpent** [comment]
I close this issue as it seems to be solved.
