### ISSUE TITLE
robot.collisionPairs.append() can't attach witness points to body?

### ISSUE THREAD

**Issue by littleggghost** [stack-of-tasks/pinocchio#731]
Hi
In chapter [4.3) Collision checking](http://projects.laas.fr/gepetto/doc/stack-of-tasks/pinocchio/master/md_doc_d-practical-exercises_4-dyn.html)
After I add the witness points, I find they did't move with links, here the pics:
before apply torque:
![coll0](https://user-images.githubusercontent.com/5058791/54021835-f967b280-41cb-11e9-8f2a-4f057ddea38a.PNG)
after apply torque:
![coll1](https://user-images.githubusercontent.com/5058791/54021840-fd93d000-41cb-11e9-93e6-776c8e44b732.PNG)
Seems I should call another function except that?

**Comment by jcarpent** [comment]
@nmansard As you are the author of these exercises, can you look at this display problem?

**Comment by littleggghost** [comment]
Hi, @jmirabel 
Have you ever meet this problem? Hope you can give me an advice, thanks.

**Comment by littleggghost** [comment]
Finally, I found function robot.visuals.append() works.
