### ISSUE TITLE
Documentation not being displayed properly in Chrome - 16.04

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/pinocchio#784]
Chrome: Version 72.0.3626.96
Pb: After 
```
make doc
```
when going to 
```
doc/doxygen-html/md_doc_a-features_a-spatial.html
```
I got the following blank page:
![Screenshot from 2019-04-25 13-03-06](https://user-images.githubusercontent.com/400341/56731465-cb7a0580-675a-11e9-816f-e5756aa5f784.png)

Where as it is displayed properly on Firefox.
Any idea why ?
Branch devel, commit 3ffa704d9612dc87fbdbbeeda8df8d070f8dd0d3

**Comment by gabrielebndn** [comment]
This is surprising because the doc is working properly in Chrome on my (old) Macbook (El Capitan).

**Comment by jmirabel** [comment]
The developer tools contains a tab that lists the errors. Can you provide them ?

**Comment by olivier-stasse** [comment]
Nothing more than this:
```
MathJax.js:32 WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips.
```
Not sure that this is really related.

**Comment by jcarpent** [comment]
I will close this issue. @olivier-stasse feel free to reopen it if needed.
