### ISSUE TITLE
Turn BUILD_UNIT_TESTS option OFF by default?

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/pinocchio#827]
Unit tests are most interesting to Pinocchio developers and CI, but less so for end users/consumers of the library and take lots of time and memory to compile. Would it be an acceptable suggestion to switch the default behaviour of `BUILD_UNIT_TESTS` to `OFF`?

**Comment by jcarpent** [comment]
Yes, this is fine for me.

**Comment by jcarpent** [comment]
Solved by #829
