### ISSUE TITLE
Eigenpy version mismatch

### ISSUE THREAD

**Issue by aelkhour** [stack-of-tasks/pinocchio#84]
Pinocchio cannot be built with eigenpy 1.2.0 on the devel branch (tested on f2fdcdc609df9c92dd3c81facbc01604a2b05557). The minimal version must be set to 1.3.0.

**Comment by jcarpent** [comment]
You're right.
The bug comes directly from EigenPy version <= 1.2.0. I change it asap.

Thanks for this useful remark.

**Comment by jcarpent** [comment]
Fixed with #85

**Comment by aelkhour** [comment]
Thanks!
