### ISSUE TITLE
Why doesn't getJointAccelerationDerivatives compute v_partial_dv?

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/pinocchio#855]
Hi guys,

I was looking this detail inside the paper and I didn't find it. Is there a mathematical reason for this? If not, I suggest to retrieve this partial derivatives too. Otherwise we need to run getJointVelocityDerivatives, which I assume it's not the most efficient way of doing things.

Yours,
Carlos

**Comment by jcarpent** [comment]
This is because v_partial_dv = a_partial_da. This is written in the documentation of the function.

**Comment by cmastalli** [comment]
Thank you for the clarification
