### ISSUE TITLE
forwardDynamics is not very descriptive

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/pinocchio#861]
Hi guys,

I proposed  to rename this class, which in my humble opinion doesn't have a proper name. For instance, "forward dynamics" is a very broad term and maybe the first thing that comes to our minds is the free case. On the other hand, "contactForwardDynamics" or any reference to contacts is wrong since it doesn't model neither a contact.

My suggestion is to rename the class as `forwardDynamicWithHolonomicConstraints` or `holonomicConstrainedForwardDynamics`. I know the name is too long, but we can figure out a shorter version  of it. In the same vein, I would rename the file to holonomic-forward-dynamics (or something like that).

I believe we should work on different contact dynamics in Pinocchio, and having a good naming of classes and files is important.

What do you think about it? I could handle this if there is consensus.

Yours,
Carlos

**Comment by jcarpent** [comment]
> My suggestion is to rename the class as `forwardDynamicWithHolonomicConstraints` or `holonomicConstrainedForwardDynamics`. I know the name is too long, but we can figure out a shorter version of it. In the same vein, I would rename the file to holonomic-forward-dynamics (or something like that).

First of all, you are talking about functions and not classes.
Your suggestions are not totally correct as the original `forwardDynamics` can deal with both holonomic and non-holonomic constraints. As I already told you during private discussions, the original naming of forwardDynamics is correct in a similar way we can call ABA forwardDynamics. But I do agree on the fact that this naming may not be precise enough. 

I'm currently working on the refactoring of all this code to deal with hard contact models. And I change the current naming to `constrainedForwardDynamics` which seems the correct and generic name for such kind of function.

As this is an ongoing process on a private branch (which be made public), I will close this issue.
Feel free to reopen it if you **really** feel that this is necessary.
