### ISSUE TITLE
No MathJax rendering anymore

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/pinocchio#865]
A small issue:
for some reason the documentation at the following address:
https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/
does not render the mathjax formulas anymore.

**Comment by jmirabel** [comment]
The reason is this: https://www.mathjax.org/cdn-shutting-down/

**Comment by jcarpent** [comment]
Solved by #866

**Comment by jcarpent** [comment]
@olivier-stasse Thanks for the raising and @jmirabel thanks for the quick fix.
