### ISSUE TITLE
Adding damping factor to impulse dynamics

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/pinocchio#875]
It would be great to have a damping factor in the impulse dynamics. I could quickly add it if @jcarpent is OK with this.

**Comment by jcarpent** [comment]
In similar way of constrained Dynamics you mean?

**Comment by cmastalli** [comment]
Yes, I do

**Comment by jcarpent** [comment]
Sure. Please you can go ahead.

**Comment by jcarpent** [comment]
Solved by #876
