### ISSUE TITLE
Coverage - Needs of more unit tests

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/pinocchio#89]
Dear all,
To have a better view of the code state so that we can improve the release process,
I made the link to coveralls. I apologize for the rough process. 
According https://coveralls.io/builds/4952648 they are three files which are not tested at all:
joint_planar.hpp joint_dense.hpp constraint.hpp.
It would be nice to have unit test related to those files.

**Comment by jcarpent** [comment]
Thanks Olivier for this great job!
Concerning those files, they are currently not used at least for joint_dense.hpp and constraint.hpp.
I will do my best to integrate some unit test around joint_planar.hpp asap.

**Comment by jcarpent** [comment]
And also, all the python bindings are not tested at all. But it won't appear in the coverage test, because they are not compiled on travis.
