### ISSUE TITLE
python impulse model

### ISSUE THREAD

**Issue by ddliugit** [stack-of-tasks/pinocchio#906]
I am working on a project of impulse model, how to use impulse model in python with Pinocchio?

**Comment by jcarpent** [comment]
Dear @ddliugit,

Without more details, it is hard for Pinocchio's support team to provide guidance.
You may have a look to the tutorials of Pinocchio which seems to a good starting point: https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/md_doc_d-practical-exercises_1-directgeom.html

**Comment by ddliugit** [comment]
I thought you implemented the model in rigid body dynamics algorithms. Where can I find the relevant Pinocchio code in that section?

**Comment by jcarpent** [comment]
You can find the relevant details here: https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/namespacepinocchio.html#a3b3ac8f8d2b0bb7ec4aeea811d5d1800

The code in Python follows the same signature as in C++.

**Comment by ddliugit** [comment]
Thanks. Really appreciate your help.

**Comment by jcarpent** [comment]
@ddliugit Your welcome.

**Comment by gabrielebndn** [comment]
> The code in Python follows the same signature as in C++.

@jcarpent not exactly. For the curent version, v2.1.8, Python is using the convention of setting `q=None` in order to employ the variant with no arguments. , which was removed and replaced by a signature more similar to C++ by #902 (a non-backward-compatible change, by choice).

If you want to avoid that some people start employing the removed signature, I suggest a new release

**Comment by ddliugit** [comment]
@jcarpent can you help release a new version for install on Mac? I need q for calculation.

**Comment by jcarpent** [comment]
Could do that indeed.

**Comment by jcarpent** [comment]
@ddliugit How do you install it on OSX?

**Comment by ddliugit** [comment]
brew install pinocchio

**Comment by ddliugit** [comment]
can you update homebrew formula to link to new release

current on Mac, it is still 2. 1. 8

**Comment by jcarpent** [comment]
Done!

**Comment by jcarpent** [comment]
It should work already.
You just need to do `brew install pinocchio --build-from-source`

**Comment by ddliugit** [comment]
That's good news!
I will test it after installing Catalina.
