### ISSUE TITLE
hide mimicJoints in model

### ISSUE THREAD

**Issue by alexswerner** [stack-of-tasks/pinocchio#923]
Hi,

when importing a model with buildModelFromUrdf, i get all joints which are marked as mimicJoints listed as joints. This is e.g. used in the romeo model distributed with pinocchio, typically for coupled finger joints. Is there a way to remove these joints/links from the model to (a) reduce computation time (b) make the number of joints and actuators match. I think that would simplify development. A function like:
model.pruneSubtree(joint_idx) would be a possible solution.

Cheers,
Alex

**Comment by jcarpent** [comment]
Hi @alexswerner,

Your request is very similar to the one from @markusgft in #905. If you confirm, I will try to implement it tomorrow. Is it fine for you?

**Comment by alexswerner** [comment]
Great, i will comment on #905. Thanks

**Comment by jcarpent** [comment]
Duplicate with #905.
