### ISSUE TITLE
Parser urdf

### ISSUE THREAD

**Issue by florent-lamiraux** [stack-of-tasks/pinocchio#93]
In its current version, the urdf parser is not able to understand url starting by "package://"
Moreover, it seems that srdf files are not parsed.

**Comment by aelkhour** [comment]
@florent-lamiraux Do you think there's a solution for the `package://` issue without adding a dependency to ROS?

+1 for srdf.

+1 as well for [sdf](http://sdformat.org/spec), the official format for Gazebo simulator. It offers slightly more options than urdf, such as adding parallel spring-dampers on the joints. Although outside the current scope of pinocchio, the model does not need to be a kinematics tree, it can also be a DAG for parallel robots.

**Comment by florent-lamiraux** [comment]
I think the best solution is to parse ROS_PACKAGE_PATH environment variable in C++ and to search in the corresponding directories for the files. The way ROS proceeds is not very clear and fails sometimes to find new directories because the right setup.sh has not been resourced after installation.

**Comment by jcarpent** [comment]
The final idea is then:
- Add method to directly read a SRDF file to activate collision pairs.
- Add function to locate model and its data (URDF, SRDF, meshes, etc) by only the robot name and seek in $ROS_PACKAGE_PATH 

Have you other requests?

**Comment by jcarpent** [comment]
Solved by #110.
