### ISSUE TITLE
Can pinocchio calculate the minimum distance between two meshes

### ISSUE THREAD

**Issue by ddliugit** [stack-of-tasks/pinocchio#955]
I am working on an optimization problem which need a kinematic constraint of calculating the minimum distance between two meshes.

Can I use _pinoccchio_ to get the minimum distance between two meshes for a certain configuration `q`?

like so:

`x = minimumdistance(robot, data, q, partId1, partId2)`

**Comment by jmirabel** [comment]
You have *computeDistances(model, data, geomModel, geomData, q)*. Then you have to find the minimum distance yourself from the distance results (geomData.distanceResults).

Mind that you will have to filter the collision pairs in order to have relevant results.

**Comment by ddliugit** [comment]
Thanks for your timely reply!

I check the function and find cpp version of that function. I am using python right now and do you have any plan to add that function in python version?

Another issue is that I also need to calculate the derivative of distance with respect to robot configuration, would that be possible in Pinocchio?

**Comment by jmirabel** [comment]
If you have the source, it shouldn't be hard to expose computeDistances.

The DistanceResult objects of hpp-fcl, in geomData.distanceResults, contains all the info you need to compute that derivative. I doubt the algorithm is implemented in Pinocchio but it isn't hard to write.

**Comment by jcarpent** [comment]
For the second question, is just related to the Jacobian of the witness points, so its very easy to write by hand ;) I do not think that a dedicated function is needed currently, but we may think to add it in Future.

**Comment by ddliugit** [comment]
Thanks, all.

@jcarpent I see. I just don't think too much about that. The derivative of the distance between one point on the robot and the ground can be considered the derivative of pose of that point with respect to `q`, which equals to the Jacobian of that point. 

Is that what you want to say?

**Comment by gabrielebndn** [comment]
@ddliugit, `computeDistances` is already exposed in Python

**Comment by ddliugit** [comment]
I see that function in expose-geometry.cpp.

Thanks for your reminder.

**Comment by jcarpent** [comment]
> Thanks, all.
> 
> @jcarpent I see. I just don't think too much about that. The derivative of the distance between one point on the robot and the ground can be considered the derivative of pose of that point with respect to `q`, which equals to the Jacobian of that point.
> 
> Is that what you want to say?

Yes, this is correct. Just check by Finite differences to be sure your result is correct.

**Comment by ddliugit** [comment]
Thanks all!
