### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/pinocchio#960]
2.1.11 still has the version computation issues in CMake. Can we have a new release please?
I noticed we had a deprecation/API change in between. Are there any other breaking changes?

**Comment by jcarpent** [comment]
I will make a release tomorrow. There is normally no change of API, just deletion of deprecated functions (one year ago). Before making the release, I would like to adjust the packaging to handle new CMake export policy. Is it OK for you?

**Comment by wxmerkt** [comment]
Yes, that is okay. Thank you for the effort going into this

**Comment by jcarpent** [comment]
Done.
