### ISSUE TITLE
boost container limits 

### ISSUE THREAD

**Issue by hammoudbilal** [stack-of-tasks/pinocchio#969]
I have a library with boost-bindings that depends on pinocchio, when trying to compile, 
i get the following error 

usr/local/include/pinocchio/container/boost-container-limits.hpp:29:7: error: "BOOST_MPL_LIMIT_LIST_SIZE value is lower than the value of
      PINOCCHIO_BOOST_MPL_LIMIT_CONTAINER_SIZE"
    # error "BOOST_MPL_LIMIT_LIST_SIZE value is lower than the value of PINOCCHIO_BOOST_MPL_LIMIT_CONTAINER_SIZE"

I tried adding 
#include <pinocchio/container/boost-container-limits.hpp>

but it seems to generate the same error. any idea or an example on how to handle this ?

**Comment by jcarpent** [comment]
- Do you a link to your code for inspection?
- Do you use pkg-config to retrieve Pinocchio settings? 
- One quick fix is to include pinocchio before all others include:
```
#include <pinocchio/fwd.hpp>
```

**Comment by hammoudbilal** [comment]
yes I use pkg-config, the solution was to move #include <boost/python.hpp> to be the last one. Thanks for the help

**Comment by jmirabel** [comment]
Hi @jcarpent 

I keep having this problem and the only solution that works is the inclusion of pinocchio/fwd.hh. Only using the compilation flags from the pc file does not work. Does it work for you ?

**Comment by jmirabel** [comment]
I have boost 1.58, on Ubuntu 16.04.

**Comment by jmirabel** [comment]
And this is not the case on 18.04.

**Comment by GithubMingEnter** [comment]
I have include fwd.hpp, but it hints same problem
