### ISSUE TITLE
Calculate moment of inertia around the CoM

### ISSUE THREAD

**Issue by ddliugit** [stack-of-tasks/pinocchio#980]
Is there a function to calculate the moment of inertia around the CoM in Pinocchio?

**Comment by jcarpent** [comment]
Yes, sure. This is called `ccrba` and the desired quantity is available through `data.Ig`, the naming being related to the paper of Orin and Goswami.
```
pin.ccrba(model,data,q,v)
data.Ig
```

**Comment by jcarpent** [comment]
@ddliugit It would be nice if you can write a simple example of computing and using such quantities. This small example will be helpful for other users. Thanks in advance for your contribution if you are willing to.

**Comment by gabrielebndn** [comment]
I've always found that algorithm kind of funny. If all you want is Ig, then v is not needed... Instead, v is there so to compute hg from Ig... There should be st least one version of ccrba without v, I think

**Comment by jcarpent** [comment]
@gabrielebndn `Ig` comes from free from many algorithms. It is not a quantity that you have to compute separately from other quantities in general ;)
Having one algorithm for each quantity contained in Data will increase a lot the current API, without any gain in performances.

**Comment by jcarpent** [comment]
@ddliugit Any feedback or comments?

**Comment by ddliugit** [comment]
Sorry for late reply.

I try that method, it works.

I will try to implement that, but it may take some time.

**Comment by jcarpent** [comment]
OK. @ddliugit Thanks for your feedback. Hope you will be able to implement those examples.

**Comment by jcarpent** [comment]
In the meantime, I close the issue as it seems to be solved!
