### ISSUE TITLE
Issue with Eigen < 3.3 & C++11

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/pinocchio#987]
Hi,

https://github.com/stack-of-tasks/pinocchio/blob/5d0d1a951941bb5b67593e424a26a00cf5a22c74/src/math/tensor.hpp#L11

This is included if we compile with C++11, but this is not available until Eigen 3.3.

**Comment by jcarpent** [comment]
Should be solved by #986.

**Comment by jcarpent** [comment]
Solved by #986
