### ISSUE TITLE
Undefined control sequence in documentation

### ISSUE THREAD

**Issue by paLeziart** [stack-of-tasks/pinocchio#991]
Hello,

I was browsing through the documentation and I found this yellow square: 
https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/structpinocchio_1_1DataTpl.html#a71869f4dc2a2c2e0d118794db771495b. 

It may just be a typo in the source code, I do not know how to check that.

Best,

**Comment by jmirabel** [comment]
Just a typo. \JMinv... should be replaced by something like \f$ J_M^{-1} J_t\f$.

**Comment by jcarpent** [comment]
Thanks @paLeziart. It is fixed in #992. Next time, I would encourage you to give a try with `grep` in the src folder of Pinocchio to find the source code and give a try to fix it.
